HAN-FUN API: HF::UID::UID Class Reference
HF::UID::UID Class Reference
Devices » UIDs
Wrapper around UID_T pointer's.
#include <uids.h>
Public Member Functions
UID (UID_T *_uid, bool _owner=false)
Constructor.
UID (UID &&other)
Move constructor.
UID (const UID &other)
Copy constructor.
uint8_t type () const
Type of the UID.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset)
Read a message from a ByteArray.
UID & operator= (const UID &other)
Copy assignment operator.
UID & operator= (UID &&other)
Move assignment operator.
UID & operator= (UID_T *_uid)
Use the given pointer as the pointer of the underlining UID to wrap around of.
int compare (const UID &other) const
Compare the current UID with the given UID.
int compare (const UID_T &other) const
Compare the current UID with the given UID.
UID_T const * raw () const
Get the underling wrapped UID_T pointer.
float changed (const UID &other) const
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Detailed Description
Wrapper around UID_T pointer's.
This class can either wrap an existing pointer (i.e. a pointer to an object it doesn't own) or wrap a pointer to an object that was created based on an existing object. In this case the clone object is owned by this class instance.
The destructor of this class will delete the object it owns.
Definition at line 529 of file uids.h.
Constructor & Destructor Documentation
HF::UID::UID::UID (UID_T * _uid, bool _owner = false) inline
Constructor.
Parameters
[in] _uid pointer to the UID being wrapped.
[in] _owner take ownership of the pointer being wrapped.
Definition at line 548 of file uids.h.
                                               :
             _raw(_uid), owner(_owner)
          {
             assert(_uid != nullptr);
          }
HF::UID::UID::UID (UID && other) inline
Move constructor.
Parameters
[in] other UID to move from.
Definition at line 559 of file uids.h.
                          : _raw(other._raw), owner(other.owner)
          {
             other.owner = false;
          }
HF::UID::UID::UID (const UID & other) inline
Copy constructor.
The underling UID_T is cloned and this object takes ownership of it.
Parameters
[in] other UID to copy from.
Definition at line 571 of file uids.h.
                               : _raw(other._raw->clone()), owner(true)
          {}
Member Function Documentation
float HF::UID::UID::changed (const UID & other) const inline
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Parameters
[in] other attribute holding a previous value.
Returns
float indicating the percentage of change.
Definition at line 708 of file uids.h.
References compare(), operator<<(), and UNUSED.
          {
             UNUSED(other);
             return 0.0;
          }
int HF::UID::UID::compare (const UID & other) const inline
Compare the current UID with the given UID.
This function returns a value less that 0 if the current UID object order is lower that the given UID, 0 if the UIDs represent the same entity and a value greater that 0 if current UID object is above the given UID.
Parameters
[in] other a pointer to a UID object to compare to.
Return values
<0 the current UID is lower that the given UID.
0 the current UID is the same as given UID.
>0 the current UID is greater that the given UID.
Definition at line 686 of file uids.h.
References HF::UID::UID_T::compare().
Referenced by changed().
          {
             return _raw->compare(*(other._raw));
          }
int HF::UID::UID::compare (const UID_T & other) const inline
Compare the current UID with the given UID.
This function returns a value less that 0 if the current UID object order is lower that the given UID, 0 if the UIDs represent the same entity and a value greater that 0 if current UID object is above the given UID.
Parameters
[in] other a pointer to a UID object to compare to.
Return values
<0 the current UID is lower that the given UID.
0 the current UID is the same as given UID.
>0 the current UID is greater that the given UID.
Definition at line 692 of file uids.h.
References HF::UID::UID_T::compare().
          {
             return _raw->compare(other);
          }
UID& HF::UID::UID::operator= (const UID & other) inline
Copy assignment operator.
Parameters
[in] other UID to copy from.
Returns
a reference to this object.
Definition at line 625 of file uids.h.
References HF::Common::Cloneable< T >::clone().
          {
             // Ship if same object.
             if (this == &other)
             {
                return *this;
             }
             // Delete current wrapped object if owner.
             if (this->owner)
             {
                delete this->_raw;
             }
             // Clone wrapped UID_T and take ownership of the clone.
             this->_raw  = other._raw->clone();
             this->owner = true;
             return *this;
          }
UID& HF::UID::UID::operator= (UID && other) inline
Move assignment operator.
Parameters
[in] other UID to move from.
Returns
a reference to this object.
Definition at line 653 of file uids.h.
          {
             std::swap(this->_raw, other._raw);
             std::swap(this->owner, other.owner);
             return *this;
          }
UID& HF::UID::UID::operator= (UID_T * _uid) inline
Use the given pointer as the pointer of the underlining UID to wrap around of.
Warning
the class takes ownership of the pointer and will delete the associated object when it is destructed.
Parameters
_uid pointer to the UID_T object instance to manage.
Returns
reference to self.
Definition at line 672 of file uids.h.
          {
             if (owner)
             {
                delete this->_raw;
             }
             _raw  = _uid;
             owner = true;
             return *this;
          }
uint16_t HF::UID::UID::pack (Common::ByteArray & array, uint16_t offset) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Implements HF::Common::Serializable.
Definition at line 607 of file uids.h.
References HF::UID::UID_T::pack(), and HF::UID::UID_T::unpack().
Referenced by hello_msg_t::pack().
          {
             return _raw->pack(array, offset);
          }
UID_T const* HF::UID::UID::raw () const inline
Get the underling wrapped UID_T pointer.
Returns
the underling wrapped UID_T pointer.
Definition at line 702 of file uids.h.
Referenced by print_error(), and to_json().
          {
             return _raw;
          }
uint16_t HF::UID::UID::size () const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Implements HF::Common::Serializable.
Definition at line 602 of file uids.h.
References HF::UID::UID_T::size().
Referenced by hello_msg_t::size().
          {
             return _raw->size();
          }
uint8_t HF::UID::UID::type () const inline
Type of the UID.
See also
HF::UID::Type.
Returns
type of the UID.
Definition at line 587 of file uids.h.
References HF::UID::UID_T::compare(), and HF::UID::UID_T::type().
Referenced by to_json().
          {
             return _raw->type();
          }
uint16_t HF::UID::UID::unpack (const Common::ByteArray & array, uint16_t offset) virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Implements HF::Common::Serializable.
Referenced by hello_msg_t::unpack().
The documentation for this class was generated from the following file:
uids.h