HAN-FUN API: HF::Attributes::AbstractAttribute Class Reference
HF::Attributes::AbstractAttribute Class Reference
Protocol » Attributes
Parent class for Attribute API implementation.
#include <attributes.h>
Public Member Functions
uint8_t uid () const
Attribute's UID.
bool isWritable () const
Indicate if the attribute is writable.
uint16_t interface () const
Return the UID of the interface the attribute belongs to.
int compare (const IAttribute &other) const
Compare this attribute with the given attribute in other.
Public Member Functions inherited from HF::Attributes::IAttribute
virtual HF::Interface const * owner () const =0
Pointer to the interface that owns this attribute.
virtual uint16_t size (bool with_uid) const =0
Number bytes needed to serialize the message.
virtual uint16_t size () const =0
Number bytes needed to serialize the message.
virtual uint16_t pack (Common::ByteArray &array, uint16_t offset, bool with_uid) const =0
Write the object on to a ByteArray so it can be sent over the network.
virtual uint16_t pack (Common::ByteArray &array, uint16_t offset) const =0
Write the object on to a ByteArray so it can be sent over the network.
virtual uint16_t unpack (const Common::ByteArray &array, uint16_t offset, bool with_uid)=0
Read a message from a ByteArray.
virtual uint16_t unpack (const Common::ByteArray &array, uint16_t offset)=0
Read a message from a ByteArray.
virtual float changed (const IAttribute &other) const =0
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from HF::Common::Cloneable< IAttribute >
virtual IAttribute * clone () const =0
Create a clone object of the object where this method is being called.
Protected Attributes
const uint16_t _itf_uid
Interface this attribute belongs to.
const uint8_t _uid
Attribute unique identifier.
const bool _writable
Attribute access mode.
Detailed Description
Parent class for Attribute API implementation.
Definition at line 269 of file attributes.h.
Member Function Documentation
int HF::Attributes::AbstractAttribute::compare (const IAttribute & other) const inline virtual
Compare this attribute with the given attribute in other.
This method should return < 0 if this attribute is less that, 0 if it is equal and > 0 if greater that the other attribute.
Parameters
[in] other attribute to compare to.
Return values
<0 if attribute less than other;
0 if attribute equal to other;
>0 if attribute greater than other.
Implements HF::Attributes::IAttribute.
Reimplemented in HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< uint8_t >, and HF::Attributes::Attribute< bool >.
Definition at line 328 of file attributes.h.
References HF::Attributes::IAttribute::interface(), interface(), HF::Attributes::IAttribute::uid(), and uid().
Referenced by HF::Attributes::Attribute< bool >::changed(), HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::changed(), HF::Attributes::Attribute< bool >::compare(), and HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::compare().
          {
             int res = this->interface () - other.interface ();
             if (res != 0)
             {
                return res;
             }
             return this->uid () - other.uid ();
          }
uint16_t HF::Attributes::AbstractAttribute::interface () const inline virtual
Return the UID of the interface the attribute belongs to.
Returns
UID of the interface the attribute belongs to.
Implements HF::Attributes::IAttribute.
Definition at line 293 of file attributes.h.
References _itf_uid.
Referenced by compare().
          {
             return _itf_uid;
          }
bool HF::Attributes::AbstractAttribute::isWritable () const inline virtual
Indicate if the attribute is writable.
Return values
true if the attribute is writable,
false otherwise.
Implements HF::Attributes::IAttribute.
Definition at line 288 of file attributes.h.
References _writable.
Referenced by HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::clone().
          {
             return _writable;
          }
uint8_t HF::Attributes::AbstractAttribute::uid () const inline virtual
Attribute's UID.
Returns
the attribute's UID value.
Implements HF::Attributes::IAttribute.
Definition at line 283 of file attributes.h.
References _uid.
Referenced by HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::clone(), compare(), HF::Attributes::Attribute< bool >::pack(), HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::pack(), HF::Attributes::Attribute< bool >::unpack(), and HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::unpack().
          {
             return _uid;
          }
Field Documentation
const uint16_t HF::Attributes::AbstractAttribute::_itf_uid protected
Interface this attribute belongs to.
Definition at line 273 of file attributes.h.
Referenced by HF::Attributes::Attribute< bool >::clone(), and interface().
const uint8_t HF::Attributes::AbstractAttribute::_uid protected
Attribute unique identifier.
Definition at line 274 of file attributes.h.
Referenced by HF::Attributes::Attribute< bool >::clone(), and uid().
const bool HF::Attributes::AbstractAttribute::_writable protected
Attribute access mode.
Definition at line 275 of file attributes.h.
Referenced by HF::Attributes::Attribute< bool >::clone(), and isWritable().
The documentation for this class was generated from the following file:
attributes.h