HAN-FUN API: HF::Devices::Concentrator::Abstract< CoreServices > Class Template Reference
HF::Devices::Concentrator::Abstract< CoreServices > Class Template Reference
Devices » Concentrator device API.
Template for HAN-FUN concentrator devices.
#include <devices.h>
Public Member Functions
CoreServices * unit0 () const
Get the unit 0 used by this concentrator device.
Public Member Functions inherited from HF::Devices::Concentrator::AbstractBase
uint16_t address () const
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
void connected (HF::Transport::Link *link)
Callback to report that a new transport link was been created to a remote device.
void disconnected (HF::Transport::Link *link)
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
void receive (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Callback to deliver a packet received from the transport layer.
Public Member Functions inherited from HF::Devices::AbstractDevice
const IUnits & units () const
Return the list of units registered in this device.
void add (Units::IUnit *unit)
Add unit to devices unit lists.
void remove (Units::IUnit *unit)
Remove unit from device's unit list.
Units::IUnit * unit (uint8_t id) const
Return pointer to the unit with the given id.
void send (Protocol::Packet &packet)
Send given packet into the HAN-FUN network.
void periodic (uint32_t time)
Handle periodic processing.
Events
Additional Inherited Members
Protected Member Functions inherited from HF::Devices::Concentrator::AbstractBase
HF::Transport::Link * link (uint16_t addr) const
Return the link that can be used to send a packet to the device with the given address.
virtual void route_packet (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Route the given packet to the corresponding device.
Protected Member Functions inherited from HF::Devices::AbstractDevice
virtual bool is_local (Protocol::Packet &packet)
Check if the given packet is for this device.
bool is_registered ()
Check if the device has a valid, i.e.
Protected Attributes inherited from HF::Devices::Concentrator::AbstractBase
Common::SimpleList
< Transport::Link * > _links
List of links present in this concentrator.
Protected Attributes inherited from HF::Devices::AbstractDevice
uint8_t next_reference
Last reference number used to send a packet.
IUnits _units
List containing pointers to the units present in the device.
Protocol::Filters::ResponseRequired response_filter
Support for generating missing responses for messages.
Detailed Description
template<typename CoreServices = DefaultUnit0>
class HF::Devices::Concentrator::Abstract< CoreServices >
Template for HAN-FUN concentrator devices.
Definition at line 641 of file devices.h.
Member Function Documentation
template<typename CoreServices = DefaultUnit0> CoreServices* HF::Devices::Concentrator::Abstract< CoreServices >::unit0 () const inline virtual
Get the unit 0 used by this concentrator device.
Returns
pointer to the unit 0 used by this concentrator device.
Implements HF::Devices::Concentrator::AbstractBase.
Definition at line 645 of file devices.h.
Referenced by COMMAND(), HF::Application::Restore(), and HF::Application::Save().
             {
                return const_cast <CoreServices *>(&_unit0);
             }
The documentation for this class was generated from the following file:
devices.h