HAN-FUN API: HF::Units::Unit< Profile, ITF > Class Template Reference
HF::Units::Unit< Profile, ITF > Class Template Reference
Devices » Units API
Helper template class to implement units.
#include <units.h>
Public Member Functions
Unit (uint8_t id, IDevice &device)
Constructor.
uint8_t id () const
Get the id number of this unit on the device.
uint16_t uid () const
Return this profile HAN-FUN UID.
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
HF::Attributes::List attributes (Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
void send (const Protocol::Address &addr, Protocol::Message &message)
Send message msg to the network address given by addr.
void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify the attribute reporting service that the given attribute has changed value.
std::vector< Common::Interface > interfaces () const
Return the list of optional interfaces implemented by this unit.
void periodic (uint32_t time)
Handle periodic processing.
Public Member Functions inherited from HF::Units::AbstractUnit
IDevice & device () const
Reference to the device this unit belongs to.
void send (const Protocol::Address &addr, Protocol::Message &message, Transport::Link *link)
Create and send a new packet with the given message to the given address.
Protected Member Functions
template<uint8_t N>
const std::tuple_element< N,
interfaces_t >::type::base * get () const
Retrieve a pointer to the N optional interface implemented by this unit.
void for_each (std::function< void(HF::Interface &)> func) const
Call the given function for all the implemented optional interfaces.
void for_each (std::function< void(HF::Interface &)> func)
Call the given function for all the implemented optional interfaces.
Protected Member Functions inherited from HF::Units::AbstractUnit
AbstractUnit (IDevice &device)
Constructor.
void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify the attribute reporting service that the given attribute has changed value.
Additional Inherited Members
Protected Attributes inherited from HF::Units::AbstractUnit
uint8_t _id
Unit ID used to identify a given unit in a given HAN-FUN device.
Detailed Description
template<class Profile, typename... ITF>
class HF::Units::Unit< Profile, ITF >
Helper template class to implement units.
Definition at line 147 of file units.h.
Constructor & Destructor Documentation
template<class Profile, typename... ITF> HF::Units::Unit< Profile, ITF >::Unit (uint8_t id, IDevice & device) inline
Constructor.
Parameters
[in] id unit identifier.
[in] device device that contains this units.
Definition at line 177 of file units.h.
                                           :
             Profile (), HF::Units::AbstractUnit (device), _id (id),
             _interfaces (Proxy <ITF, Unit>(*this) ...)
          {}
Member Function Documentation
template<class Profile, typename... ITF> HF::Attributes::List HF::Units::Unit< Profile, ITF >::attributes (Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS & uids) const inline virtual
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
Parameters
[in] itf interface UID.
[in] pack_id attribute pack id.
[in] uids list of attributes UID's.
Returns
attribute list.
Implements HF::Profiles::IProfile.
Definition at line 219 of file units.h.
          {
             auto result = Profile::attributes (itf, pack_id, uids);
             attributes_itf <0, ITF...>(result, itf, pack_id, uids);
             return result;
          }
template<class Profile, typename... ITF> void HF::Units::Unit< Profile, ITF >::for_each (std::function< void(HF::Interface &)> func) const inline protected
Call the given function for all the implemented optional interfaces.
Parameters
[in] func function to call with each of the optional implemented interfaces.
Definition at line 297 of file units.h.
Referenced by HF::Units::Unit< HF::Profiles::SimpleLight >::for_each(), HF::Units::Unit< HF::Profiles::SimpleLight >::interfaces(), and HF::Units::Unit< HF::Profiles::SimpleLight >::periodic().
          {
             for_each <0, ITF...>(func);
          }
template<class Profile, typename... ITF> void HF::Units::Unit< Profile, ITF >::for_each (std::function< void(HF::Interface &)> func) inline protected
Call the given function for all the implemented optional interfaces.
Parameters
[in] func function to call with each of the optional implemented interfaces.
Definition at line 307 of file units.h.
          {
             for_each <0, ITF...>(func);
          }
template<class Profile, typename... ITF> template<uint8_t N> const std::tuple_element<N, interfaces_t>::type::base* HF::Units::Unit< Profile, ITF >::get () const inline protected
Retrieve a pointer to the N optional interface implemented by this unit.
Template Parameters
N index of the interface to retrieve the pointer to.
Returns
a pointer to the optional implemented interface.
Definition at line 287 of file units.h.
          {
             return &std::get <N>(_interfaces);
          }
template<class Profile, typename... ITF> Common::Result HF::Units::Unit< Profile, ITF >::handle (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) inline virtual
Handle incoming messages from the network.
Parameters
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
Implements HF::Units::IUnit.
Definition at line 195 of file units.h.
          {
             Common::Result result = Profile::handle (packet, payload, offset);
             // Message not handled by base profile, then try extra interfaces.
             if (result == Common::Result::FAIL_ARG)
             {
                Interface *itf = find <0, ITF...>(packet.message.itf.id);
                if (itf != nullptr)
                {
                   return itf->handle (packet, payload, offset);
                }
                else
                {
                   return Common::Result::FAIL_SUPPORT;
                }
             }
             return result;
          }
template<class Profile, typename... ITF> uint8_t HF::Units::Unit< Profile, ITF >::id () const inline virtual
Get the id number of this unit on the device.
Returns
id number of this unit on the device.
Implements HF::Units::IUnit.
Definition at line 183 of file units.h.
          {
             return _id;
          }
template<class Profile, typename... ITF> std::vector<Common::Interface> HF::Units::Unit< Profile, ITF >::interfaces () const inline virtual
Return the list of optional interfaces implemented by this unit.
Returns
a vector containing the UIDs for the optional interfaces implemented by this unit.
Reimplemented from HF::Units::AbstractUnit.
Definition at line 250 of file units.h.
          {
             std::vector <Common::Interface> result;
             result.reserve (sizeof ... (ITF));
             Common::Interface temp;
             /* *INDENT-OFF* */
             for_each ([&result, &temp](HF::Interface &itf)
             {
                 temp.id = itf.uid ();
                 temp.role = itf.role ();
                 result.push_back (temp);
             });
             /* *INDENT-ON* */
             return result;
          }
template<class Profile, typename... ITF> void HF::Units::Unit< Profile, ITF >::notify (const HF::Attributes::IAttribute & old_value, const HF::Attributes::IAttribute & new_value) const inline
Notify the attribute reporting service that the given attribute has changed value.
Parameters
[in] old_value reference to the previous value of the attribute.
[in] new_value reference to the current value of the attribute.
Definition at line 238 of file units.h.
          {
             AbstractUnit::notify (old_value, new_value);
          }
template<class Profile, typename... ITF> void HF::Units::Unit< Profile, ITF >::periodic (uint32_t time) inline virtual
Handle periodic processing.
Parameters
[in] time current system clock value in seconds.
Reimplemented from HF::Units::AbstractUnit.
Definition at line 268 of file units.h.
          {
             Profile::periodic (time);
             /* *INDENT-OFF* */
             for_each ([time](HF::Interface &itf) { itf.periodic (time);});
             /* *INDENT-ON* */
          }
template<class Profile, typename... ITF> void HF::Units::Unit< Profile, ITF >::send (const Protocol::Address & addr, Protocol::Message & message) inline
Send message msg to the network address given by addr.
Parameters
[in] addr HF network address.
[in] message pointer to the message to be sent to the network.
Definition at line 232 of file units.h.
          {
             AbstractUnit::send (addr, message, nullptr);
          }
template<class Profile, typename... ITF> uint16_t HF::Units::Unit< Profile, ITF >::uid () const inline virtual
Return this profile HAN-FUN UID.
Returns
the UID associated with this profile.
See also
IProfile::UID.
Implements HF::Profiles::IProfile.
Definition at line 189 of file units.h.
          {
             return Profile::uid ();
          }
The documentation for this class was generated from the following file:
units.h