HAN-FUN API: HF::Core::GroupManagement::IServer Class Reference
HF::Core::GroupManagement::IServer Class Reference abstract
Core Services & Interfaces » Group Management
Group Management Service : Server side implementation.
#include <group_management.h>
Public Member Functions
IServer (Unit0 &unit)
Constructor.
virtual ~IServer ()
Destructor.
HF::Devices::Concentrator::IUnit0 * unit0 () const
Return a reference to the unit that this service belongs to.
virtual IEntries & entries () const =0
Get a reference to the current object implementing the persistence API, for the device information.
GroupPtr entry (const uint16_t address) const
Get the group entry given by address.
GroupPtr entry (const std::string &name) const
Get the group entry given by name.
uint16_t next_address () const
Return next available address for device group.
uint8_t number_of_groups () const
Get the Number Of Groups for the Group Management server.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
HF::Attributes::UIDS attributes (uint8_t pack_id=HF::Attributes::Pack::MANDATORY) const
Return a vector containing the attribute UIDs, for the given pack ID.
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
Events
virtual Common::Result create (Protocol::Packet &packet, CreateMessage &msg)
Callback that is called when a GroupManagement::CREATE_CMD, is received.
virtual void created (const GroupPtr &group)
Indicate that a new group was created.
virtual Common::Result remove (Protocol::Packet &packet, DeleteMessage &msg)
Callback that is called when a GroupManagement::DELETE_CMD, is received.
virtual void deleted (const Group &group)
Indicate that a group was deleted.
virtual Common::Result add (Protocol::Packet &packet, const AddMessage &msg)
Callback that is called when a GroupManagement::ADD_CMD, is received.
virtual void added (const GroupPtr &group, const Member &member)
Indicate that a new device/unit was added to an existing group.
virtual Common::Result remove (Protocol::Packet &packet, const RemoveMessage &msg)
Callback that is called when a GroupManagement::REMOVE_CMD, is received.
virtual void removed (const GroupPtr &group, const Member &member)
Indicate that a device/unit was removed from an existing group.
Public Member Functions inherited from HF::Core::ServiceRole< GroupManagement::Base, HF::Interface::SERVER_ROLE >
Interface::Role role () const
Return the Interface::Role this interface implements.
Public Member Functions inherited from HF::Core::Service< HF::Interface::GROUP_MANAGEMENT >
uint16_t uid () const
This method returns the interface UID.
Public Member Functions inherited from HF::Core::AbstractService
Unit0 & unit () const
The device this unit is associated with.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
HF::Attributes::UIDS attributes (uint8_t pack_id=HF::Attributes::Pack::MANDATORY) const
Return a vector containing the attribute UIDs, for the given pack ID.
Public Member Functions inherited from HF::Interfaces::AbstractInterface
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void periodic (uint32_t time)
Handle periodic processing.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
Protected Member Functions
virtual bool authorized (CMD member, const Protocol::Address &source, const Protocol::Address &destination)
This method serves to indicate if a given member of the interface can be used by the source device affecting the destination device configuration on the system.
void number_of_groups_update (int8_t diff) const
Get the Number Of Groups for the Group Management server.
uint16_t payload_size (Protocol::Message::Interface &itf) const
Return the minimal payload size that a message should hold when addressed at the given interface.
Common::Result handle_command (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void added (const Protocol::Address &addr, Common::Result result, const AddMessage &request, uint8_t reference)
Process the result of adding a device to a group.
virtual IGroupTable & group_table () const =0
Get the Group Table client associated with this Group Management server.
Protected Member Functions inherited from HF::Core::ServiceRole< GroupManagement::Base, HF::Interface::SERVER_ROLE >
ServiceRole (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Core::GroupManagement::Base
Base (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Core::Service< HF::Interface::GROUP_MANAGEMENT >
Service (Unit0 &unit)
Constructor.
bool check_uid (uint16_t uid) const
Check if the given uid value matches the service's UID value.
Protected Member Functions inherited from HF::Core::AbstractService
AbstractService (Unit0 &unit)
Constructor.
void send (const Protocol::Address &addr, Protocol::Message &message)
Send message msg to the network address given by addr.
void send (const Protocol::Address &addr, Protocol::Message &message, Transport::Link *link)
Create and send a new packet with the given message to the given address.
Protected Member Functions inherited from HF::Interfaces::AbstractInterface
virtual void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify that an attribute value as changed.
Common::Result check (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if message has correct attributes to be processed by the interface.
Common::Result check_payload_size (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if payload data size if sufficient for processing the message.
virtual uint16_t payload_size (Protocol::Message &message) const
Return the minimal payload size that should be present for the given message.
template<typename _Message >
uint16_t payload_size_helper () const
Helper function template to retrieve minimum size required for serializing/deserializing the class given.
virtual Common::Result handle_attribute (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
Additional Inherited Members
Public Types inherited from HF::Interface
enum Role { CLIENT_ROLE = 0, SERVER_ROLE = 1 }
Interface roles.
enum UID {
DEVICE_MANAGEMENT = 0x0001, BIND_MANAGEMENT = 0x0002, GROUP_MANAGEMENT = 0x0003, IDENTIFY = 0x0004,
DEVICE_INFORMATION = 0x0005, ATTRIBUTE_REPORTING = 0x0006, BATCH_PROGRAM_MANAGEMENT = 0x0007, EVENT_SCHEDULING = 0x0008,
WEEKLY_SCHEDULING = 0x0009, GROUP_TABLE = 0x000A, TAMPER_ALERT = 0x0101, TIME = 0x0102,
POWER = 0x0110, KEEP_ALIVE = 0x0115, RSSI = 0x0111, SUOTA = 0x0400,
ALERT = 0x0100, ON_OFF = 0x0200, LEVEL_CONTROL = 0x0201, COLOUR_CONTROL = 0x0202,
SIMPLE_KEYPAD = 0x0203, SIMPLE_POWER_METER = 0x0300, SIMPLE_TEMPERATURE = 0x0301, SIMPLE_HUMIDITY = 0x0302,
SIMPLE_THERMOSTAT = 0x0303, SIMPLE_BUTTON = 0x0304, SIMPLE_VISUAL_EFFECTS = 0x0305, SIMPLE_AIR_PRESSURE = 0x0306,
SIMPLE_LIGHT_SENSOR = 0x0307, RESERVED = 0x7F00, MAX_UID = 0x7FFE, ANY_UID = 0x7FFF
}
Interfaces Unique Identifiers (UID).
Static Public Attributes inherited from HF::Interface
static constexpr uint8_t MAX_CMD_ID = 0xFF
Maximum value for command IDs in interfaces.
Protected Attributes inherited from HF::Core::AbstractService
Unit0 & _unit
Reference to the unit the service belongs to.
Detailed Description
Group Management Service : Server side implementation.
This class provides the server side of the Group Management interface.
Definition at line 744 of file group_management.h.
Member Function Documentation
add()
virtual Common::Result HF::Core::GroupManagement::IServer::add (Protocol::Packet & packet, const AddMessage & msg) virtual
Callback that is called when a GroupManagement::ADD_CMD, is received.
Parameters
[in] packet the message Packet.
[in] msg the CreateMessage received.
Returns
the response code sent in the response.
added() [1/2]
virtual void HF::Core::GroupManagement::IServer::added (const GroupPtr & group, const Member & member) inline virtual
Indicate that a new device/unit was added to an existing group.
Parameters
[in] group reference to a pointer to the group entry corresponding to the group where a member was added.
[in] member reference to the member added.
Definition at line 824 of file group_management.h.
References UNUSED.
             {
                UNUSED(group);
                UNUSED(member);
             }
added() [2/2]
void HF::Core::GroupManagement::IServer::added (const Protocol::Address & addr, Common::Result result, const AddMessage & request, uint8_t reference) protected
Process the result of adding a device to a group.
Parameters
[in] addr HF address of the device that requested the HF::GroupManagement::ADD_CMD command.
[in] result the result of the operation.
[in] request the payload for the HF::GroupManagement::ADD_CMD command.
[in] reference Application reference for the initial request.
attribute()
HF::Attributes::IAttribute* HF::Core::GroupManagement::IServer::attribute (uint8_t uid) virtual
Return a pointer to the interface attribute with the given uid.
Parameters
[in] uid identifier of the attribute in the interface.
Returns
a pointer to the attribute if it exists, nullptr otherwise.
Implements HF::Interface.
attributes()
HF::Attributes::UIDS HF::Core::GroupManagement::IServer::attributes (uint8_t pack_id = HF::Attributes::Pack::MANDATORY) const inline virtual
Return a vector containing the attribute UIDs, for the given pack ID.
Parameters
[in] pack_id the Attribute pack ID to get the attributes UIDs for.
Returns
vector containing the attributes UIDs.
Reimplemented from HF::Interfaces::AbstractInterface.
Definition at line 945 of file group_management.h.
References HF::Core::GroupManagement::NUMBER_OF_GROUPS_ATTR, and UNUSED.
             {
                UNUSED(pack_id);
                return HF::Attributes::UIDS {NUMBER_OF_GROUPS_ATTR};
             }
authorized()
virtual bool HF::Core::GroupManagement::IServer::authorized (CMD member, const Protocol::Address & source, const Protocol::Address & destination) inline protected virtual
This method serves to indicate if a given member of the interface can be used by the source device affecting the destination device configuration on the system.
Parameters
[in] member interface member UID.
[in] source HF address for the requesting device.
[in] destination HF address for the affected device.
Return values
true the operation is allowed,
false otherwise.
Definition at line 969 of file group_management.h.
References UNUSED.
             {
                UNUSED(member);
                UNUSED(source);
                UNUSED(destination);
                return true;
             }
create()
virtual Common::Result HF::Core::GroupManagement::IServer::create (Protocol::Packet & packet, CreateMessage & msg) virtual
Callback that is called when a GroupManagement::CREATE_CMD, is received.
Parameters
[in] packet the message Packet.
[in] msg the CreateMessage received.
Returns
the response code sent in the response.
created()
virtual void HF::Core::GroupManagement::IServer::created (const GroupPtr & group) inline virtual
Indicate that a new group was created.
Parameters
[in] group pointer to the group entry corresponding to the created group.
Definition at line 779 of file group_management.h.
References UNUSED.
             {
                UNUSED(group);
             }
deleted()
virtual void HF::Core::GroupManagement::IServer::deleted (const Group & group) inline virtual
Indicate that a group was deleted.
Parameters
[in] group reference to a copy of the group entry that was deleted.
Definition at line 800 of file group_management.h.
References UNUSED.
             {
                UNUSED(group);
             }
entries()
virtual IEntries& HF::Core::GroupManagement::IServer::entries () const pure virtual
Get a reference to the current object implementing the persistence API, for the device information.
Returns
reference to the current object for the persistence API.
Implemented in HF::Core::GroupManagement::Server< _Entries, _GroupTable >.
Referenced by entry(), next_address(), and number_of_groups().
entry() [1/2]
GroupPtr HF::Core::GroupManagement::IServer::entry (const uint16_t address) const inline
Get the group entry given by address.
Parameters
[in] address group address of the group to retrieve.
Returns
a pointer to the group if it exists, nullptr otherwise.
Definition at line 899 of file group_management.h.
References entries(), and HF::Core::GroupManagement::IEntries::find().
             {
                return entries().find(address);
             }
entry() [2/2]
GroupPtr HF::Core::GroupManagement::IServer::entry (const std::string & name) const inline
Get the group entry given by name.
Parameters
[in] name group name of the group to retrieve.
Returns
a pointer to the group if it exists, nullptr otherwise.
Definition at line 912 of file group_management.h.
References entries(), and HF::Core::GroupManagement::IEntries::find().
             {
                return entries().find(name);
             }
group_table()
virtual IGroupTable& HF::Core::GroupManagement::IServer::group_table () const protected pure virtual
Get the Group Table client associated with this Group Management server.
Returns
reference to the Group Table client used by this Group Management server.
Implemented in HF::Core::GroupManagement::Server< _Entries, _GroupTable >.
handle()
Common::Result HF::Core::GroupManagement::IServer::handle (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) virtual
Handle incoming messages from the network.
Parameters
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
Implements HF::Interface.
handle_command()
Common::Result HF::Core::GroupManagement::IServer::handle_command (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) protected virtual
Handle incoming messages from the network.
Parameters
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
Handle command request/response messages, i.e. :
Protocol::Message:Type::COMMAND_REQ;
Protocol::Message:Type::COMMAND_RESP_REQ;
Protocol::Message:Type::COMMAND_RES;
Reimplemented from HF::Interfaces::AbstractInterface.
next_address()
uint16_t HF::Core::GroupManagement::IServer::next_address () const inline
Return next available address for device group.
Returns
the address to use in the next group, or GroupAddress::NO_ADDR if no address is available.
Definition at line 920 of file group_management.h.
References entries(), and HF::Core::GroupManagement::IEntries::next_address().
             {
                return entries().next_address();
             }
number_of_groups()
uint8_t HF::Core::GroupManagement::IServer::number_of_groups () const inline
Get the Number Of Groups for the Group Management server.
Returns
the current Number Of Groups.
Definition at line 934 of file group_management.h.
References entries(), and HF::Common::IEntries< T >::size().
Referenced by number_of_groups_update().
             {
                return (uint8_t) entries().size();
             }
number_of_groups_update()
void HF::Core::GroupManagement::IServer::number_of_groups_update (int8_t diff) const inline protected
Get the Number Of Groups for the Group Management server.
Parameters
[in] diff number of groups added/removed.
Returns
the current Number Of Groups.
Definition at line 985 of file group_management.h.
References HF::Interfaces::AbstractInterface::notify(), and number_of_groups().
             {
                uint8_t value = number_of_groups();
                NumberOfGroups old_attr(value - diff, this);
                NumberOfGroups new_attr(value, this);
                notify(old_attr, new_attr);
             }
payload_size()
uint16_t HF::Core::GroupManagement::IServer::payload_size (Protocol::Message::Interface & itf) const protected virtual
Return the minimal payload size that a message should hold when addressed at the given interface.
Parameters
[in] itf the interface being address.
Returns
the minimum number of bytes for the message for the interface.
Reimplemented from HF::Interfaces::AbstractInterface.
remove() [1/2]
virtual Common::Result HF::Core::GroupManagement::IServer::remove (Protocol::Packet & packet, DeleteMessage & msg) virtual
Callback that is called when a GroupManagement::DELETE_CMD, is received.
Parameters
[in] packet the message Packet.
[in] msg the DeleteMessage received.
Returns
the response code sent in the response.
remove() [2/2]
virtual Common::Result HF::Core::GroupManagement::IServer::remove (Protocol::Packet & packet, const RemoveMessage & msg) virtual
Callback that is called when a GroupManagement::REMOVE_CMD, is received.
Parameters
[in] packet the message Packet.
[in] msg the RemoveMessage received.
Returns
the response code sent in the response.
removed()
virtual void HF::Core::GroupManagement::IServer::removed (const GroupPtr & group, const Member & member) inline virtual
Indicate that a device/unit was removed from an existing group.
Parameters
[in] group pointer to the group entry corresponding to the affected group.
[in] member reference to the member entry removed.
Definition at line 847 of file group_management.h.
References UNUSED.
             {
                UNUSED(group);
                UNUSED(member);
             }
unit0()
HF::Devices::Concentrator::IUnit0* HF::Core::GroupManagement::IServer::unit0 () const
Return a reference to the unit that this service belongs to.
This is the same reference as AbstractService::unit, but static casted to allow access to the other interfaces.
Returns
a reference to the unit that holds this interface.
The documentation for this class was generated from the following file:
group_management.h