HAN-FUN API: HF::Interfaces::LevelControl::Client Class Reference
HF::Interfaces::LevelControl::Client Class Reference
Level Control Interface
Level Control Interface : Client side implementation.
#include <level_control.h>
Public Member Functions
Commands
void level (Protocol::Address &addr, uint8_t new_level)
Send a SET_LEVEL_CMD to the given address to set the level at new_level.
void level (uint8_t new_level)
Send a SET_LEVEL_CMD to broadcast network address to set the level at new_level.
void level (Protocol::Address &addr, float new_level)
Send a SET_LEVEL_CMD to the given address to set the level at new_level.
void level (float new_level)
Send a SET_LEVEL_CMD to broadcast network address to set the level at new_level.
Public Member Functions inherited from HF::Interfaces::InterfaceRole< LevelControl::Base, HF::Interface::CLIENT_ROLE >
HF::Interface::Role role () const
Return the Interface::Role this interface implements.
Public Member Functions inherited from HF::Interfaces::Interface< HF::Interface::LEVEL_CONTROL >
uint16_t uid () const
This method returns the interface UID.
Public Member Functions inherited from HF::Interfaces::AbstractInterface
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void periodic (uint32_t time)
Handle periodic processing.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
virtual HF::Attributes::UIDS attributes (uint8_t pack_id=HF::Attributes::Pack::MANDATORY) const
Return a vector containing the attribute UIDs, for the given pack ID.
Additional Inherited Members
Public Types inherited from HF::Interface
enum Role { CLIENT_ROLE = 0, SERVER_ROLE = 1 }
Interface roles.
enum UID {
DEVICE_MANAGEMENT = 0x0001, BIND_MANAGEMENT = 0x0002, GROUP_MANGEMENT = 0x0003, IDENTIFY = 0x0004,
DEVICE_INFORMATION = 0x0005, ATTRIBUTE_REPORTING = 0x0006, BATCH_PROGRAM_MANGEMENT = 0x0007, EVENT_SCHEDULING = 0x0008,
WEEKLY_SCHEDULING = 0x0009, TAMPER_ALERT = 0x0101, TIME = 0x0102, POWER = 0x0110,
KEEP_ALIVE = 0x0115, RSSI = 0x0111, SUOTA = 0x0400, ALERT = 0x0100,
ON_OFF = 0x0200, LEVEL_CONTROL = 0x0201, SIMPLE_POWER_METER = 0x0300, SIMPLE_TEMPERATURE = 0x0301,
SIMPLE_HUMIDITY = 0x0302, SIMPLE_THERMOSTAT = 0x0303, SIMPLE_BUTTON = 0x0304, SIMPLE_VISUAL_EFFECTS = 0x0305,
SIMPLE_AIR_PRESSURE = 0x0306, RESERVED = 0x7F00, MAX_UID = 0x7FFE, ANY_UID = 0x7FFF
}
Interfaces Unique Identifiers (UID).
Static Public Attributes inherited from HF::Interface
static constexpr uint8_t MAX_CMD_ID = 0xFF
Maximum value for command IDs in interfaces.
Protected Member Functions inherited from HF::Interfaces::LevelControl::Base
uint16_t payload_size (Protocol::Message::Interface &itf) const
Return the minimal payload size that a message should hold when addressed at the given interface.
void check_and_fix (float &value)
Make sure level percentage values is in range [0,100].
Protected Member Functions inherited from HF::Interfaces::AbstractInterface
virtual void send (const Protocol::Address &addr, Protocol::Message &message)=0
Send message msg to the network address given by addr.
virtual void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify that an attribute value as changed.
Common::Result check (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if message has correct attributes to be processed by the interface.
Common::Result check_payload_size (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if payload data size if sufficient for processing the message.
virtual uint16_t payload_size (Protocol::Message &message) const
Return the minimal payload size that should be present for the given message.
template<typename _Message >
uint16_t payload_size_helper () const
Helper function template to retrieve minimum size required for serializing/deserializing the class given.
virtual Common::Result handle_command (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
virtual Common::Result handle_attribute (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
Detailed Description
Level Control Interface : Client side implementation.
This class provides the client side of the Level Control interface.
Definition at line 288 of file level_control.h.
Member Function Documentation
void HF::Interfaces::LevelControl::Client::level (Protocol::Address & addr, uint8_t new_level)
Send a SET_LEVEL_CMD to the given address to set the level at new_level.
Parameters
[in] addr network address to send the message to.
[in] new_level level value to send in the message.
Referenced by level().
void HF::Interfaces::LevelControl::Client::level (uint8_t new_level) inline
Send a SET_LEVEL_CMD to broadcast network address to set the level at new_level.
Parameters
[in] new_level level value to send in the message.
Definition at line 313 of file level_control.h.
References level().
             {
                Protocol::Address addr;
                level(addr, new_level);
             }
void HF::Interfaces::LevelControl::Client::level (Protocol::Address & addr, float new_level)
Send a SET_LEVEL_CMD to the given address to set the level at new_level.
Parameters
[in] addr network address to send the message to.
[in] new_level level value to send in the message.
Remarks
This method converts the given new_level percentage value in the range of [0,100] to the range used by the interface [0-255].
void HF::Interfaces::LevelControl::Client::level (float new_level) inline
Send a SET_LEVEL_CMD to broadcast network address to set the level at new_level.
Parameters
[in] new_level level value to send in the message.
Definition at line 330 of file level_control.h.
References level().
             {
                Protocol::Address addr;
                level(addr, new_level);
             }
The documentation for this class was generated from the following file:
level_control.h