HAN-FUN API: HF::Devices::Node::Abstract< CoreServices > Class Template Reference
HF::Devices::Node::Abstract< CoreServices > Class Template Reference
Devices » Node device API.
Template for declaring HAN-FUN node devices.
#include <devices.h>
Public Member Functions
void connected (HF::Transport::Link *link)
Callback to report that a new transport link was been created to a remote device.
void disconnected (HF::Transport::Link *link)
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
void receive (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Callback to deliver a packet received from the transport layer.
uint16_t address () const
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
CoreServices * unit0 () const
Return pointer to the unit 0 for this device.
Public Member Functions inherited from HF::Devices::AbstractDevice
const IUnits & units () const
Return the list of units registered in this device.
void add (Units::IUnit *unit)
Add unit to devices unit lists.
void remove (Units::IUnit *unit)
Remove unit from device's unit list.
Units::IUnit * unit (uint8_t id) const
Return pointer to the unit with the given id.
void send (Protocol::Packet &packet)
Send given packet into the HAN-FUN network.
void periodic (uint32_t time)
Handle periodic processing.
Events
Protected Member Functions
HF::Transport::Link * link (uint16_t addr) const
Return the link that can be used to send a packet to the device with the given address.
bool is_local (Protocol::Packet &packet)
Check if an incoming packet is for the node.
Protected Member Functions inherited from HF::Devices::AbstractDevice
bool is_registered ()
Check if the device has a valid, i.e.
Protected Attributes
HF::Transport::Link * _link
Link to the be used when sending packets to the network.
CoreServices _unit0
Unit 0 implementation this device will use.
Protected Attributes inherited from HF::Devices::AbstractDevice
uint8_t next_reference
Last reference number used to send a packet.
IUnits _units
List containing pointers to the units present in the device.
Protocol::Filters::ResponseRequired response_filter
Support for generating missing responses for messages.
Detailed Description
template<typename CoreServices = DefaultUnit0>
class HF::Devices::Node::Abstract< CoreServices >
Template for declaring HAN-FUN node devices.
Definition at line 281 of file devices.h.
Member Function Documentation
template<typename CoreServices = DefaultUnit0> uint16_t HF::Devices::Node::Abstract< CoreServices >::address () const inline virtual
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
Returns
the device address on the HAN-FUN network, HF_BROADCAST_ADDR otherwise.
Implements HF::IDevice.
Definition at line 311 of file devices.h.
Referenced by HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >::is_local().
             {
                return unit0 ()->device_management ()->address ();
             }
template<typename CoreServices = DefaultUnit0> void HF::Devices::Node::Abstract< CoreServices >::connected (HF::Transport::Link * link) inline virtual
Callback to report that a new transport link was been created to a remote device.
This link can then be used by the local end-point to send messages to the remote end-point.
Parameters
[in] link pointer to the created link.
Implements HF::Transport::Endpoint.
Definition at line 289 of file devices.h.
             {
                _link = link;
             }
template<typename CoreServices = DefaultUnit0> void HF::Devices::Node::Abstract< CoreServices >::disconnected (HF::Transport::Link * link) inline virtual
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
At the time of this method call the link MUST not be used to send any further messages to the remote end-point.
Parameters
[in] link pointer to the link disconnected.
Implements HF::Transport::Endpoint.
Definition at line 294 of file devices.h.
             {
                if (_link == link)
                {
                   _link = nullptr;
                }
             }
template<typename CoreServices = DefaultUnit0> bool HF::Devices::Node::Abstract< CoreServices >::is_local (Protocol::Packet & packet) inline protected virtual
Check if an incoming packet is for the node.
Parameters
[in] packet reference to the incoming packet.
Return values
true if the packet if for the node;
false otherwise.
Reimplemented from HF::Devices::AbstractDevice.
Definition at line 348 of file devices.h.
             {
                return AbstractDevice::is_local (packet) ||
                       // If we are unregistered only allow packets to unit 0.
                       (address () == Protocol::BROADCAST_ADDR && packet.destination.unit == 0);
             }
template<typename CoreServices = DefaultUnit0> HF::Transport::Link* HF::Devices::Node::Abstract< CoreServices >::link (uint16_t addr) const inline protected virtual
Return the link that can be used to send a packet to the device with the given address.
Parameters
[in] addr the address of the device to send the packet to.
Returns
a pointer to the link that can be used to send the packet, nullptr otherwise;
Implements HF::Devices::AbstractDevice.
Definition at line 334 of file devices.h.
Referenced by HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >::connected().
             {
                UNUSED (addr);
                return _link;
             }
template<typename CoreServices = DefaultUnit0> void HF::Devices::Node::Abstract< CoreServices >::receive (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) inline virtual
Callback to deliver a packet received from the transport layer.
Parameters
[in] packet reference to the received packet.
[in] payload reference a ByteArray containing the received data.
[in] offset offset from where the received data starts on the payload byte array buffer.
Reimplemented from HF::Devices::AbstractDevice.
Reimplemented in Node.
Definition at line 302 of file devices.h.
             {
                AbstractDevice::receive (packet, payload, offset);
             }
template<typename CoreServices = DefaultUnit0> CoreServices* HF::Devices::Node::Abstract< CoreServices >::unit0 () const inline virtual
Return pointer to the unit 0 for this device.
Returns
pointer to the unit 0 for this device.
Implements HF::IDevice.
Definition at line 316 of file devices.h.
Referenced by HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >::address().
             {
                return const_cast <CoreServices *>(&_unit0);
             }
The documentation for this class was generated from the following file:
devices.h