HAN-FUN API: HF::Transport::AbstractLayer Class Reference
HF::Transport::AbstractLayer Class Reference
Devices » Transport Layer API
Parent class for all HF::Transport::Layer implementations.
#include <transport.h>
Public Member Functions
void initialize ()
Initialize the associated transport layer.
void destroy ()
Free the system resources associated with this transport layer.
void add (HF::Transport::Endpoint *ep)
Add an entry to the list of end-points connected to the transport layer.
void remove (HF::Transport::Endpoint *ep=nullptr)
Remove the entry in ep, from the list of end-points connected to the transport layer.
void receive (HF::Transport::Link *link, HF::Common::ByteArray &payload)
Receive the data in payload, coming in in the given link and deliver the decoded packet to all registered end-points.
const HF::UID::UID uid () const
Return the UID of the local device on this transport layer.
void uid (HF::UID::UID_T *_uid)
Set the UID to the given value.
void connected (HF::Transport::Link *link)
Call the connected method for all the registered end-points with the given link as argument.
void disconnected (HF::Transport::Link *link)
Call the disconnected method for all the registered end-points with the given link as argument.
Commands
Protected Attributes
Common::SimpleList< HF::Transport::Endpoint * > endpoints
List of registered end-points for this layer.
HF::UID::UID_T * _uid
UID associated with the local transport layer.
Detailed Description
Parent class for all HF::Transport::Layer implementations.
Definition at line 239 of file inc/hanfun/transport.h.
Member Function Documentation
add()
void HF::Transport::AbstractLayer::add (HF::Transport::Endpoint * ep) inline virtual
Add an entry to the list of end-points connected to the transport layer.
Parameters
[in] ep pointer to the end-point to add.
Implements HF::Transport::Layer.
Definition at line 268 of file inc/hanfun/transport.h.
References endpoints.
Referenced by HF::Devices::Node::Transport::add(), and HF::Devices::Concentrator::Transport::add().
          {
             assert(ep != nullptr);
             endpoints.push_front(ep);
          }
connected()
void HF::Transport::AbstractLayer::connected (HF::Transport::Link * link) inline
Call the connected method for all the registered end-points with the given link as argument.
Parameters
[in] link pointer to the link to call the connected method with.
Definition at line 342 of file inc/hanfun/transport.h.
References endpoints.
Referenced by HF::Devices::Node::Transport::add(), and HF::Devices::Concentrator::Transport::add().
          {
             assert(link != nullptr);
             /* *INDENT-OFF* */
             std::for_each (endpoints.begin (), endpoints.end (),
                   [link](HF::Transport::Endpoint *ep)
                   {
                      ep->connected (link);
                   });
             /* *INDENT-ON* */
          }
disconnected()
void HF::Transport::AbstractLayer::disconnected (HF::Transport::Link * link) inline
Call the disconnected method for all the registered end-points with the given link as argument.
Parameters
[in] link pointer to the link to call the disconnected method with.
Definition at line 361 of file inc/hanfun/transport.h.
References endpoints.
Referenced by HF::Devices::Node::Transport::remove().
          {
             assert(link != nullptr);
             /* *INDENT-OFF* */
             std::for_each (endpoints.begin (), endpoints.end (),
                   [link](HF::Transport::Endpoint *ep)
                   {
                      ep->disconnected (link);
                   });
             /* *INDENT-ON* */
          }
initialize()
void HF::Transport::AbstractLayer::initialize () inline virtual
Initialize the associated transport layer.
This method should initialize the transport layer using it's default values.
Implements HF::Transport::Layer.
Reimplemented in HF::Application::Transport.
Definition at line 259 of file inc/hanfun/transport.h.
 {}
receive()
void HF::Transport::AbstractLayer::receive (HF::Transport::Link * link, HF::Common::ByteArray & payload) inline
Receive the data in payload, coming in in the given link and deliver the decoded packet to all registered end-points.
Parameters
[in] link pointer to the link the incoming data was received.
[in] payload reference to the ByteArray containing the data received.
Definition at line 302 of file inc/hanfun/transport.h.
References endpoints, HF::Protocol::Packet::link, and HF::Protocol::Packet::unpack().
          {
             assert(link != nullptr);
             Protocol::Packet *packet = new Protocol::Packet();
             packet->link = link;
             uint16_t offset = packet->unpack(payload);
             /* *INDENT-OFF* */
             std::for_each (endpoints.begin (), endpoints.end (),
                   [&packet, &payload, &offset](HF::Transport::Endpoint *ep)
                   {
                      ep->receive (*packet, payload, offset);
                   });
             /* *INDENT-ON* */
             delete packet;
          }
remove()
void HF::Transport::AbstractLayer::remove (HF::Transport::Endpoint * ep = nullptr) inline virtual
Remove the entry in ep, from the list of end-points connected to the transport layer.
If ep is equal to nullptr then all end-points are removed.
Parameters
[in] ep pointer to the end-point entry to remove or nullptr to remove all entries.
Implements HF::Transport::Layer.
Definition at line 283 of file inc/hanfun/transport.h.
References endpoints.
          {
             if (ep != nullptr)
             {
                endpoints.remove(ep);
             }
             else
             {
                endpoints.clear();
             }
          }
uid() [1/2]
const HF::UID::UID HF::Transport::AbstractLayer::uid () const inline virtual
Return the UID of the local device on this transport layer.
For example on an ULE device this would return the IPUI of the device.
Returns
the UID of the local device on this transport layer.
Implements HF::Transport::Layer.
Definition at line 321 of file inc/hanfun/transport.h.
References _uid.
          {
             return HF::UID::UID(_uid);
          }
uid() [2/2]
void HF::Transport::AbstractLayer::uid (HF::UID::UID_T * _uid) inline
Set the UID to the given value.
Parameters
[in] _uid pointer to the UID to use.
Definition at line 331 of file inc/hanfun/transport.h.
References _uid.
          {
             this->_uid = _uid;
          }
The documentation for this class was generated from the following file:
inc/hanfun/transport.h