HAN-FUN API: HF::Devices::Node::Transport Class Reference
HF::Devices::Node::Transport Class Reference
Devices » Node device API.
Parent class for transport layer implementations on a HAN-FUN Node.
#include <devices.h>
Public Member Functions
void destroy ()
Free the system resources associated with this transport layer.
void add (HF::Transport::Endpoint *ep)
Register the given Endpoint to receive events.
void add (HF::Transport::Link *_link)
Add the given link to the list of known links and call the connected method for all registered end-points.
void remove (HF::Transport::Link *_link=nullptr)
Call the disconnected method for all registered end-points with the given _link and remove it from list of known links.
HF::Transport::Link * find (uint16_t address)
Find the link used to send messages to the HAN-FUN device with the given address.
Public Member Functions inherited from HF::Transport::AbstractLayer
void initialize ()
Initialize the associated transport layer.
void destroy ()
Free the system resources associated with this transport layer.
void add (HF::Transport::Endpoint *ep)
Add an entry to the list of end-points connected to the transport layer.
void remove (HF::Transport::Endpoint *ep=nullptr)
Remove the entry in ep, from the list of end-points connected to the transport layer.
void receive (HF::Transport::Link *link, HF::Common::ByteArray &payload)
Receive the data in payload, coming in in the given link and deliver the decoded packet to all registered end-points.
const HF::UID::UID uid () const
Return the UID of the local device on this transport layer.
void uid (HF::UID::UID_T *_uid)
Set the UID to the given value.
void connected (HF::Transport::Link *link)
Call the connected method for all the registered end-points with the given link as argument.
void disconnected (HF::Transport::Link *link)
Call the disconnected method for all the registered end-points with the given link as argument.
Commands
Protected Attributes
HF::Transport::Link * link
Pointer to the link used to send packets to the network.
Protected Attributes inherited from HF::Transport::AbstractLayer
Common::SimpleList< HF::Transport::Endpoint * > endpoints
List of registered end-points for this layer.
HF::UID::UID_T * _uid
UID associated with the local transport layer.
Detailed Description
Parent class for transport layer implementations on a HAN-FUN Node.
Definition at line 506 of file devices.h.
Member Function Documentation
add() [1/2]
void HF::Devices::Node::Transport::add (HF::Transport::Endpoint * ep) inline virtual
Register the given Endpoint to receive events.
This should be possible to register multiple end-points, to the transport layer.
Parameters
[in] ep pointer to the end-point to register in the transport layer.
Implements HF::Transport::Layer.
Definition at line 524 of file devices.h.
References HF::Transport::AbstractLayer::add(), HF::Transport::Endpoint::connected(), and link.
             {
                HF::Transport::AbstractLayer::add(ep);
                if (link != nullptr)
                {
                   ep->connected(link);
                }
             }
add() [2/2]
void HF::Devices::Node::Transport::add (HF::Transport::Link * _link) inline
Add the given link to the list of known links and call the connected method for all registered end-points.
Parameters
[in] _link pointer to the link to add.
Definition at line 540 of file devices.h.
References HF::Transport::AbstractLayer::connected().
             {
                assert(_link != nullptr);
                this->link = _link;
                HF::Transport::AbstractLayer::connected(_link);
             }
find()
HF::Transport::Link* HF::Devices::Node::Transport::find (uint16_t address) inline
Find the link used to send messages to the HAN-FUN device with the given address.
Note
in the nodes there is only one link as all messages are sent to the base.
Parameters
[in] address the HAN-FUN address to find the link for.
Returns
a pointer to the link for the given address or nullptr if no link exists for the given address.
Definition at line 579 of file devices.h.
References link, and UNUSED.
             {
                UNUSED(address);
                return link;
             }
remove()
void HF::Devices::Node::Transport::remove (HF::Transport::Link * _link = nullptr) inline
Call the disconnected method for all registered end-points with the given _link and remove it from list of known links.
If _link is nullptr, then remove all known links.
Parameters
[in] _link pointer to the link to remove.
Definition at line 556 of file devices.h.
References HF::Transport::AbstractLayer::disconnected(), and link.
             {
                if ((_link == nullptr && this->link != nullptr) || (_link == this->link))
                {
                   HF::Transport::AbstractLayer::disconnected(this->link);
                   delete this->link;
                   this->link = nullptr;
                }
             }
The documentation for this class was generated from the following file:
devices.h