HAN-FUN API: HF::Devices::Concentrator::AbstractBase Class Reference
HF::Devices::Concentrator::AbstractBase Class Reference abstract
Devices » Concentrator device API.
This is the parent class for the HAN-FUN Concentrator devices implementation.
#include <devices.h>
Public Member Functions
uint16_t address () const
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
void connected (HF::Transport::Link *link)
Callback to report that a new transport link was been created to a remote device.
void disconnected (HF::Transport::Link *link)
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
void receive (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Callback to deliver a packet received from the transport layer.
Public Member Functions inherited from HF::Devices::AbstractDevice
const IUnits & units () const
Return the list of units registered in this device.
void add (Units::IUnit *unit)
Add unit to devices unit lists.
void remove (Units::IUnit *unit)
Remove unit from device's unit list.
Units::IUnit * unit (uint8_t id) const
Return pointer to the unit with the given id.
void send (Protocol::Packet &packet)
Send given packet into the HAN-FUN network.
void periodic (uint32_t time)
Handle periodic processing.
Events
Protected Member Functions
HF::Transport::Link * link (uint16_t addr) const
Return the link that can be used to send a packet to the device with the given address.
virtual void route_packet (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Route the given packet to the corresponding device.
virtual Concentrator::IUnit0 * unit0 () const =0
Get the unit 0 used by this concentrator device.
Protected Member Functions inherited from HF::Devices::AbstractDevice
virtual bool is_local (Protocol::Packet &packet)
Check if the given packet is for this device.
bool is_registered ()
Check if the device has a valid, i.e.
Protected Attributes
Common::SimpleList< Transport::Link * > _links
List of links present in this concentrator.
Protected Attributes inherited from HF::Devices::AbstractDevice
uint8_t next_reference
Last reference number used to send a packet.
IUnits _units
List containing pointers to the units present in the device.
Protocol::Filters::ResponseRequired response_filter
Support for generating missing responses for messages.
Detailed Description
This is the parent class for the HAN-FUN Concentrator devices implementation.
Definition at line 590 of file devices.h.
Member Function Documentation
uint16_t HF::Devices::Concentrator::AbstractBase::address () const inline virtual
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
Returns
the device address on the HAN-FUN network, HF_BROADCAST_ADDR otherwise.
Implements HF::IDevice.
Definition at line 598 of file devices.h.
References HF::Transport::Endpoint::connected(), HF::Transport::Endpoint::disconnected(), HF::Devices::AbstractDevice::link(), and HF::Devices::AbstractDevice::receive().
             {
                return 0;
             }
void HF::Devices::Concentrator::AbstractBase::connected (HF::Transport::Link * link) virtual
Callback to report that a new transport link was been created to a remote device.
This link can then be used by the local end-point to send messages to the remote end-point.
Parameters
[in] link pointer to the created link.
Implements HF::Transport::Endpoint.
void HF::Devices::Concentrator::AbstractBase::disconnected (HF::Transport::Link * link) virtual
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
At the time of this method call the link MUST not be used to send any further messages to the remote end-point.
Parameters
[in] link pointer to the link disconnected.
Implements HF::Transport::Endpoint.
HF::Transport::Link* HF::Devices::Concentrator::AbstractBase::link (uint16_t addr) const protected virtual
Return the link that can be used to send a packet to the device with the given address.
Parameters
[in] addr the address of the device to send the packet to.
Returns
a pointer to the link that can be used to send the packet, nullptr otherwise;
Implements HF::Devices::AbstractDevice.
Referenced by COMMAND().
void HF::Devices::Concentrator::AbstractBase::receive (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) virtual
Callback to deliver a packet received from the transport layer.
Parameters
[in] packet reference to the received packet.
[in] payload reference a ByteArray containing the received data.
[in] offset offset from where the received data starts on the payload byte array buffer.
Reimplemented from HF::Devices::AbstractDevice.
Reimplemented in Base.
Referenced by Base::receive().
virtual void HF::Devices::Concentrator::AbstractBase::route_packet (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) protected virtual
Route the given packet to the corresponding device.
Parameters
[in] packet reference for the packet to route.
[in] payload reference to the ByteArray containing the packet payload.
[in] offset offset from where the packet data starts.
virtual Concentrator::IUnit0* HF::Devices::Concentrator::AbstractBase::unit0 () const protected pure virtual
Get the unit 0 used by this concentrator device.
Returns
pointer to the unit 0 used by this concentrator device.
Implements HF::IDevice.
Implemented in HF::Devices::Concentrator::Abstract< CoreServices >, HF::Devices::Concentrator::Abstract< Unit0 >, HF::Devices::Concentrator::Abstract< BaseUnit0 >, HF::Core::DeviceManagement::IServer, and HF::Core::BindManagement::IServer.
The documentation for this class was generated from the following file:
devices.h