HAN-FUN API: HF::Core::Scheduling::IClient Class Reference
HF::Core::Scheduling::IClient Class Reference abstract
Core Services & Interfaces » Scheduling Services (Common)
Scheduling Service : Client side implementation.
#include <scheduling.h>
Public Member Functions
Commands
void activate_scheduler (const Protocol::Address &addr, const Interface::UID itf_uid, bool enabled=true)
Send a HAN-FUN message containing a Scheduling::ACTIVATE_SCHEDULER_CMD, to the given network address.
void delete_event (const Protocol::Address &addr, const Interface::UID itf_uid, uint8_t id)
Send a HAN-FUN message containing a Scheduling::DELETE_CMD, to the given network address.
virtual void send (const Protocol::Address &addr, Protocol::Message &message)=0
Send message msg to the network address given by addr.
Public Member Functions inherited from HF::Interfaces::InterfaceRole< Interfaces::AbstractInterface, HF::Interface::CLIENT_ROLE >
HF::Interface::Role role () const
Return the Interface::Role this interface implements.
Public Member Functions inherited from HF::Interfaces::AbstractInterface
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void periodic (uint32_t time)
Handle periodic processing.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
virtual HF::Attributes::UIDS attributes (uint8_t pack_id=HF::Attributes::Pack::MANDATORY) const
Return a vector containing the attribute UIDs, for the given pack ID.
Public Member Functions inherited from HF::Interface
virtual uint16_t uid () const =0
This method returns the interface UID.
Additional Inherited Members
Public Types inherited from HF::Interface
enum Role { CLIENT_ROLE = 0, SERVER_ROLE = 1 }
Interface roles.
enum UID {
DEVICE_MANAGEMENT = 0x0001, BIND_MANAGEMENT = 0x0002, GROUP_MANAGEMENT = 0x0003, IDENTIFY = 0x0004,
DEVICE_INFORMATION = 0x0005, ATTRIBUTE_REPORTING = 0x0006, BATCH_PROGRAM_MANAGEMENT = 0x0007, EVENT_SCHEDULING = 0x0008,
WEEKLY_SCHEDULING = 0x0009, GROUP_TABLE = 0x000A, TAMPER_ALERT = 0x0101, TIME = 0x0102,
POWER = 0x0110, KEEP_ALIVE = 0x0115, RSSI = 0x0111, SUOTA = 0x0400,
ALERT = 0x0100, ON_OFF = 0x0200, LEVEL_CONTROL = 0x0201, COLOUR_CONTROL = 0x0202,
SIMPLE_KEYPAD = 0x0203, SIMPLE_POWER_METER = 0x0300, SIMPLE_TEMPERATURE = 0x0301, SIMPLE_HUMIDITY = 0x0302,
SIMPLE_THERMOSTAT = 0x0303, SIMPLE_BUTTON = 0x0304, SIMPLE_VISUAL_EFFECTS = 0x0305, SIMPLE_AIR_PRESSURE = 0x0306,
SIMPLE_LIGHT_SENSOR = 0x0307, RESERVED = 0x7F00, MAX_UID = 0x7FFE, ANY_UID = 0x7FFF
}
Interfaces Unique Identifiers (UID).
Static Public Attributes inherited from HF::Interface
static constexpr uint8_t MAX_CMD_ID = 0xFF
Maximum value for command IDs in interfaces.
Protected Member Functions inherited from HF::Interfaces::AbstractInterface
virtual void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify that an attribute value as changed.
Common::Result check (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if message has correct attributes to be processed by the interface.
Common::Result check_payload_size (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if payload data size if sufficient for processing the message.
virtual uint16_t payload_size (Protocol::Message &message) const
Return the minimal payload size that should be present for the given message.
virtual uint16_t payload_size (Protocol::Message::Interface &itf) const
Return the minimal payload size that a message should hold when addressed at the given interface.
template<typename _Message >
uint16_t payload_size_helper () const
Helper function template to retrieve minimum size required for serializing/deserializing the class given.
virtual Common::Result handle_command (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
virtual Common::Result handle_attribute (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
virtual bool check_uid (uint16_t uid) const =0
Check if the given UID matches the interface UID.
Detailed Description
Scheduling Service : Client side implementation.
This class provides the client side of the Scheduling interface.
Definition at line 876 of file scheduling.h.
Member Function Documentation
activate_scheduler()
void HF::Core::Scheduling::IClient::activate_scheduler (const Protocol::Address & addr, const Interface::UID itf_uid, bool enabled = true)
Send a HAN-FUN message containing a Scheduling::ACTIVATE_SCHEDULER_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] itf_uid interface UID to use in the message.
[in] enabled enable/disable scheduler.
Referenced by HF::Core::Scheduling::Event::IClient::activate_scheduler(), and HF::Core::Scheduling::Weekly::IClient::activate_scheduler().
delete_event()
void HF::Core::Scheduling::IClient::delete_event (const Protocol::Address & addr, const Interface::UID itf_uid, uint8_t id)
Send a HAN-FUN message containing a Scheduling::DELETE_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] itf_uid interface UID to use in the message.
[in] id entry ID to delete.
Referenced by HF::Core::Scheduling::Event::IClient::delete_event(), and HF::Core::Scheduling::Weekly::IClient::delete_event().
send()
virtual void HF::Core::Scheduling::IClient::send (const Protocol::Address & addr, Protocol::Message & message) pure virtual
Send message msg to the network address given by addr.
Parameters
[in] addr HF network address.
[in] message pointer to the message to be sent to the network.
Implements HF::Interfaces::AbstractInterface.
The documentation for this class was generated from the following file:
scheduling.h