HAN-FUN API: HF::Interfaces::Container< Base, Proxies > Class Template Reference
HF::Interfaces::Container< Base, Proxies > Class Template Reference
Interfaces » Common
Helper class to add optional interfaces to other classes.
#include <interface.h>
Public Member Functions
Container (Base &base)
Constructor.
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void attributes (HF::Attributes::List &attr_list, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
std::vector< Common::Interface > interfaces () const
Return the list of interfaces present in the wrapper.
template<uint8_t N>
const std::tuple_element< N, interfaces_t >::type::base * get () const
Retrieve a pointer to the N optional interface implemented by this unit.
Protected Member Functions
void for_each (std::function< void(HF::Interface &)> func) const
Call the given function for all the interfaces.
void for_each (std::function< void(HF::Interface &)> func)
Call the given function for all the interfaces.
template<uint8_t N, typename Head , typename... Tail>
HF::Interface * find (uint16_t itf_uid) const
Find the interface with the given UID.
template<uint8_t N>
HF::Interface * find (uint16_t itf_uid) const
Final template instantiation that finds the wrapped interface with the given UID.
template<uint8_t N, typename Head , typename... Tail>
void for_each (std::function< void(HF::Interface &)> func) const
Helper template function to implement the HF::Units::Unit::for_each functionality.
template<uint8_t N>
void for_each (std::function< void(HF::Interface &)> func) const
Helper template function to implement the HF::Units::Unit::for_each functionality.
template<uint8_t N, typename Head , typename... Tail>
void attributes_itf (HF::Attributes::List &attrs, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Helper function used to provide HF::Units::Unit::attributes functionality.
template<uint8_t N>
void attributes_itf (HF::Attributes::List &attrs, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Helper function used to provide HF::Units::Unit::attributes functionality.
Detailed Description
template<typename Base, typename... Proxies>
class HF::Interfaces::Container< Base, Proxies >
Helper class to add optional interfaces to other classes.
Definition at line 445 of file interface.h.
Constructor & Destructor Documentation
Container()
template<typename Base, typename... Proxies> HF::Interfaces::Container< Base, Proxies >::Container (Base & base) inline
Constructor.
Parameters
[in] base reference to the object containing the interfaces.
Definition at line 459 of file interface.h.
                               : _interfaces(Proxies(base) ...)
          {}
Member Function Documentation
attributes()
template<typename Base, typename... Proxies> void HF::Interfaces::Container< Base, Proxies >::attributes (HF::Attributes::List & attr_list, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS & uids) const inline
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
Parameters
[in] itf interface UID.
[in] pack_id attribute pack id.
[in] uids list of attributes UID's.
Returns
attribute list.
Parameters
[in,out] attr_list list to place the attributes UIDs.
Definition at line 483 of file interface.h.
Referenced by HF::Profiles::ProfileN< DIMMABLE_COLOUR_BULB, OnOffServer, ColourControlServer, LevelControlServer >::attributes().
          {
             attributes_itf<0, Proxies...>(attr_list, itf, pack_id, uids);
          }
attributes_itf() [1/2]
template<typename Base, typename... Proxies> template<uint8_t N, typename Head , typename... Tail> void HF::Interfaces::Container< Base, Proxies >::attributes_itf (HF::Attributes::List & attrs, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS & uids) const inline protected
Helper function used to provide HF::Units::Unit::attributes functionality.
Parameters
[out] attrs attribute list to append the attributes for the interface to.
[in] itf interface to get the attributes for.
[in] pack_id attributes pack id to use when retrieving the attributes.
[in] uids list of attribute uids to get attributes for if pack_id is HF::Attributes::Pack::DYNAMIC.
Template Parameters
N index in the wrapped interfaces tuple to check if UID matches.
Head class for the wrapped interface at the given index.
Tail the classes associated with the remaining wrapped interfaces.
Definition at line 653 of file interface.h.
Referenced by HF::Interfaces::Container< HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... >, Proxy< ITF, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... > >... >::attributes(), and HF::Interfaces::Container< HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... >, Proxy< ITF, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... > >... >::attributes_itf().
          {
             const auto &head = std::get<N>(this->_interfaces);
             if (head.uid() == itf.id)
             {
                auto result = HF::Attributes::get(head, pack_id, uids);
                attrs.merge(result);
             }
             else
             {
                attributes_itf<N + 1, Tail...>(attrs, itf, pack_id, uids);
             }
          }
attributes_itf() [2/2]
template<typename Base, typename... Proxies> template<uint8_t N> void HF::Interfaces::Container< Base, Proxies >::attributes_itf (HF::Attributes::List & attrs, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS & uids) const inline protected
Helper function used to provide HF::Units::Unit::attributes functionality.
Template expansion end.
Parameters
[out] attrs attribute list to append the attributes for the interface to.
[in] itf interface to get the attributes for.
[in] pack_id attributes pack id to use when retrieving the attributes.
[in] uids list of attribute uids to get attributes for if pack_id is HF::Attributes::Pack::DYNAMIC.
Template Parameters
N index in the wrapped interfaces tuple to check if UID matches.
Definition at line 683 of file interface.h.
          {
             UNUSED(attrs);
             UNUSED(itf);
             UNUSED(pack_id);
             UNUSED(uids);
          }
find() [1/2]
template<typename Base, typename... Proxies> template<uint8_t N, typename Head , typename... Tail> HF::Interface* HF::Interfaces::Container< Base, Proxies >::find (uint16_t itf_uid) const inline protected
Find the interface with the given UID.
Parameters
itf_uid the interface UID to search for in the wrapped interfaces.
Template Parameters
N index in the interfaces tuple to check if UID matches.
Head class for the interface at the given index.
Tail the classes associated with the remaining optional interfaces.
Returns
a pointer to the interface or nullptr if the interface is not present.
Definition at line 570 of file interface.h.
Referenced by HF::Interfaces::Container< HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... >, Proxy< ITF, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... > >... >::find(), and HF::Interfaces::Container< HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... >, Proxy< ITF, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... > >... >::handle().
          {
             static_assert(std::is_base_of<HF::Interface, Head>::value,
                           "Head must be of type HF::Interface");
             const Head &head = std::get<N>(_interfaces);
             if (head.uid() == itf_uid)
             {
                return const_cast<Head *>(&head);
             }
             else
             {
                return find<N + 1, Tail...>(itf_uid);
             }
          }
find() [2/2]
template<typename Base, typename... Proxies> template<uint8_t N> HF::Interface* HF::Interfaces::Container< Base, Proxies >::find (uint16_t itf_uid) const inline protected
Final template instantiation that finds the wrapped interface with the given UID.
Parameters
itf_uid the interface UID to search for in the wrapped interfaces.
Template Parameters
N index in the interfaces tuple to check if UID matches.
Returns
nullptr, i.e. the interface is not present.
Definition at line 598 of file interface.h.
          {
             UNUSED(itf_uid);
             return nullptr;
          }
for_each() [1/4]
template<typename Base, typename... Proxies> void HF::Interfaces::Container< Base, Proxies >::for_each (std::function< void(HF::Interface &)> func) const inline protected
Call the given function for all the interfaces.
Parameters
[in] func function to call with each of the optional implemented interfaces.
Definition at line 540 of file interface.h.
Referenced by HF::Interfaces::Container< HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... >, Proxy< ITF, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... > >... >::for_each(), and HF::Interfaces::Container< HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... >, Proxy< ITF, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... > >... >::interfaces().
          {
             for_each<0, Proxies...>(func);
          }
for_each() [2/4]
template<typename Base, typename... Proxies> void HF::Interfaces::Container< Base, Proxies >::for_each (std::function< void(HF::Interface &)> func) inline protected
Call the given function for all the interfaces.
Parameters
[in] func function to call with each of the optional implemented interfaces.
Definition at line 550 of file interface.h.
          {
             for_each<0, Proxies...>(func);
          }
for_each() [3/4]
template<typename Base, typename... Proxies> template<uint8_t N, typename Head , typename... Tail> void HF::Interfaces::Container< Base, Proxies >::for_each (std::function< void(HF::Interface &)> func) const inline protected
Helper template function to implement the HF::Units::Unit::for_each functionality.
Parameters
[in] func function to call with the reference for the wrapped interface at index N.
Template Parameters
N index in the wrapped interfaces tuple to check if UID matches.
Head class for the wrapped interface at the given index.
Tail the classes associated with the remaining wrapped interfaces.
Definition at line 615 of file interface.h.
          {
             const auto &head = std::get<N>(this->_interfaces);
             func(*(const_cast<HF::Interface *>(static_cast<const HF::Interface *>(&head))));
             for_each<N + 1, Tail...>(func);
          }
for_each() [4/4]
template<typename Base, typename... Proxies> template<uint8_t N> void HF::Interfaces::Container< Base, Proxies >::for_each (std::function< void(HF::Interface &)> func) const inline protected
Helper template function to implement the HF::Units::Unit::for_each functionality.
Parameters
[in] func function to call with the reference for the wrapped interface at index N.
Template Parameters
N index in the wrapped interfaces tuple to check if UID matches.
Definition at line 633 of file interface.h.
          {
             UNUSED(func);
          }
get()
template<typename Base, typename... Proxies> template<uint8_t N> const std::tuple_element<N, interfaces_t>::type::base* HF::Interfaces::Container< Base, Proxies >::get () const inline
Retrieve a pointer to the N optional interface implemented by this unit.
Template Parameters
N index of the interface to retrieve the pointer to.
Returns
a pointer to the optional implemented interface.
Definition at line 528 of file interface.h.
          {
             return &std::get<N>(_interfaces);
          }
handle()
template<typename Base, typename... Proxies> Common::Result HF::Interfaces::Container< Base, Proxies >::handle (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) inline
Handle incoming messages from the network.
Parameters
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
Definition at line 463 of file interface.h.
Referenced by HF::Profiles::ProfileN< DIMMABLE_COLOUR_BULB, OnOffServer, ColourControlServer, LevelControlServer >::handle().
          {
             HF::Interface *itf = find<0, Proxies...>(packet.message.itf.id);
             if (itf != nullptr)
             {
                return itf->handle(packet, payload, offset);
             }
             else
             {
                return Common::Result::FAIL_SUPPORT;
             }
          }
interfaces()
template<typename Base, typename... Proxies> std::vector<Common::Interface> HF::Interfaces::Container< Base, Proxies >::interfaces () const inline
Return the list of interfaces present in the wrapper.
Returns
a vector containing the UIDs for the interfaces wrapped by this class.
Definition at line 495 of file interface.h.
          {
             std::vector<Common::Interface> result;
             result.reserve(sizeof ... (Proxies));
             Common::Interface temp;
             /* *INDENT-OFF* */
             for_each ([&result, &temp](HF::Interface &itf)
             {
                 temp.id = itf.uid ();
                 temp.role = itf.role ();
                 result.push_back (temp);
             });
             /* *INDENT-ON* */
             return result;
          }
The documentation for this class was generated from the following file:
interface.h