HAN-FUN API: HF::Interfaces::Alert::Server Class Reference
HF::Interfaces::Alert::Server Class Reference
Interfaces » Alert Interface
Alert Interface : Server side implementation.
#include <alert.h>
Public Member Functions
Server ()
Constructor.
virtual ~Server ()
Destructor.
uint32_t state ()
Return the current state for all the alerts as a bitmask.
void set_state (uint32_t value)
Set the state bitmask to the given value.
bool state (uint8_t index, bool value)
Set the alert given by index to value.
bool state (uint8_t index)
Get the state of the alert given by index.
void clear ()
Clear all the alerts.
void enable (uint8_t index)
Enable alert at index.
void enableAll ()
Enable all alerts.
bool enabled (uint8_t index)
Check if alert at index is enabled.
uint32_t enabled ()
Return the bitmask of the enable state of the alerts.
void set_enabled (uint32_t value)
Set the bitmask of the enable state of the alerts.
void disable (uint8_t index)
Disable the alert at index.
bool disabled (uint8_t index)
Check if alert at index is disabled.
void disableAll ()
Disable all alerts.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
HF::Attributes::UIDS attributes (uint8_t pack_id=HF::Attributes::Pack::MANDATORY) const
Return a vector containing the attribute UIDs, for the given pack ID.
Commands
void status (Protocol::Address &addr, uint16_t unit_type)
Send a HAN-FUN message containing a Alert::STATUS_CMD, to the given network address.
void status (uint16_t unit_type)
Send a HAN-FUN message containing a Alert::STATUS_CMD, to the broadcast network address.
Public Member Functions inherited from HF::Interfaces::InterfaceRole< Alert::Base, HF::Interface::SERVER_ROLE >
HF::Interface::Role role () const
Return the Interface::Role this interface implements.
Public Member Functions inherited from HF::Interfaces::Interface< HF::Interface::ALERT >
uint16_t uid () const
This method returns the interface UID.
Public Member Functions inherited from HF::Interfaces::AbstractInterface
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void periodic (uint32_t time)
Handle periodic processing.
Protected Member Functions
Alert::Message * create_status (uint16_t unit_type)
Create a HAN-FUN message containing a Alert::STATUS_CMD, to be sent to the network.
Protected Member Functions inherited from HF::Interfaces::Alert::Base
uint16_t payload_size (Protocol::Message::Interface &itf) const
Return the minimal payload size that a message should hold when addressed at the given interface.
Protected Member Functions inherited from HF::Interfaces::AbstractInterface
virtual void send (const Protocol::Address &addr, Protocol::Message &message)=0
Send message msg to the network address given by addr.
virtual void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify that an attribute value as changed.
Common::Result check (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if message has correct attributes to be processed by the interface.
Common::Result check_payload_size (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if payload data size if sufficient for processing the message.
virtual uint16_t payload_size (Protocol::Message &message) const
Return the minimal payload size that should be present for the given message.
template<typename _Message >
uint16_t payload_size_helper () const
Helper function template to retrieve minimum size required for serializing/deserializing the class given.
virtual Common::Result handle_command (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
virtual Common::Result handle_attribute (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
Protected Attributes
uint32_t _state
Alert's state.
uint32_t _enabled
Alert's enable state.
Additional Inherited Members
Public Types inherited from HF::Interface
Static Public Attributes inherited from HF::Interface
static constexpr uint8_t MAX_CMD_ID = 0xFF
Maximum value for command IDs in interfaces.
Detailed Description
Alert Interface : Server side implementation.
This class provides the server side of the Alert interface.
Definition at line 176 of file alert.h.
Member Function Documentation
HF::Attributes::IAttribute* HF::Interfaces::Alert::Server::attribute (uint8_t uid) inline virtual
Return a pointer to the interface attribute with the given uid.
Parameters
[in] uid identifier of the attribute in the interface.
Returns
a pointer to the attribute if it exists, nullptr otherwise.
Reimplemented from HF::Interfaces::AbstractInterface.
Definition at line 303 of file alert.h.
References HF::Interfaces::create_attribute().
             {
                return Interfaces::create_attribute(this, uid);
             }
HF::Attributes::UIDS HF::Interfaces::Alert::Server::attributes (uint8_t pack_id = HF::Attributes::Pack::MANDATORY) const inline virtual
Return a vector containing the attribute UIDs, for the given pack ID.
Parameters
[in] pack_id the Attribute pack ID to get the attributes UIDs for.
Returns
vector containing the attributes UIDs.
Reimplemented from HF::Interfaces::AbstractInterface.
Definition at line 341 of file alert.h.
References HF::Interfaces::Alert::ENABLE_ATTR, HF::Interfaces::Alert::STATE_ATTR, and UNUSED.
Referenced by HF::Profiles::Detector< FLOOD_DETECTOR >::alert().
             {
                UNUSED(pack_id);
                /* *INDENT-OFF* */
                return HF::Attributes::UIDS ({ Alert::STATE_ATTR, Alert::ENABLE_ATTR });
                /* *INDENT-ON* */
             }
Alert::Message* HF::Interfaces::Alert::Server::create_status (uint16_t unit_type) protected
Create a HAN-FUN message containing a Alert::STATUS_CMD, to be sent to the network.
Parameters
unit_type unit type (i.e. profile) source for the alert status message.
Returns
a pointer to a Alert::Message, or nullptr if the message can't be allocated.
void HF::Interfaces::Alert::Server::disable (uint8_t index)
Disable the alert at index.
Parameters
[in] index index of the alert to disable : [0,31].
bool HF::Interfaces::Alert::Server::disabled (uint8_t index)
Check if alert at index is disabled.
Parameters
[in] index index of the alert to get the enable state : [0,31].
Return values
<tt>true</tt> if the alert at index is disabled
<tt>false</tt> otherwise
void HF::Interfaces::Alert::Server::enable (uint8_t index)
Enable alert at index.
Parameters
[in] index index to enable the alert : [0,31].
bool HF::Interfaces::Alert::Server::enabled (uint8_t index)
Check if alert at index is enabled.
Parameters
[in] index index of the alert to get the enabled state : [0,31].
Return values
<tt>true</tt> if the alert at index is enabled,
<tt>false</tt> otherwise.
uint32_t HF::Interfaces::Alert::Server::enabled ()
Return the bitmask of the enable state of the alerts.
Returns
the bitmask of the enable state of the alerts.
void HF::Interfaces::Alert::Server::set_enabled (uint32_t value)
Set the bitmask of the enable state of the alerts.
Parameters
[in] value the bitmask of the enable state of the alerts to set.
void HF::Interfaces::Alert::Server::set_state (uint32_t value)
Set the state bitmask to the given value.
Parameters
[in] value bitmask value to set the alert states.
uint32_t HF::Interfaces::Alert::Server::state ()
Return the current state for all the alerts as a bitmask.
Returns
the bitmask of the alert states.
Referenced by HF::Profiles::Detector< FLOOD_DETECTOR >::alert().
bool HF::Interfaces::Alert::Server::state (uint8_t index, bool value)
Set the alert given by index to value.
The alert entry MUST be enabled in order for the state to be set.
Parameters
[in] index index of the alert to set : [0,31].
[in] value state to set the index to.
Returns
true if the alert state was set or false otherwise.
bool HF::Interfaces::Alert::Server::state (uint8_t index)
Get the state of the alert given by index.
Note
This will return false if index is greater than 31.
Parameters
[in] index index of the alert to get the state from : [0,31].
Returns
true if the alert is active, false otherwise.
void HF::Interfaces::Alert::Server::status (Protocol::Address & addr, uint16_t unit_type)
Send a HAN-FUN message containing a Alert::STATUS_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] unit_type the unit type (
See also
hf_profile_uid_t) sending the message.
Referenced by HF::Profiles::Detector< FLOOD_DETECTOR >::alert().
void HF::Interfaces::Alert::Server::status (uint16_t unit_type) inline
Send a HAN-FUN message containing a Alert::STATUS_CMD, to the broadcast network address.
Parameters
[in] unit_type the unit type (
See also
HF::Profile::UID) sending the message.
Definition at line 332 of file alert.h.
             {
                Protocol::Address addr;
                status(addr, unit_type);
             }
The documentation for this class was generated from the following file:
alert.h