HAN-FUN API: HF::Units::AbstractUnit Class Reference
HF::Units::AbstractUnit Class Reference
Devices » Units API
This is the parent class for all HAN-FUN units.
#include <units.h>
Public Member Functions
IDevice & device () const
Reference to the device this unit belongs to.
void send (const Protocol::Address &addr, Protocol::Message &message, Transport::Link *link)
Create and send a new packet with the given message to the given address.
std::vector< Common::Interface > interfaces () const
Return a vector containing a list of extra interfaces, other than the interfaces specified by the profile the unit implements)
void periodic (uint32_t time)
Handle periodic processing.
Public Member Functions inherited from HF::Units::IUnit
virtual uint8_t id () const =0
Get the id number of this unit on the device.
virtual Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)=0
Handle incoming messages from the network.
Public Member Functions inherited from HF::Profiles::IProfile
virtual uint16_t uid () const =0
Return this profile HAN-FUN UID.
virtual HF::Attributes::List attributes (Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const =0
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
Protected Member Functions
AbstractUnit (IDevice &device)
Constructor.
void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify the attribute reporting service that the given attribute has changed value.
Protected Attributes
uint8_t _id
Unit ID used to identify a given unit in a given HAN-FUN device.
Detailed Description
This is the parent class for all HAN-FUN units.
Definition at line 95 of file units.h.
Constructor & Destructor Documentation
AbstractUnit()
HF::Units::AbstractUnit::AbstractUnit (IDevice & device) inline protected
Constructor.
Parameters
[in] device reference to the device that holds this unit.
Definition at line 135 of file units.h.
References HF::IDevice::add(), and device().
                                       : _device(device)
          {
             device.add(this);
          }
Member Function Documentation
device()
IDevice& HF::Units::AbstractUnit::device () const inline virtual
Reference to the device this unit belongs to.
Returns
reference to the device this unit belongs to
Implements HF::Units::IUnit.
Definition at line 107 of file units.h.
Referenced by AbstractUnit().
          {
             return _device;
          }
interfaces()
std::vector<Common::Interface> HF::Units::AbstractUnit::interfaces () const inline virtual
Return a vector containing a list of extra interfaces, other than the interfaces specified by the profile the unit implements)
Returns
vector containing the list of extra interfaces.
Implements HF::Units::IUnit.
Reimplemented in HF::Units::Unit< Profile, ITF >, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch >, HF::Units::Unit< HF::Profiles::GenericApplicationLogic, Alert, LevelControl, OnOff, SimplePowerMeter >, and HF::Units::Unit< HF::Profiles::SimpleLight >.
Definition at line 115 of file units.h.
          {
             return std::vector<Common::Interface>();
          }
notify()
void HF::Units::AbstractUnit::notify (const HF::Attributes::IAttribute & old_value, const HF::Attributes::IAttribute & new_value) const protected
Notify the attribute reporting service that the given attribute has changed value.
Parameters
[in] old_value reference to the previous value of the attribute.
[in] new_value reference to the current value of the attribute.
Referenced by HF::Units::Unit< HF::Profiles::SimpleLight >::notify().
periodic()
void HF::Units::AbstractUnit::periodic (uint32_t time) inline virtual
Handle periodic processing.
Parameters
[in] time current system clock value in seconds.
Implements HF::Units::IUnit.
Reimplemented in HF::Units::Unit< Profile, ITF >, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch >, HF::Units::Unit< HF::Profiles::GenericApplicationLogic, Alert, LevelControl, OnOff, SimplePowerMeter >, and HF::Units::Unit< HF::Profiles::SimpleLight >.
Definition at line 120 of file units.h.
References UNUSED.
          {
             UNUSED(time);
          }
send()
void HF::Units::AbstractUnit::send (const Protocol::Address & addr, Protocol::Message & message, Transport::Link * link) virtual
Create and send a new packet with the given message to the given address.
Parameters
[in] addr address to send the message to.
[in] message message to send.
[in] link preferred link to send the message on.
Implements HF::Units::IUnit.
Referenced by HF::Core::AbstractService::send(), and HF::Units::Unit< HF::Profiles::SimpleLight >::send().
The documentation for this class was generated from the following file:
units.h