HAN-FUN API: Protocol
Protocol
This module contains the classes that define and implement the Protocol API.
Modules
Attributes
This module contains the classes that define and implement the common API for handling attributes.
Filters
This module contains the filters used in the Protocol API implementation.
Data Structures
struct HF::Protocol::Message
Network Message.
struct HF::Protocol::Address
Network Address.
struct HF::Protocol::Packet
HAN-FUN Protocol Packet.
struct HF::Protocol::Response
Parent class for the response messages.
Functions
bool HF::Protocol::request (Message::Type type, bool response=false)
Check if message type is a request.
bool HF::Protocol::response (Message::Type type)
Check if message is a response.
bool HF::Protocol::matches (Message::Type lhs, Message::Type rhs)
Check if the given message types are the request and response for each other, for example, the Message::Type::COMMAND_RES matches both the Message::Type::COMMAND_REQ and Message::Type::COMMAND_RESP_REQ.
std::ostream & operator<< (std::ostream &stream, const HF::Protocol::Message::Type type)
Convert the given message type into a string and write it to the given stream.
std::ostream & operator<< (std::ostream &stream, const HF::Protocol::Message &message)
Convert the given message into a string and write it to the given stream.
std::ostream & operator<< (std::ostream &stream, const HF::Protocol::Address &address)
Convert the given address into a string and write it to the given stream.
std::ostream & operator<< (std::ostream &stream, const HF::Protocol::Packet &packet)
Convert the given packet into a string and write it to the given stream.
Variables
constexpr uint16_t HF::Protocol::BROADCAST_ADDR = 0x7FFF
HAN-FUN Broadcast - device address.
constexpr uint8_t HF::Protocol::BROADCAST_UNIT = 0xFF
HAN-FUN Broadcast - unit address.
constexpr uint16_t HF::Protocol::MAX_PAYLOAD = 0x01FF
HAN-FUN Network - Maximum application payload length.
Detailed Description
This module contains the classes that define and implement the Protocol API.
Function Documentation
bool HF::Protocol::matches (Message::Type lhs, Message::Type rhs)
Check if the given message types are the request and response for each other, for example, the Message::Type::COMMAND_RES matches both the Message::Type::COMMAND_REQ and Message::Type::COMMAND_RESP_REQ.
Parameters
[in] lhs message type to match.
[in] rhs message type to match.
Return values
true if the message types match.
false otherwise.
Referenced by HF::Protocol::Filters::ResponseRequired::size().
std::ostream& operator<< (std::ostream & stream, const HF::Protocol::Message::Type type)
Convert the given message type into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] type message type value to convert to a string.
Returns
stream
Referenced by HF::Protocol::Filters::ResponseRequired::size().
std::ostream& operator<< (std::ostream & stream, const HF::Protocol::Message & message)
Convert the given message into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] message message value to convert to a string.
Returns
stream
std::ostream& operator<< (std::ostream & stream, const HF::Protocol::Address & address)
Convert the given address into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] address HAN-FUN address to convert to a string.
Returns
stream
std::ostream& operator<< (std::ostream & stream, const HF::Protocol::Packet & packet)
Convert the given packet into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] packet HAN-FUN packet to convert to a string.
Returns
stream
bool HF::Protocol::request (Message::Type type, bool response = false)
Check if message type is a request.
If response is false then return true for all requests, otherwise only for those that require a response.
Parameters
[in] type message type to check if it is a request.
[in] response false check for all request types, otherwise only those that require a response.
Return values
true if the message is a request.
false otherwise.
Referenced by HF::Core::BindManagement::Client::end_session(), HF::Core::DeviceManagement::Client::end_session(), HF::Protocol::Filters::ResponseRequired::size(), HF::Core::BindManagement::Client::start_session(), and HF::Core::DeviceManagement::Client::start_session().
bool HF::Protocol::response (Message::Type type)
Check if message is a response.
Parameters
[in] type message type to check if it is a response.
Return values
true if the message is a response.
false otherwise.
Referenced by HF::Core::AttributeReporting::IServer::attributes(), HF::Core::BindManagement::Client::end_session(), HF::Core::DeviceManagement::Client::end_session(), HF::Core::SessionManagement::Server< Entries >::entries(), HF::Core::SessionManagement::Client< Device >::entries(), BindManagement::Server::restore(), HF::Protocol::Filters::ResponseRequired::size(), and HF::Core::SUOTA::Client::upgrade_complete().