HAN-FUN API: Session Management
Session Management
Core Services & Interfaces
This module contains the classes that implement the Session Management functionality.
Data Structures
struct HF::Core::SessionManagement::StartResponse
Start Read Session Command Message.
struct HF::Core::SessionManagement::GetEntriesMessage
Get Entries Command Message.
struct HF::Core::SessionManagement::IServer
Session Management API : Server side.
struct HF::Core::SessionManagement::AbstractServer::Session
Session database entry.
class HF::Core::SessionManagement::AbstractServer
Parent class for session management functionality - Server side.
class HF::Core::SessionManagement::EntriesWrapper< Parent >
Wrapper over persistent storage APIs to invalidate sessions on save and destroy.
struct HF::Core::SessionManagement::Server< _Entries >
Helper template to inject session management functionality into services requiring it - Server side.
class HF::Core::SessionManagement::AbstractClient
Parent class for session management functionality - Client side.
struct HF::Core::SessionManagement::Client< _Entry >
Helper template to inject session management functionality into services requiring it - Client side.
Enumerations
enum HF::Core::SessionManagement::CMD { HF::Core::SessionManagement::START, HF::Core::SessionManagement::GET, HF::Core::SessionManagement::END }
Available commands for session management.
Functions
HF::Core::SessionManagement::StartResponse::StartResponse (uint16_t count=0)
Constructor.
uint16_t HF::Core::SessionManagement::GetEntriesMessage::size () const
Number bytes needed to serialize the message.
uint16_t HF::Core::SessionManagement::GetEntriesMessage::pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t HF::Core::SessionManagement::GetEntriesMessage::unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
virtual void HF::Core::SessionManagement::IServer::start_session (uint16_t address)=0
Start a session for the device with the given address.
virtual void HF::Core::SessionManagement::IServer::end_session (uint16_t address)=0
Terminate the session associated with the device with the given address.
virtual bool HF::Core::SessionManagement::IServer::exists (uint16_t address) const =0
Check if a session for the device with the given address exists.
virtual bool HF::Core::SessionManagement::IServer::is_valid (uint16_t address) const =0
Check if the session for the device with the given address is valid, i.e., the underling entries have not been modified since the start of the session.
HF::Core::SessionManagement::AbstractServer::Session::Session (uint16_t _address=HF::Protocol::BROADCAST_ADDR, bool _valid=false)
Constructor.
HF::Core::SessionManagement::AbstractServer::AbstractServer ()
Constructor.
void HF::Core::SessionManagement::AbstractServer::start_session (uint16_t address)
Start a session for the device with the given address.
void HF::Core::SessionManagement::AbstractServer::end_session (uint16_t address)
Terminate the session associated with the device with the given address.
bool HF::Core::SessionManagement::AbstractServer::exists (uint16_t address) const
Check if a session for the device with the given address exists.
bool HF::Core::SessionManagement::AbstractServer::is_valid (uint16_t address) const
Check if the session for the device with the given address is valid, i.e., the underling entries have not been modified since the start of the session.
void HF::Core::SessionManagement::AbstractServer::invalidate ()
Invalidate all sessions.
Common::Result HF::Core::SessionManagement::AbstractServer::handle_command (CMD cmd, Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset=0)
Handle command request/response messages.
iterator HF::Core::SessionManagement::AbstractServer::find (uint16_t address)
Find the session associated with the given device address.
const_iterator HF::Core::SessionManagement::AbstractServer::find (uint16_t address) const
Find the session associated with the given device address.
uint16_t HF::Core::SessionManagement::AbstractServer::payload_size (CMD cmd) const
Get the minimum number of bytes necessary to pack/unpack a message of the given command.
Common::Result HF::Core::SessionManagement::AbstractServer::check_offset (uint16_t offset, uint8_t &count, uint16_t size) const
Check if the given offset is valid and adjust the count value if necessary.
virtual void HF::Core::SessionManagement::AbstractServer::send (const Protocol::Address &addr, Protocol::Message &message)=0
Send message msg to the network address given by addr.
virtual uint16_t HF::Core::SessionManagement::AbstractServer::entries_size () const =0
Get the number of entries present in the container.
virtual Common::Result HF::Core::SessionManagement::AbstractServer::entries (uint16_t offset, uint8_t count, Common::ByteArray &payload)=0
Create a GetEntriesResponse message message with, count entries starting from the given offset and serialize the created message into the given byte array in payload.
Common::Result HF::Core::SessionManagement::AbstractServer::check_session (uint16_t address, Common::ByteArray &payload) const
Check if a session for the given device address exists and if it is valid.
HF::Core::SessionManagement::EntriesWrapper< Parent >::EntriesWrapper (AbstractServer &_manager)
Constructor.
HF::Core::SessionManagement::EntriesWrapper< Parent >::EntriesWrapper (const EntriesWrapper &other, AbstractServer &_manager)
Constructor.
Common::Result HF::Core::SessionManagement::EntriesWrapper< Parent >::save (const value_type &entry)
Store the given entry to persistent storage.
Common::Result HF::Core::SessionManagement::EntriesWrapper< Parent >::destroy (const value_type &entry)
Destroy the given entry in the persistent storage.
Container & HF::Core::SessionManagement::Server< _Entries >::entries () const
Return the container for the service entries.
HF::Core::SessionManagement::Server< _Entries >::Server (const Server &other)
Copy-Constructor.
uint16_t HF::Core::SessionManagement::Server< _Entries >::entries_size () const
Get the number of entries present in the container.
Common::Result HF::Core::SessionManagement::Server< _Entries >::entries (uint16_t offset, uint8_t count, Common::ByteArray &payload)
Create a GetEntriesResponse message message with, count entries starting from the given offset and serialize the created message into the given byte array in payload.
Common::Result HF::Core::SessionManagement::AbstractClient::handle_command (CMD cmd, Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset=0)
Handle command request/response messages.
uint16_t HF::Core::SessionManagement::AbstractClient::payload_size (CMD cmd) const
Get the minimum number of bytes necessary to pack/unpack a message of the given command.
template<uint8_t _role, uint16_t _uid, uint8_t _member>
void HF::Core::SessionManagement::AbstractClient::get_entries (uint16_t offset, uint8_t count=0) const
Helper method to send a message to read, count entries starting at offset from the server.
template<uint8_t _role, uint16_t _uid, uint8_t _member>
void HF::Core::SessionManagement::AbstractClient::request () const
Helper method to create a session management request.
virtual void HF::Core::SessionManagement::AbstractClient::send (const Protocol::Address &addr, Protocol::Message &message)=0
Send message msg to the network address given by addr.
Variables
uint16_t HF::Core::SessionManagement::StartResponse::count
Number of device entries.
static constexpr uint16_t HF::Core::SessionManagement::StartResponse::min_size = Protocol::Response::min_size + sizeof(uint16_t)
Minimum pack/unpack required data size.
uint16_t HF::Core::SessionManagement::GetEntriesMessage::offset
Start index for the first entry to be provided.
uint8_t HF::Core::SessionManagement::GetEntriesMessage::count
Number of entries to be sent in the response.
static constexpr uint16_t HF::Core::SessionManagement::GetEntriesMessage::min_size = sizeof(offset) + sizeof(count)
Minimum pack/unpack required data size.
static constexpr uint16_t HF::Core::SessionManagement::GetEntriesResponse< _Entry >::min_size
Minimum pack/unpack required data size.
static constexpr uint16_t HF::Core::SessionManagement::GetEntriesResponse< void >::min_size
Minimum pack/unpack required data size.
uint16_t HF::Core::SessionManagement::AbstractServer::Session::address
Device address for session.
bool HF::Core::SessionManagement::AbstractServer::Session::valid
Indicate if the session is still valid.
Container HF::Core::SessionManagement::AbstractServer::sessions
Session's database.
Events
virtual void HF::Core::SessionManagement::Client< _Entry >::entries (const GetEntriesResponse< _Entry > &response)
This event is called when a response to a get entries is received.
Detailed Description
This module contains the classes that implement the Session Management functionality.
Enumeration Type Documentation
CMD
enum HF::Core::SessionManagement::CMD
Available commands for session management.
Enumerator
START
Start a new session for a device.
GET
Retrieve information.
END
End the session for device.
Definition at line 42 of file session_management.h.
          {
             START,
             GET,
             END,
          } CMD;
Function Documentation
EntriesWrapper() [1/2]
template<typename Parent> HF::Core::SessionManagement::EntriesWrapper< Parent >::EntriesWrapper (AbstractServer & _manager) inline
Constructor.
Parameters
[in] _manager session manager the entries are associated to.
Definition at line 557 of file session_management.h.
                                                     : Parent(),
                manager(_manager)
             {}
EntriesWrapper() [2/2]
template<typename Parent> HF::Core::SessionManagement::EntriesWrapper< Parent >::EntriesWrapper (const EntriesWrapper< Parent > & other, AbstractServer & _manager) inline
Constructor.
Parameters
[in] other entries container to wrap.
[in] _manager session manager the entries are associated to.
Definition at line 567 of file session_management.h.
                                                                                  :
                Parent(other), manager(_manager)
             {}
Server()
template<typename _Entries> HF::Core::SessionManagement::Server< _Entries >::Server (const Server< _Entries > & other) inline protected
Copy-Constructor.
Make sure that the entries are copied maintaining this object as the session manager.
Parameters
[in] other reference to the object to copy from.
Definition at line 627 of file session_management.h.
                                        :
                AbstractServer(other), _entries(other._entries, *this)
             {}
Session()
HF::Core::SessionManagement::AbstractServer::Session::Session (uint16_t _address = HF::Protocol::BROADCAST_ADDR, bool _valid = false) inline
Constructor.
Parameters
[in] _address device address this session belongs to.
[in] _valid true if the session is valid, false otherwise.
Definition at line 330 of file session_management.h.
                                                                                          :
                   address(_address), valid(_valid)
                {}
StartResponse()
HF::Core::SessionManagement::StartResponse::StartResponse (uint16_t count = 0) inline
Constructor.
Parameters
[in] count number of entries available.
Definition at line 65 of file session_management.h.
                                              :
                count(count)
             {}
check_offset()
Common::Result HF::Core::SessionManagement::AbstractServer::check_offset (uint16_t offset, uint8_t & count, uint16_t size) const protected
Check if the given offset is valid and adjust the count value if necessary.
Parameters
[in] offset offset to start reading the entries from.
[in,out] count number of entries to read.
[in] size number of entries present in the underling container.
Return values
HF::Common::Result::OK if entries can be read.
HF::Common::Result::FAIL_ARG if the offset value is invalid.
Referenced by HF::Core::SessionManagement::Server< Entries >::entries().
check_session()
Common::Result HF::Core::SessionManagement::AbstractServer::check_session (uint16_t address, Common::ByteArray & payload) const protected
Check if a session for the given device address exists and if it is valid.
In case a session does not exist or is invalid, place an GetEntriesEmptyResponse into the byte array given by payload to be sent to the remote device.
Parameters
[in] address device address to check the session for.
[out] payload the byte array to place the response in case of error.
Return values
Common::Result::FAIL_READ_SESSION if the session does not exist;
Common::Result::FAIL_FAIL_MODIFIED if the session is not valid;
Common::Result::OK a session exists an is valid.
destroy()
template<typename Parent> Common::Result HF::Core::SessionManagement::EntriesWrapper< Parent >::destroy (const value_type & entry) inline
Destroy the given entry in the persistent storage.
Parameters
[in] entry reference to the entry to erase.
Return values
Common::Result::OK,if the entry was destroyed.
Common::Result::FAIL_ARG otherwise.
Definition at line 584 of file session_management.h.
             {
                auto res = Parent::destroy(entry);
                manager.invalidate();
                return res;
             }
end_session() [1/2]
virtual void HF::Core::SessionManagement::IServer::end_session (uint16_t address) pure virtual
Terminate the session associated with the device with the given address.
Parameters
[in] address device address to end the session for.
Implemented in HF::Core::SessionManagement::AbstractServer.
end_session() [2/2]
void HF::Core::SessionManagement::AbstractServer::end_session (uint16_t address) inline virtual
Terminate the session associated with the device with the given address.
Parameters
[in] address device address to end the session for.
Implements HF::Core::SessionManagement::IServer.
Definition at line 369 of file session_management.h.
References HF::Core::SessionManagement::AbstractServer::find(), and HF::Core::SessionManagement::AbstractServer::sessions.
             {
                auto it = find(address);
                if (it != sessions.end())
                {
                   sessions.erase(it);
                }
             }
entries() [1/4]
virtual Common::Result HF::Core::SessionManagement::AbstractServer::entries (uint16_t offset, uint8_t count, Common::ByteArray & payload) protected pure virtual
Create a GetEntriesResponse message message with, count entries starting from the given offset and serialize the created message into the given byte array in payload.
Remarks
if offset + count > [number of entries], the message will truncated to the available entries starting from the given offset.
Parameters
[in] offset the offset to start reading the entries.
[in] count number of entries to read.
[out] payload byte array to serialize the entries to.
Return values
Common::Result::OK message created successfully;
Common::Result::FAIL_ARG if offset is bigger than the number of entries.
Implemented in HF::Core::SessionManagement::Server< _Entries >, and HF::Core::SessionManagement::Server< Entries >.
entries() [2/4]
template<typename _Entries> Container& HF::Core::SessionManagement::Server< _Entries >::entries () const inline
Return the container for the service entries.
Returns
reference to the object containing the wrapped service entries.
Definition at line 607 of file session_management.h.
Referenced by HF::Core::BindManagement::Server< Entries >::entries(), and HF::Core::DeviceManagement::Server< Entries >::entries().
             {
                return const_cast<Container &>(_entries);
             }
entries() [3/4]
template<typename _Entries> Common::Result HF::Core::SessionManagement::Server< _Entries >::entries (uint16_t offset, uint8_t count, Common::ByteArray & payload) inline protected virtual
Create a GetEntriesResponse message message with, count entries starting from the given offset and serialize the created message into the given byte array in payload.
Remarks
if offset + count > [number of entries], the message will truncated to the available entries starting from the given offset.
Parameters
[in] offset the offset to start reading the entries.
[in] count number of entries to read.
[out] payload byte array to serialize the entries to.
Return values
Common::Result::OK message created successfully;
Common::Result::FAIL_ARG if offset is bigger than the number of entries.
Implements HF::Core::SessionManagement::AbstractServer.
Definition at line 642 of file session_management.h.
             {
                GetEntriesResponse<value_type> response;
                response.code = check_offset(offset, count, entries_size());
                if (response.code == Common::Result::OK)
                {
                   auto start = _entries.begin();
                   std::advance(start, offset);
                   auto end = start;
                   std::advance(end, count);
                   std::copy(start, end, std::back_inserter(response.entries));
                }
                payload = Common::ByteArray(response.size());
                response.pack(payload);
                return response.code;
             }
entries() [4/4]
template<typename _Entry> virtual void HF::Core::SessionManagement::Client< _Entry >::entries (const GetEntriesResponse< _Entry > & response) inline virtual
This event is called when a response to a get entries is received.
Parameters
[in] response the response received.
Definition at line 837 of file session_management.h.
             {
                UNUSED(response);
             }
entries_size() [1/2]
virtual uint16_t HF::Core::SessionManagement::AbstractServer::entries_size () const protected pure virtual
Get the number of entries present in the container.
Returns
number of entries in the wrapped service.
Implemented in HF::Core::SessionManagement::Server< _Entries >, and HF::Core::SessionManagement::Server< Entries >.
entries_size() [2/2]
template<typename _Entries> uint16_t HF::Core::SessionManagement::Server< _Entries >::entries_size () const inline protected virtual
Get the number of entries present in the container.
Returns
number of entries in the wrapped service.
Implements HF::Core::SessionManagement::AbstractServer.
Definition at line 635 of file session_management.h.
Referenced by HF::Core::SessionManagement::Server< Entries >::entries().
             {
                return static_cast<uint16_t>(_entries.size());
             }
exists() [1/2]
virtual bool HF::Core::SessionManagement::IServer::exists (uint16_t address) const pure virtual
Check if a session for the device with the given address exists.
Parameters
[in] address device address to check is a session exists.
Return values
true if a session exists,
false otherwise.
Implemented in HF::Core::SessionManagement::AbstractServer.
exists() [2/2]
bool HF::Core::SessionManagement::AbstractServer::exists (uint16_t address) const inline virtual
Check if a session for the device with the given address exists.
Parameters
[in] address device address to check is a session exists.
Return values
true if a session exists,
false otherwise.
Implements HF::Core::SessionManagement::IServer.
Definition at line 379 of file session_management.h.
References HF::Core::SessionManagement::AbstractServer::find(), and HF::Core::SessionManagement::AbstractServer::sessions.
             {
                return find(address) != sessions.end();
             }
find() [1/2]
iterator HF::Core::SessionManagement::AbstractServer::find (uint16_t address) inline protected
Find the session associated with the given device address.
Parameters
[in] address device address to search a session for.
Returns
an iterator to the session found or Container::end() otherwise.
Definition at line 438 of file session_management.h.
References HF::Core::SessionManagement::AbstractServer::sessions.
Referenced by HF::Core::SessionManagement::AbstractServer::end_session(), HF::Core::SessionManagement::AbstractServer::exists(), HF::Core::SessionManagement::AbstractServer::is_valid(), and HF::Core::SessionManagement::AbstractServer::start_session().
             {
                /* *INDENT-OFF* */
                return std::find_if (sessions.begin (), sessions.end (),
                                     [address](const Session &session)
                {
                   return address == session.address;
                });
                /* *INDENT-ON* */
             }
find() [2/2]
const_iterator HF::Core::SessionManagement::AbstractServer::find (uint16_t address) const inline protected
Find the session associated with the given device address.
Parameters
[in] address device address to search a session for.
Returns
a constant iterator to the session found or Container::end() otherwise.
Definition at line 456 of file session_management.h.
References HF::Core::SessionManagement::AbstractServer::sessions.
             {
                /* *INDENT-OFF* */
                return std::find_if (sessions.cbegin (), sessions.cend (),
                                     [address](const Session &session)
                {
                   return address == session.address;
                });
                /* *INDENT-ON* */
             }
get_entries()
template<uint8_t _role, uint16_t _uid, uint8_t _member> void HF::Core::SessionManagement::AbstractClient::get_entries (uint16_t offset, uint8_t count = 0) const inline protected
Helper method to send a message to read, count entries starting at offset from the server.
Parameters
[in] offset index to start reading the entries from.
[in] count number of entries to read.
Definition at line 776 of file session_management.h.
References HF::Common::Interface::id, HF::Protocol::Message::itf, HF::Protocol::Message::Interface::member, HF::Core::SessionManagement::GetEntriesMessage::pack(), HF::Protocol::Message::payload, HF::Common::Interface::role, HF::Core::SessionManagement::AbstractClient::send(), and HF::Core::SessionManagement::GetEntriesMessage::size().
             {
                SessionManagement::GetEntriesMessage msg(offset, count);
                Protocol::Address addr(0, 0);
                Protocol::Message message;
                message.itf.role   = _role;
                message.itf.id     = _uid;
                message.itf.member = _member;
                message.payload    = Common::ByteArray(msg.size());
                msg.pack(message.payload);
                const_cast<AbstractClient *>(this)->send(addr, message);
             }
handle_command() [1/2]
Common::Result HF::Core::SessionManagement::AbstractServer::handle_command (CMD cmd, Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset = 0) protected
Handle command request/response messages.
Protocol::Message:Type::COMMAND_REQ;
Protocol::Message:Type::COMMAND_RESP_REQ;
Protocol::Message:Type::COMMAND_RES;
Parameters
[in] cmd the session operation to process.
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
handle_command() [2/2]
Common::Result HF::Core::SessionManagement::AbstractClient::handle_command (CMD cmd, Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset = 0) protected
Handle command request/response messages.
Protocol::Message:Type::COMMAND_REQ;
Protocol::Message:Type::COMMAND_RESP_REQ;
Protocol::Message:Type::COMMAND_RES;
Parameters
[in] cmd the session operation to process.
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
is_valid() [1/2]
virtual bool HF::Core::SessionManagement::IServer::is_valid (uint16_t address) const pure virtual
Check if the session for the device with the given address is valid, i.e., the underling entries have not been modified since the start of the session.
Parameters
[in] address device address to check is the session is valid.
Return values
true if the session exists and is valid,
false otherwise.
Implemented in HF::Core::SessionManagement::AbstractServer.
is_valid() [2/2]
bool HF::Core::SessionManagement::AbstractServer::is_valid (uint16_t address) const inline virtual
Check if the session for the device with the given address is valid, i.e., the underling entries have not been modified since the start of the session.
Parameters
[in] address device address to check is the session is valid.
Return values
true if the session exists and is valid,
false otherwise.
Implements HF::Core::SessionManagement::IServer.
Definition at line 384 of file session_management.h.
References HF::Core::SessionManagement::AbstractServer::find(), and HF::Core::SessionManagement::AbstractServer::sessions.
             {
                auto it = find(address);
                if (it != sessions.end())
                {
                   return it->valid;
                }
                return false;
             }
pack()
uint16_t HF::Core::SessionManagement::GetEntriesMessage::pack (Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 121 of file session_management.h.
References HF_SERIALIZABLE_CHECK, HF::Core::SessionManagement::GetEntriesMessage::min_size, HF::Core::SessionManagement::GetEntriesMessage::offset, and HF::Common::ByteArray::write().
Referenced by HF::Core::SessionManagement::AbstractClient::get_entries().
             {
                HF_SERIALIZABLE_CHECK(array, offset, min_size);
                offset += array.write(offset, this->offset);
                array.write(offset, this->count);
                return min_size;
             }
payload_size() [1/2]
uint16_t HF::Core::SessionManagement::AbstractServer::payload_size (CMD cmd) const protected
Get the minimum number of bytes necessary to pack/unpack a message of the given command.
Parameters
[in] cmd the command to get the number of bytes for.
Returns
number of bytes required.
payload_size() [2/2]
uint16_t HF::Core::SessionManagement::AbstractClient::payload_size (CMD cmd) const protected
Get the minimum number of bytes necessary to pack/unpack a message of the given command.
Parameters
[in] cmd the command to get the number of bytes for.
Returns
number of bytes required.
request()
template<uint8_t _role, uint16_t _uid, uint8_t _member> void HF::Core::SessionManagement::AbstractClient::request () const inline protected
Helper method to create a session management request.
Template Parameters
_role role to use in the created message.
_uid interface UID to use in the message.
_member interface member ID to use.
Definition at line 803 of file session_management.h.
References HF::Common::Interface::id, HF::Protocol::Message::itf, HF::Protocol::Message::Interface::member, HF::Common::Interface::role, and HF::Core::SessionManagement::AbstractClient::send().
Referenced by HF::Core::BindManagement::Client::end_session(), HF::Core::DeviceManagement::Client::end_session(), HF::Core::BindManagement::Client::start_session(), and HF::Core::DeviceManagement::Client::start_session().
             {
                Protocol::Address addr(0, 0);
                Protocol::Message message;
                message.itf.role   = _role;
                message.itf.id     = _uid;
                message.itf.member = _member;
                const_cast<AbstractClient *>(this)->send(addr, message);
             }
save()
template<typename Parent> Common::Result HF::Core::SessionManagement::EntriesWrapper< Parent >::save (const value_type & entry) inline
Store the given entry to persistent storage.
Parameters
[in] entry the entry to save to storage.
Return values
Common::Result::OK if the entry was saved,
Common::Result::FAIL_UNKNOWN otherwise.
Definition at line 575 of file session_management.h.
             {
                auto res = Parent::save(entry);
                manager.invalidate();
                return res;
             }
send() [1/2]
virtual void HF::Core::SessionManagement::AbstractServer::send (const Protocol::Address & addr, Protocol::Message & message) protected pure virtual
Send message msg to the network address given by addr.
Parameters
[in] addr HF network address.
[in] message pointer to the message to be sent to the network.
Implemented in HF::Core::DeviceManagement::Server< _Entries >, HF::Core::DeviceManagement::Server< Entries >, HF::Core::BindManagement::Server< _Entries >, and HF::Core::BindManagement::Server< Entries >.
send() [2/2]
virtual void HF::Core::SessionManagement::AbstractClient::send (const Protocol::Address & addr, Protocol::Message & message) protected pure virtual
Send message msg to the network address given by addr.
Parameters
[in] addr HF network address.
[in] message pointer to the message to be sent to the network.
Implemented in HF::Core::DeviceManagement::Client, and HF::Core::BindManagement::Client.
Referenced by HF::Core::SessionManagement::AbstractClient::get_entries(), and HF::Core::SessionManagement::AbstractClient::request().
size()
uint16_t HF::Core::SessionManagement::GetEntriesMessage::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 115 of file session_management.h.
References HF::Core::SessionManagement::GetEntriesMessage::min_size.
Referenced by HF::Core::SessionManagement::AbstractClient::get_entries().
             {
                return min_size;
             }
start_session() [1/2]
virtual void HF::Core::SessionManagement::IServer::start_session (uint16_t address) pure virtual
Start a session for the device with the given address.
Only one session is associated with any given device at any time.
Parameters
[in] address device address to start the session for.
Implemented in HF::Core::SessionManagement::AbstractServer.
start_session() [2/2]
void HF::Core::SessionManagement::AbstractServer::start_session (uint16_t address) inline virtual
Start a session for the device with the given address.
Only one session is associated with any given device at any time.
Parameters
[in] address device address to start the session for.
Implements HF::Core::SessionManagement::IServer.
Definition at line 355 of file session_management.h.
References HF::Core::SessionManagement::AbstractServer::find(), and HF::Core::SessionManagement::AbstractServer::sessions.
             {
                auto it = find(address);
                if (it == sessions.end())   // Session does not exist.
                {
                   sessions.push_back(Session(address, true));
                }
                else  // Session already exists. Update state.
                {
                   it->valid = true;
                }
             }
unpack()
uint16_t HF::Core::SessionManagement::GetEntriesMessage::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 132 of file session_management.h.
References HF_SERIALIZABLE_CHECK, HF::Core::SessionManagement::GetEntriesMessage::min_size, HF::Core::SessionManagement::GetEntriesMessage::offset, and HF::Common::ByteArray::read().
             {
                HF_SERIALIZABLE_CHECK(array, offset, min_size);
                offset += array.read(offset, this->offset);
                array.read(offset, this->count);
                return min_size;
             }
Variable Documentation
address
uint16_t HF::Core::SessionManagement::AbstractServer::Session::address
Device address for session.
Definition at line 321 of file session_management.h.
count [1/2]
uint16_t HF::Core::SessionManagement::StartResponse::count
Number of device entries.
Definition at line 58 of file session_management.h.
count [2/2]
uint8_t HF::Core::SessionManagement::GetEntriesMessage::count
Number of entries to be sent in the response.
Definition at line 104 of file session_management.h.
offset
uint16_t HF::Core::SessionManagement::GetEntriesMessage::offset
Start index for the first entry to be provided.
Definition at line 103 of file session_management.h.
Referenced by HF::Core::SessionManagement::GetEntriesMessage::pack(), and HF::Core::SessionManagement::GetEntriesMessage::unpack().
valid
bool HF::Core::SessionManagement::AbstractServer::Session::valid
Indicate if the session is still valid.
Definition at line 322 of file session_management.h.