HAN-FUN API: Alert Interface
Alert Interface
Interfaces
This module contains the classes that define and implement the Alert interface API.
Data Structures
struct HF::Interfaces::Alert::Message
Payload for the Status command.
struct HF::Interfaces::Alert::State
Helper class to handle the State attribute for the Alert interface.
struct HF::Interfaces::Alert::Enable
Helper class to handle the Enabled attribute for the Alert interface.
struct HF::Interfaces::Alert::Base
Alert Interface : Parent.
class HF::Interfaces::Alert::Server
Alert Interface : Server side implementation.
struct HF::Interfaces::Alert::Client
Alert Interface : Client side implementation.
Enumerations
enum HF::Interfaces::Alert::CMD { HF::Interfaces::Alert::STATUS_CMD = 0x01 }
Command IDs.
enum HF::Interfaces::Alert::Attributes { HF::Interfaces::Alert::STATE_ATTR = 0x01, HF::Interfaces::Alert::ENABLE_ATTR = 0x02 }
Attributes.
Functions
HF::Attributes::IAttribute * HF::Interfaces::create_attribute (HF::Interfaces::Alert::Server *server, uint8_t uid)
Create an attribute object that can hold the attribute with the given uid.
HF::Attributes::IAttribute * HF::Interfaces::Alert::create_attribute (uint8_t uid)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::Alert::Server *,uint8_t)
std::ostream & operator<< (std::ostream &stream, const HF::Interfaces::Alert::CMD command)
Convert the given command into a string and write it to the given stream.
std::ostream & operator<< (std::ostream &stream, const HF::Interfaces::Alert::Attributes attribute)
Convert the given attribute into a string and write it to the given stream.
Detailed Description
This module contains the classes that define and implement the Alert interface API.
Enumeration Type Documentation
enum HF::Interfaces::Alert::Attributes
Attributes.
Enumerator
STATE_ATTR
State attribute UID.
ENABLE_ATTR
Enable attribute UID.
Definition at line 76 of file alert.h.
          {
             STATE_ATTR    = 0x01,
             ENABLE_ATTR   = 0x02,
             __LAST_ATTR__ = ENABLE_ATTR,
          } Attributes;
enum HF::Interfaces::Alert::CMD
Command IDs.
Enumerator
STATUS_CMD
Alert Status Command ID.
Definition at line 69 of file alert.h.
          {
             STATUS_CMD   = 0x01,
             __LAST_CMD__ = STATUS_CMD
          } CMD;
Function Documentation
HF::Attributes::IAttribute* HF::Interfaces::create_attribute (HF::Interfaces::Alert::Server * server, uint8_t uid)
Create an attribute object that can hold the attribute with the given uid.
If server is not equal to nullptr then initialize it with the current value.
Parameters
[in] server pointer to the object to read the current value from.
[in] uid attribute's UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
Referenced by HF::Interfaces::SimpleHumidity::Server::attribute(), HF::Interfaces::OnOff::Server::attribute(), HF::Interfaces::SimpleTemperature::Server::attribute(), HF::Interfaces::LevelControl::Server::attribute(), HF::Interfaces::Alert::Server::attribute(), HF::Interfaces::SimpleThermostat::Server::attribute(), HF::Interfaces::SimpleTemperature::create_attribute(), and HF::Interfaces::SimpleVisualEffects::create_attribute().
HF::Attributes::IAttribute* HF::Interfaces::Alert::create_attribute (uint8_t uid) inline
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::Alert::Server *,uint8_t)
See also
HF::Interfaces::create_attribute (HF::Interfaces::Alert::Server *,uint8_t)
Parameters
[in] uid attribute UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::Alert::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SUOTA::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::RSSI::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceManagement::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceInformation::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::BindManagement::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::AttributeReporting::Server *,uint8_t)
See also
HF::Interfaces::create_attribute (HF::Interfaces::SimpleHumidity::Server *,uint8_t)
Parameters
[in] uid attribute UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::Alert::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SUOTA::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::RSSI::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceManagement::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceInformation::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::BindManagement::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::AttributeReporting::Server *,uint8_t)
See also
HF::Interfaces::create_attribute (HF::Interfaces::SimpleTemperature::Server *,uint8_t)
Parameters
[in] uid attribute UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
Definition at line 107 of file simple_humidity.h.
          {
             return Interfaces::create_attribute(static_cast<SimpleHumidity::Server *>(nullptr),
                                                 uid);
          }
std::ostream& operator<< (std::ostream & stream, const HF::Interfaces::Alert::CMD command)
Convert the given command into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] command role value to convert to a string.
Returns
stream
std::ostream& operator<< (std::ostream & stream, const HF::Interfaces::Alert::Attributes attribute)
Convert the given attribute into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] attribute attribute value to convert to a string.
Returns
stream