HAN-FUN API: Bind Management
Bind Management
Core Services & Interfaces
This module contains the classes that implement the Bind Management service.
Data Structures
struct HF::Core::BindManagement::Entry
This represents a bind entry data structure.
struct HF::Core::BindManagement::Message
Add/Remove Bind message.
struct HF::Core::BindManagement::IEntries
Bind Management persistent storage API.
class HF::Core::BindManagement::Abstract
Parent class for the Bind Management interface implementation.
class HF::Core::BindManagement::Client
Bind Management interface : Client side.
struct HF::Core::BindManagement::IServer
Bind Management interface : Server side API.
struct HF::Core::BindManagement::AbstractServer
Parent class for bind management - server role.
struct HF::Core::BindManagement::Entries
Default implementation of the bind entries container.
struct HF::Core::BindManagement::Server< _Entries >
Helper class used to implement custom functionality to the bind management server side.
Enumerations
enum HF::Core::BindManagement::CMD {
HF::Core::BindManagement::ADD_BIND_CMD = 0x01, HF::Core::BindManagement::REMOVE_BIND_CMD = 0x02, HF::Core::BindManagement::START_SESSION_CMD = 0x03, HF::Core::BindManagement::END_SESSION_CMD = 0x04,
HF::Core::BindManagement::GET_ENTRIES_CMD = 0x05
}
Commands.
enum HF::Core::BindManagement::Attributes { HF::Core::BindManagement::NUMBER_OF_ENTRIES_ATTR = 0x01 }
Attributes.
Functions
HF::Attributes::IAttribute * HF::Core::create_attribute (HF::Core::BindManagement::IServer *server, uint8_t uid)
Create an attribute object that can hold the attribute with the given uid.
HF::Core::BindManagement::Entry::Entry (Protocol::Address _source, Common::Interface _itf)
Constructor.
HF::Core::BindManagement::Entry::Entry (Protocol::Address _source, Common::Interface _itf, Protocol::Address _destination)
Constructor.
uint16_t HF::Core::BindManagement::Entry::size () const
Number bytes needed to serialize the message.
uint16_t HF::Core::BindManagement::Entry::pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t HF::Core::BindManagement::Entry::unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
virtual Common::Result HF::Core::BindManagement::IEntries::destroy (uint16_t address, Protocol::Address::Type type=Protocol::Address::DEVICE)=0
Destroy the entries in the persistent storage, that refer to the the given address.
virtual EntryPtr HF::Core::BindManagement::IEntries::find (const Protocol::Address &source, const Common::Interface &itf, const Protocol::Address &destination) const =0
Return the Bind entry for the given parameters.
virtual bool HF::Core::BindManagement::IEntries::any_of (Protocol::Address const &source, Common::Interface const &itf) const =0
Check if entries for the device with given source address and for the given interface ifc exist.
virtual void HF::Core::BindManagement::IEntries::for_each (Protocol::Address const &source, Common::Interface const &itf, std::function< void(const Entry &)> func) const =0
Call the given function for all the entries with given source address and for the given interface ifc.
HF::Attributes::IAttribute * HF::Core::BindManagement::create_attribute (uint8_t uid)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::BindManagement::Server *,uint8_t)
HF::Core::BindManagement::Abstract::Abstract (HF::Core::Unit0 &unit)
Constructor.
HF::Core::BindManagement::Client::Client (HF::Core::Unit0 &unit)
Constructor.
SessionMgr & HF::Core::BindManagement::Client::session ()
Reference to the session management API.
void HF::Core::BindManagement::Client::send (const Protocol::Address &addr, Protocol::Message &message)
Send message msg to the network address given by addr.
HF::Devices::Concentrator::IUnit0 & HF::Core::BindManagement::IServer::unit0 () const
Return a reference to the unit that this service belongs to.
virtual IEntries & HF::Core::BindManagement::IServer::entries () const =0
Reference to the persistent storage implementation.
virtual
SessionManagement::IServer & HF::Core::BindManagement::IServer::sessions ()=0
Reference to the session management API.
HF::Core::BindManagement::IServer::IServer (Unit0 &unit)
Constructor.
Common::Result HF::Core::BindManagement::AbstractServer::add (const Protocol::Address &source, const Protocol::Address &destination, const Common::Interface &itf)
Create a new bind entry in the database.
Common::Result HF::Core::BindManagement::AbstractServer::remove (const Protocol::Address &source, const Protocol::Address &destination, const Common::Interface &itf)
Remove a bind entry from the database.
HF::Core::BindManagement::AbstractServer::AbstractServer (Unit0 &unit)
Constructor.
uint16_t HF::Core::BindManagement::Entries::size () const
Return the number of entries in the container.
Common::Result HF::Core::BindManagement::Entries::destroy (const Entry &entry)
Destroy the given entry in the persistent storage.
Common::Result HF::Core::BindManagement::Entries::destroy (uint16_t address, Protocol::Address::Type type=Protocol::Address::DEVICE)
Destroy the entries in the persistent storage, that refer to the the given address.
EntryPtr HF::Core::BindManagement::Entries::find (const Protocol::Address &source, const Common::Interface &itf, const Protocol::Address &destination) const
Return the Bind entry for the given parameters.
bool HF::Core::BindManagement::Entries::any_of (Protocol::Address const &source, Common::Interface const &itf) const
Check if entries for the device with given source address and for the given interface ifc exist.
void HF::Core::BindManagement::Entries::for_each (Protocol::Address const &source, Common::Interface const &itf, std::function< void(const Entry &)> func) const
Call the given function for all the entries with given source address and for the given interface ifc.
std::pair< iterator, iterator > HF::Core::BindManagement::Entries::find (Protocol::Address const &source, Common::Interface const &itf) const
Return a pair of iterators for the entries that match the given search criteria.
template<typename Func >
Common::Result HF::Core::BindManagement::Entries::destroy (Func func)
Destroy the entries in the persistent storage, for which the given predicate function returns true.
HF::Core::BindManagement::Server< _Entries >::Server (Unit0 &unit)
Constructor.
Container & HF::Core::BindManagement::Server< _Entries >::entries () const
Reference to the persistent storage implementation.
SessionMgr & HF::Core::BindManagement::Server< _Entries >::sessions ()
Reference to the session management API.
void HF::Core::BindManagement::Server< _Entries >::send (const Protocol::Address &addr, Protocol::Message &message)
Send message msg to the network address given by addr.
std::ostream & operator<< (std::ostream &stream, const HF::Core::BindManagement::CMD command)
Convert the given command into a string and write it to the given stream.
std::ostream & operator<< (std::ostream &stream, const HF::Core::BindManagement::Attributes attribute)
Convert the given attribute into a string and write it to the given stream.
Variables
Protocol::Address HF::Core::BindManagement::Entry::source
Source Address.
Protocol::Address HF::Core::BindManagement::Entry::destination
Destination Address.
Common::Interface HF::Core::BindManagement::Entry::itf
Destination Interface.
static constexpr uint16_t HF::Core::BindManagement::Entry::min_size
Minimum pack/unpack required data size.
Container HF::Core::BindManagement::Entries::db
Container for the bind entries.
_Entries HF::Core::BindManagement::Server< _Entries >::_entries
Bind entries database.
Commands
void HF::Core::BindManagement::Client::add (const Protocol::Address &source, const Protocol::Address &destination, const Common::Interface &itf)
Send a ADD_BIND command.
void HF::Core::BindManagement::Client::remove (const Protocol::Address &source, const Protocol::Address &destination, const Common::Interface &itf)
Send a REMOVE_BIND command.
void HF::Core::BindManagement::Client::start_session () const
Start read entries session.
void HF::Core::BindManagement::Client::get_entries (uint16_t offset, uint8_t count=0) const
Read entries.
void HF::Core::BindManagement::Client::end_session () const
End read entries session.
Events
virtual void HF::Core::BindManagement::Client::response (const CMD cmd, const Protocol::Response &response)
This method is called when the response to a command is received.
Commands
virtual Common::Result HF::Core::BindManagement::IServer::add (const Protocol::Address &source, const Protocol::Address &destination, const Common::Interface &itf)=0
Create a new bind entry in the database.
virtual Common::Result HF::Core::BindManagement::IServer::remove (const Protocol::Address &source, const Protocol::Address &destination, const Common::Interface &itf)=0
Remove a bind entry from the database.
Detailed Description
This module contains the classes that implement the Bind Management service.
Enumeration Type Documentation
enum HF::Core::BindManagement::Attributes
Attributes.
Enumerator
NUMBER_OF_ENTRIES_ATTR
Number of entries attribute.
Definition at line 101 of file bind_management.h.
          {
             NUMBER_OF_ENTRIES_ATTR = 0x01,
             __LAST_ATTR__          = NUMBER_OF_ENTRIES_ATTR
          } Attributes;
enum HF::Core::BindManagement::CMD
Commands.
Enumerator
ADD_BIND_CMD
Add bind entry command.
REMOVE_BIND_CMD
Remove bind entry command.
START_SESSION_CMD
Start Session Read Registration Info.
END_SESSION_CMD
End Session Read Registration Info.
GET_ENTRIES_CMD
Get Entries Command.
Definition at line 90 of file bind_management.h.
          {
             ADD_BIND_CMD      = 0x01,
             REMOVE_BIND_CMD   = 0x02,
             START_SESSION_CMD = 0x03,
             END_SESSION_CMD   = 0x04,
             GET_ENTRIES_CMD   = 0x05,
             __LAST_CMD__      = GET_ENTRIES_CMD
          } CMD;
Function Documentation
HF::Core::BindManagement::Abstract::Abstract (HF::Core::Unit0 & unit) inline protected
Constructor.
Parameters
[in] unit reference to the unit containing this service.
Definition at line 263 of file bind_management.h.
                                        :
                Service (unit)
             {}
HF::Core::BindManagement::AbstractServer::AbstractServer (Unit0 & unit) inline protected
Constructor.
Parameters
[in] unit reference to the unit containing this service.
Definition at line 524 of file bind_management.h.
                                        :IServer (unit)
             {}
HF::Core::BindManagement::Client::Client (HF::Core::Unit0 & unit) inline
Constructor.
Parameters
[in] unit reference to the unit containing this service.
Definition at line 285 of file bind_management.h.
                                      :
                ServiceRole (unit)
             {}
HF::Core::BindManagement::Entry::Entry (Protocol::Address _source, Common::Interface _itf) inline
Constructor.
Parameters
[in] _source device source for the bind entry.
[in] _itf interface UID + role for the bind entry.
Definition at line 127 of file bind_management.h.
                                                                 :
                source (_source), itf (_itf)
             {}
HF::Core::BindManagement::Entry::Entry (Protocol::Address _source, Common::Interface _itf, Protocol::Address _destination) inline
Constructor.
Parameters
[in] _source device source for the bind entry.
[in] _itf interface UID + role for the bind entry.
[in] _destination destination device for he bing entry.
Definition at line 138 of file bind_management.h.
                                                :
                source (_source), destination (_destination), itf (_itf)
             {}
HF::Core::BindManagement::IServer::IServer (Unit0 & unit) inline protected
Constructor.
Parameters
[in] unit reference to the unit containing this service.
Definition at line 478 of file bind_management.h.
                                 :
                ServiceRole <Abstract, HF::Interface::SERVER_ROLE>(unit)
             {}
template<typename _Entries = Entries> HF::Core::BindManagement::Server< _Entries >::Server (Unit0 & unit) inline
Constructor.
Parameters
[in] unit reference to the unit containing this service.
Definition at line 653 of file bind_management.h.
                                :AbstractServer (unit)
             {}
void HF::Core::BindManagement::Client::add (const Protocol::Address & source, const Protocol::Address & destination, const Common::Interface & itf)
Send a ADD_BIND command.
Parameters
[in] source the HAN-FUN source device.
[in] destination the HAN-FUN destination device.
[in] itf the interface to bind between source and destination.
virtual Common::Result HF::Core::BindManagement::IServer::add (const Protocol::Address & source, const Protocol::Address & destination, const Common::Interface & itf) pure virtual
Create a new bind entry in the database.
Parameters
[in] source the HAN-FUN source device.
[in] destination the HAN-FUN destination device.
[in] itf the interface to bind between source and destination.
Returns
Common::Result::OK if the bind was created or Result::FAIL_* otherwise.
Implemented in HF::Core::BindManagement::AbstractServer.
Common::Result HF::Core::BindManagement::AbstractServer::add (const Protocol::Address & source, const Protocol::Address & destination, const Common::Interface & itf) virtual
Create a new bind entry in the database.
Parameters
[in] source the HAN-FUN source device.
[in] destination the HAN-FUN destination device.
[in] itf the interface to bind between source and destination.
Returns
Common::Result::OK if the bind was created or Result::FAIL_* otherwise.
Implements HF::Core::BindManagement::IServer.
virtual bool HF::Core::BindManagement::IEntries::any_of (Protocol::Address const & source, Common::Interface const & itf) const pure virtual
Check if entries for the device with given source address and for the given interface ifc exist.
Parameters
[in] source device address to search for.
[in] itf interface id to search for.
Return values
true if entries exist,
false otherwise.
Implemented in HF::Core::BindManagement::Entries.
bool HF::Core::BindManagement::Entries::any_of (Protocol::Address const & source, Common::Interface const & itf) const virtual
Check if entries for the device with given source address and for the given interface ifc exist.
Parameters
[in] source device address to search for.
[in] itf interface id to search for.
Return values
true if entries exist,
false otherwise.
Implements HF::Core::BindManagement::IEntries.
HF::Attributes::IAttribute* HF::Core::create_attribute (HF::Core::BindManagement::IServer * server, uint8_t uid)
Create an attribute object that can hold the attribute with the given uid.
If server is not equal to nullptr then initialize it with the current value.
Parameters
[in] server pointer to the object to read the current value from.
[in] uid attribute's UID to create the attribute object for.
Returns
pointer to an attribute object or nullptr if the attribute UID does not exist.
HF::Attributes::IAttribute* HF::Core::BindManagement::create_attribute (uint8_t uid)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::BindManagement::Server *,uint8_t)
See also
HF::Core::create_attribute (HF::Core::BindManagement::Server *,uint8_t)
Parameters
[in] uid attribute UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
virtual Common::Result HF::Core::BindManagement::IEntries::destroy (uint16_t address, Protocol::Address::Type type = Protocol::Address::DEVICE) pure virtual
Destroy the entries in the persistent storage, that refer to the the given address.
This method destroys the entries that refer to the address both in the source and in the destination address.
Parameters
[in] address HF address to remove entries for.
[in] type HF address type.
Return values
Common::Result::OK and a copy of the destroyed entry if the entry was destroyed.
Common::Result::FAIL_ARG and nullptr otherwise.
Implemented in HF::Core::BindManagement::Entries.
Common::Result HF::Core::BindManagement::Entries::destroy (const Entry & entry)
Destroy the given entry in the persistent storage.
Parameters
[in] entry reference to the bind entry to erase.
Return values
Common::Result::OK,if the entry was destroyed.
Common::Result::FAIL_ARG otherwise.
Warning
the reference passed into this method SHOULD NOT be considered valid if it was obtained by calling the find method.
Referenced by HF::Core::BindManagement::Entries::destroy().
Common::Result HF::Core::BindManagement::Entries::destroy (uint16_t address, Protocol::Address::Type type = Protocol::Address::DEVICE) virtual
Destroy the entries in the persistent storage, that refer to the the given address.
This method destroys the entries that refer to the address both in the source and in the destination address.
Parameters
[in] address HF address to remove entries for.
[in] type HF address type.
Return values
Common::Result::OK and a copy of the destroyed entry if the entry was destroyed.
Common::Result::FAIL_ARG and nullptr otherwise.
Implements HF::Core::BindManagement::IEntries.
template<typename Func > Common::Result HF::Core::BindManagement::Entries::destroy (Func func) inline
Destroy the entries in the persistent storage, for which the given predicate function returns true.
Parameters
[in] func predicate to call for each entry to check if it should be deleted.
Return values
Common::Result::OK if at least one entry was destroyed.
Common::Result::FAIL_ARG,otherwise.
Definition at line 611 of file bind_management.h.
References HF::Core::BindManagement::Entries::db, HF::Core::BindManagement::Entries::destroy(), HF::Common::FAIL_ARG, and HF::Common::OK.
             {
                Common::Result result = Common::Result::FAIL_ARG;
                for (iterator itr = db.begin (); itr != db.end ();)
                {
                   if (func (*itr))
                   {
                      auto old = itr++;
                      destroy (*old);
                      result = Common::Result::OK;
                   }
                   else
                   {
                      ++itr;
                   }
                }
                return result;
             }
virtual IEntries& HF::Core::BindManagement::IServer::entries () const pure virtual
Reference to the persistent storage implementation.
Returns
reference to the object responsible by the persistent storage of the bind entries.
Implemented in HF::Core::BindManagement::Server< _Entries >, and HF::Core::BindManagement::Server< Entries >.
template<typename _Entries = Entries> Container& HF::Core::BindManagement::Server< _Entries >::entries () const inline virtual
Reference to the persistent storage implementation.
Returns
reference to the object responsible by the persistent storage of the bind entries.
Implements HF::Core::BindManagement::IServer.
Definition at line 659 of file bind_management.h.
             {
                return SessionMgr::entries ();
             }
virtual EntryPtr HF::Core::BindManagement::IEntries::find (const Protocol::Address & source, const Common::Interface & itf, const Protocol::Address & destination) const pure virtual
Return the Bind entry for the given parameters.
Parameters
[in] source source address of the device.
[in] destination destination address of the device.
[in] itf interface to bind.
Return values
a pointer to bind entry for the given parameters,
nullptr if bind entry does not exist.
Implemented in HF::Core::BindManagement::Entries.
EntryPtr HF::Core::BindManagement::Entries::find (const Protocol::Address & source, const Common::Interface & itf, const Protocol::Address & destination) const virtual
Return the Bind entry for the given parameters.
Parameters
[in] source source address of the device.
[in] destination destination address of the device.
[in] itf interface to bind.
Return values
a pointer to bind entry for the given parameters,
nullptr if bind entry does not exist.
Implements HF::Core::BindManagement::IEntries.
std::pair<iterator, iterator> HF::Core::BindManagement::Entries::find (Protocol::Address const & source, Common::Interface const & itf) const
Return a pair of iterators for the entries that match the given search criteria.
Parameters
[in] source device address to search for.
[in] itf interface id to search for.
Returns
iterators to the entries found.
virtual void HF::Core::BindManagement::IEntries::for_each (Protocol::Address const & source, Common::Interface const & itf, std::function< void(const Entry &)> func) const pure virtual
Call the given function for all the entries with given source address and for the given interface ifc.
Parameters
[in] source device address to search for.
[in] itf interface id to search for.
[in] func function to call for all the entries.
Implemented in HF::Core::BindManagement::Entries.
void HF::Core::BindManagement::Entries::for_each (Protocol::Address const & source, Common::Interface const & itf, std::function< void(const Entry &)> func) const virtual
Call the given function for all the entries with given source address and for the given interface ifc.
Parameters
[in] source device address to search for.
[in] itf interface id to search for.
[in] func function to call for all the entries.
Implements HF::Core::BindManagement::IEntries.
void HF::Core::BindManagement::Client::get_entries (uint16_t offset, uint8_t count = 0) const inline virtual
Read entries.
Parameters
[in] offset start read at offset.
[in] count number of entries to read.
Implements HF::Core::SessionManagement::AbstractClient.
Definition at line 347 of file bind_management.h.
References HF::Interface::DEVICE_MANAGEMENT, and HF::Core::BindManagement::GET_ENTRIES_CMD.
             {
                SessionMgr::get_entries <SERVER_ROLE, Interface::DEVICE_MANAGEMENT,
                                         GET_ENTRIES_CMD>(offset, count);
             }
std::ostream& operator<< (std::ostream & stream, const HF::Core::BindManagement::CMD command)
Convert the given command into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] command role value to convert to a string.
Returns
stream
std::ostream& operator<< (std::ostream & stream, const HF::Core::BindManagement::Attributes attribute)
Convert the given attribute into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] attribute attribute value to convert to a string.
Returns
stream
uint16_t HF::Core::BindManagement::Entry::pack (Common::ByteArray & array, uint16_t offset = 0) const
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
void HF::Core::BindManagement::Client::remove (const Protocol::Address & source, const Protocol::Address & destination, const Common::Interface & itf)
Send a REMOVE_BIND command.
Parameters
[in] source the HAN-FUN source device.
[in] destination the HAN-FUN destination device.
[in] itf the interface to unbind between source and destination.
virtual Common::Result HF::Core::BindManagement::IServer::remove (const Protocol::Address & source, const Protocol::Address & destination, const Common::Interface & itf) pure virtual
Remove a bind entry from the database.
Parameters
[in] source the HAN-FUN source device.
[in] destination the HAN-FUN destination device.
[in] itf the interface to bind between source and destination.
Returns
Common::Result::OK if the bind was removed or Result::FAIL_* otherwise.
Implemented in HF::Core::BindManagement::AbstractServer.
Common::Result HF::Core::BindManagement::AbstractServer::remove (const Protocol::Address & source, const Protocol::Address & destination, const Common::Interface & itf) virtual
Remove a bind entry from the database.
Parameters
[in] source the HAN-FUN source device.
[in] destination the HAN-FUN destination device.
[in] itf the interface to bind between source and destination.
Returns
Common::Result::OK if the bind was removed or Result::FAIL_* otherwise.
Implements HF::Core::BindManagement::IServer.
virtual void HF::Core::BindManagement::Client::response (const CMD cmd, const Protocol::Response & response) virtual
This method is called when the response to a command is received.
Parameters
[in] cmd the command that response refers to.
[in] response the result of the command.
void HF::Core::BindManagement::Client::send (const Protocol::Address & addr, Protocol::Message & message) inline virtual
Send message msg to the network address given by addr.
Parameters
[in] addr HF network address.
[in] message pointer to the message to be sent to the network.
Implements HF::Core::SessionManagement::AbstractClient.
Definition at line 384 of file bind_management.h.
References HF::Core::AbstractService::send().
             {
                Service::send (addr, message);
             }
template<typename _Entries = Entries> void HF::Core::BindManagement::Server< _Entries >::send (const Protocol::Address & addr, Protocol::Message & message) inline virtual
Send message msg to the network address given by addr.
Parameters
[in] addr HF network address.
[in] message pointer to the message to be sent to the network.
Implements HF::Core::SessionManagement::AbstractServer.
Definition at line 671 of file bind_management.h.
             {
                AbstractServer::send (addr, message);
             }
SessionMgr& HF::Core::BindManagement::Client::session () inline
Reference to the session management API.
Returns
reference to the object implementing the session management API for this device management client.
Definition at line 297 of file bind_management.h.
             {
                return *this;
             }
virtual SessionManagement::IServer& HF::Core::BindManagement::IServer::sessions () pure virtual
Reference to the session management API.
Returns
reference to the object implementing the session management API for this bind management server.
Implemented in HF::Core::BindManagement::Server< _Entries >, and HF::Core::BindManagement::Server< Entries >.
template<typename _Entries = Entries> SessionMgr& HF::Core::BindManagement::Server< _Entries >::sessions () inline virtual
Reference to the session management API.
Returns
reference to the object implementing the session management API for this bind management server.
Implements HF::Core::BindManagement::IServer.
Definition at line 664 of file bind_management.h.
             {
                return *this;
             }
uint16_t HF::Core::BindManagement::Entry::size () const
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
uint16_t HF::Core::BindManagement::Entries::size () const virtual
Return the number of entries in the container.
Returns
the number of entries in the container.
Implements HF::Common::IEntries< Entry >.
Referenced by COMMAND().
HF::Devices::Concentrator::IUnit0& HF::Core::BindManagement::IServer::unit0 () const
Return a reference to the unit that this service belongs to.
This is the same reference as AbstractService::unit, but static casted to allow access to the the other interfaces.
Returns
a reference to the unit that holds this interface.
uint16_t HF::Core::BindManagement::Entry::unpack (const Common::ByteArray & array, uint16_t offset = 0)
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Variable Documentation
template<typename _Entries = Entries> _Entries HF::Core::BindManagement::Server< _Entries >::_entries protected
Bind entries database.
Definition at line 678 of file bind_management.h.
Protocol::Address HF::Core::BindManagement::Entry::destination
Destination Address.
Definition at line 114 of file bind_management.h.
Referenced by from_json(), BindManagement::Server::restore(), and to_json().
Common::Interface HF::Core::BindManagement::Entry::itf
Destination Interface.
Definition at line 116 of file bind_management.h.
Referenced by from_json(), and to_json().
Protocol::Address HF::Core::BindManagement::Entry::source
Source Address.
Definition at line 112 of file bind_management.h.
Referenced by from_json(), BindManagement::Server::restore(), and to_json().