HAN-FUN API: Examples
Examples
This module contains the classes for the provided example applications.
Namespaces
HF::Application
This namespace contains the declaration of the functions that implement the HAN-FUN example applications.
Data Structures
struct Base
This class represents a HAN-FUN Concentrator.
struct ICommand
Example application menu entry API.
class Command
Parent class for the commands API implementations.
struct Node
This class represents a node in the HAN-FUN network.
struct SimpleLight
Unit implementing a Simple Light.
struct SimpleSwitch
Unit implementing a Simple Switch.
struct msg_t
Message sent between the concentrator and the nodes.
struct hello_msg_t
Hello message payload.
Macros
#define HF_APP_CONFIG_FILE "./hanfun.json"
JSON database file.
#define COMMAND(_name, _key, _help)
Helper macro to define new commands.
#define COMMAND_ADD(_name)
Helper macro to add a new command to the registry.
#define STRTOL(X) strtol(X.c_str(), NULL, 10);
Helper macro to convert a std::string into a number (base 10).
#define STRTOL_HEX(X) strtol(X.c_str(), NULL, 16);
Helper macro to convert a std::string into a number (base 16).
#define NONE_MSG 0xFFFF
No message primitive id.
#define HELLO_MSG 0x0101
Hello message primitive id.
#define DATA_MSG 0x0201
Data message primitive id.
#define CHECK_STATUS()
Helper macro the check libuv command status.
Typedefs
typedef HF::Devices::Concentrator::Unit0< HF::Core::DeviceInformation::Server,::DeviceManagement::Server, HF::Core::AttributeReporting::Server,::BindManagement::Server > Unit0
Custom Unit0 declaration.
Functions
void to_json (const HF::Common::Interface &interface, Json::Value &node)
Serialize a HF::Common::Interface to the given Json::Value.
void to_json (const HF::Core::DeviceManagement::Unit &unit, Json::Value &node)
Serialize a HF::Core::DeviceManagement::Unit to the given Json::Value.
void to_json (const HF::Core::DeviceManagement::Device &device, Json::Value &node)
Serialize a HF::Core::DeviceManagement::Device to the given Json::Value.
void to_json (const HF::Protocol::Address &address, Json::Value &node)
Serialize a HF::Protocol::Address to the given Json::Value.
void to_json (const HF::Core::BindManagement::Entry &entry, Json::Value &node)
Serialize a HF::Core::BindManagement::Entry to the given Json::Value.
void from_json (Json::Value &node, HF::Common::Interface &interface)
Fill a HF::Common::Interface from the given Json::Value object.
void from_json (Json::Value &node, HF::Core::DeviceManagement::Unit &unit)
Fill a HF::Core::DeviceManagement::Unit from the given Json::Value object.
void from_json (Json::Value &node, HF::Core::DeviceManagement::Device &device)
Fill a HF::Core::DeviceManagement::Device from the given Json::Value object.
void from_json (Json::Value &node, HF::Protocol::Address &address)
Fill a HF::Protocol::Address from the given Json::Value object.
void from_json (Json::Value &node, HF::Core::BindManagement::Entry &entry)
Fill a HF::Core::BindManagement::Entry from the given Json::Value object.
void to_json (HF::UID::UID *uid, Json::Value &node)
Serialize a HF::UID::UID pointer to the given Json::Value.
void from_json (Json::Value &node, HF::UID::UID *&uid)
Create a new HF::UID::UID based on the fields present in the given Json::Value object.
COMMAND (ListRegs,"lr","lr:list registrations.")
ListRegs List registrations command.
COMMAND (ListBinds,"lb","lb:list binds.")
List binds command.
COMMAND (Register,"r","r 1 x:register device x.\nr 0:exit registration mode.")
Setup registration command.
COMMAND (Deregister,"d","d x:de-register device x.")
De-register device command.
COMMAND (Unbind,"u","u x y:unbind device x with y.")
Destroy bind command.
COMMAND (GlobalBind,"gb","gb 1:create bind to receive all interface events.\n""gb 0:remove bind to receive all interface events.")
Global binds command.
COMMAND (On,"on","on d u:Send an ON command to device/unit pair.")
Send ON command.
COMMAND (Off,"off","off d u:Send an OFF command to device/unit pair.")
Send OFF command.
COMMAND (Toggle,"toggle","toggle d u:Send a TOGGLE command to device/unit pair.")
Send TOGGLE command.
COMMAND (DevInfo,"di","di m d:Get device information mandatory attributes.\n""di a d:Get device information all attributes.")
Get Device information.
uv_buf_t alloc_buffer (uv_handle_t *handle, size_t suggested_size)
This function is used to allocate the buffers used with libuv.
COMMAND (Register,"r","r:register device")
Register node command.
COMMAND (Address,"a","a:device address")
Print node address command.
COMMAND (SimpleLight,"sl","sl:set device as a simple light")
Change device to a simple light.
COMMAND (SimpleSwitch,"ss","ss:set device as a simple switch")
Change device to a simple switch.
COMMAND (On,"on","on:On Command")
Send an on command from the simple switch.
COMMAND (Off,"off","off:Off Command")
Send an off command from the simple switch.
COMMAND (Toggle,"toggle","toggle:Toggle Command")
Send a toggle command from the simple switch.
void print_error (uv_err_t status)
Print a user friendly string for given status code.
void DeviceManagement::Entries::insert (const Device &device)
Insert a device management entry into the database.
bool DeviceManagement::Server::available (uint16_t address)
Check if the given address is available for registration.
uint16_t DeviceManagement::Server::next_address ()
Return next available address for registering a device.
bool DeviceManagement::Server::deregister (uint16_t address)
De-register the device with the given address.
void DeviceManagement::Server::save (Json::Value &root)
Save the device entries into the JSON database.
void DeviceManagement::Server::restore (Json::Value root)
Restore the device entries from the JSON database.
void BindManagement::Entries::insert (Entry &entry)
Insert a bind management entry into the database.
void BindManagement::Server::save (Json::Value &root)
Save the bind entries into the JSON database.
void BindManagement::Server::restore (Json::Value root)
Restore the bind entries from the JSON database.
void Base::receive (HF::Protocol::Packet &packet, HF::Common::ByteArray &payload, uint16_t offset)
Callback to deliver a packet received from the transport layer.
bool Base::has_bind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Check if bind exists.
uint8_t Base::bind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Create a new bind entry.
bool Base::unbind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Remove the binding entry for the given devices.
void HF::Application::Initialize (HF::Transport::Layer &transport)
Initialize the application.
void HF::Application::Save ()
Save application configuration.
void HF::Application::Restore ()
Restore application configuration.
void HF::Application::Saved ()
Callback indicating that the application configuration has been saved.
void HF::Application::Restored ()
Callback indicating that the application configuration has been restored.
void Node::receive (HF::Protocol::Packet &packet, HF::Common::ByteArray &payload, uint16_t offset)
Callback to deliver a packet received from the transport layer.
void SimpleLight::on (HF::Protocol::Address &source)
Callback that is called when a ON_CMD message is received.
void SimpleLight::off (HF::Protocol::Address &source)
Callback that is called when a OFF_CMD message is received.
void SimpleLight::toggle (HF::Protocol::Address &source)
Callback that is called when a TOGGLE_CMD message is received.
void HF::Application::Transport::initialize ()
Initialize the associated transport layer.
void HF::Application::Transport::destroy ()
Free the system resources associated with this transport layer.
void HF::Application::Link::send (HF::Common::ByteArray &array)
Send the data in the given ByteArray using the link to the remote end-point.
Variables
uint16_t arg2 = STRTOL(args[1])
Create bind command.
Detailed Description
This module contains the classes for the provided example applications.
Macro Definition Documentation
#define DATA_MSG 0x0201
Data message primitive id.
Definition at line 45 of file transport.cpp.
Referenced by print_error(), and HF::Application::Link::send().
#define HELLO_MSG 0x0101
Hello message primitive id.
Definition at line 44 of file transport.cpp.
Referenced by print_error().
#define HF_APP_CONFIG_FILE "./hanfun.json"
JSON database file.
Definition at line 47 of file base_app.cpp.
Referenced by HF::Application::Restore(), and HF::Application::Save().
#define NONE_MSG 0xFFFF
No message primitive id.
Definition at line 43 of file transport.cpp.
Function Documentation
uv_buf_t alloc_buffer (uv_handle_t * handle, size_t suggested_size)
This function is used to allocate the buffers used with libuv.
Parameters
[in] handle a pointer to the handle to allocate the buffer for.
[in] suggested_size number bytes to allocate.
Returns
buffer allocated.
Definition at line 212 of file transport.cpp.
References UNUSED.
Referenced by HF::Application::Transport::initialize(), print_error(), and HF::Application::Restored().
 {
    UNUSED(handle);
    return uv_buf_init((char *) calloc(1, suggested_size), suggested_size);
 }
bool DeviceManagement::Server::available (uint16_t address)
Check if the given address is available for registration.
Parameters
[in] address device address to check.
Return values
<tt>true</tt> if no device is registered with the given address;
<tt>false</tt> otherwise.
Definition at line 88 of file base.cpp.
References HF::Core::DeviceManagement::Device::address, HF::Core::DeviceManagement::Entries::begin(), HF::Protocol::BROADCAST_ADDR, and HF::Core::DeviceManagement::Entries::end().
 {
    if (address == 0 || address == HF::Protocol::BROADCAST_ADDR)
    {
       return false;
    }
    /* *INDENT-OFF* */
    auto it = std::find_if(entries().begin(), entries().end(),
                           [address](const HF::Core::DeviceManagement::Device &dev)
{
                              return address == dev.address;
                           });
    /* *INDENT-ON* */
    return it == entries().end();
 }
uint8_t Base::bind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Create a new bind entry.
Parameters
[in] dev_addr_1 HAN-FUN address of the first device.
[in] dev_addr_2 HAN-FUN address of the second device.
Return values
0 Bind created.
1 Bind already created.
2 First device does not exist.
3 Second device does not exist.
Definition at line 625 of file base.cpp.
References HF::Common::OK, HF::Interface::ON_OFF, and HF::Interface::SERVER_ROLE.
 {
    if (this->has_bind(dev_addr_1, dev_addr_2))
    {
       return 1;
    }
    HF::Protocol::Address source(dev_addr_1, 1);
    HF::Common::Interface itf(HF::Interface::ON_OFF, HF::Interface::SERVER_ROLE);
    HF::Protocol::Address destination(dev_addr_2, 1);
    auto res = _unit0.bind_management()->add(source, destination, itf);
    if (res == HF::Common::OK)
    {
       return 0;
    }
    if (_unit0.device_management()->entry(dev_addr_1) == nullptr)
    {
       return 2;
    }
    if (_unit0.device_management()->entry(dev_addr_2) == nullptr)
    {
       return 3;
    }
    return 4;
 }
COMMAND (Register , "r" , "r 1 x:register device x.\nr 0:exit registration mode.")
Setup registration command.
< Disable Registration
< Enable Registration
Definition at line 116 of file base_app.cpp.
References HF::Protocol::BROADCAST_ADDR, LOG, NL, STRTOL, and HF::Devices::Concentrator::Abstract< CoreServices >::unit0().
                              :register device x.\nr 0:exit registration mode.")
 {
    if (args.size() > 0 && args[0] == "0")  //!< Disable Registration
    {
 #ifdef HF_APP_EXT_REG
       if (HF::Application::Registration(false))
       {
          LOG(INFO) << "Disable Registration mode: SUCCESS" << NL;
       }
       else
       {
          LOG(WARN) << "Disable Registration mode: FAIL" << NL;
       }
 #endif
    }
    else if (args.size() > 1 && args[0] == "1")  //!< Enable Registration
    {
       uint16_t address = STRTOL(args[1]);
       if (base.unit0()->device_management()->available(address) && address != 0 &&
           address < HF::Protocol::BROADCAST_ADDR)
       {
          base.unit0()->device_management()->next_address(address);
 #ifdef HF_APP_EXT_REG
          if (HF::Application::Registration(true))
          {
             LOG(INFO) << "Enable Registration mode: SUCCESS" << NL;
          }
          else
          {
             LOG(WARN) << "[HANFUN] Enable Registration mode: FAIL" << NL;
          }
 #endif
          LOG(INFO) << "Next Registration will have address : " << (int) address << NL;
       }
       else
       {
          LOG(ERROR) << "Registration impossible: address " << (int) address
                     << "  not available." << NL;
       }
       return;
    }
    LOG(APP) << usage(true) << NL;
 }
bool DeviceManagement::Server::deregister (uint16_t address)
De-register the device with the given address.
Parameters
[in] address address for the device to de-register.
Return values
<tt>true</tt> if the device was de-registered;
<tt>false</tt> otherwise.
Definition at line 134 of file base.cpp.
References HF::Protocol::BROADCAST_ADDR, and HF::Core::DeviceManagement::AbstractServer::deregister().
 {
    if (address == 0 || address == HF::Protocol::BROADCAST_ADDR)
    {
       return false;
    }
    auto _entry = entry(address);
    if (_entry != nullptr)
    {
       HF::Core::DeviceManagement::Server<Entries>::deregister(_entry);
       return true;
    }
    return false;
 }
void from_json (Json::Value & node, HF::UID::UID *& uid)
Create a new HF::UID::UID based on the fields present in the given Json::Value object.
Parameters
[in] node reference to the Json::Value containing the fields for the HF::UID::UID.
[out] uid reference to the pointer that will hold the created HF::UID::UID object of the correct type (NONE/RFPI/IPUI/MAC/URI).
void from_json (Json::Value & node, HF::Common::Interface & interface)
Fill a HF::Common::Interface from the given Json::Value object.
Parameters
[in] node reference to the Json::Value containing the fields for the HF::Common::Interface.
[out] interface reference to the HF::Common::Interface to update.
Definition at line 841 of file base.cpp.
References HF::Interface::CLIENT_ROLE, HF::Common::Interface::id, HF::Common::Interface::role, and HF::Interface::SERVER_ROLE.
Referenced by from_json(), DeviceManagement::Server::restore(), and BindManagement::Server::restore().
 {
    std::string role = node.get("role", "client").asString();
    if (role[0] == 's' || role[0] == 'S')
    {
       interface.role = HF::Interface::SERVER_ROLE;
    }
    else
    {
       interface.role = HF::Interface::CLIENT_ROLE;
    }
    interface.id = json_uid(node.get("id", "0x7FFF").asString());
 }
void from_json (Json::Value & node, HF::Core::DeviceManagement::Unit & unit)
Fill a HF::Core::DeviceManagement::Unit from the given Json::Value object.
Parameters
[in] node reference to the Json::Value containing the fields for the HF::Core::DeviceManagement::Unit.
[out] unit reference to the HF::Core::DeviceManagement::Unit to update.
Definition at line 910 of file base.cpp.
References HF::Protocol::BROADCAST_UNIT, from_json(), HF::Core::DeviceManagement::Unit::id, HF::Core::DeviceManagement::Unit::interfaces, and HF::Core::DeviceManagement::Unit::profile.
 {
    unit.id      = (uint8_t) node.get("id", HF::Protocol::BROADCAST_UNIT).asUInt();
    unit.profile = json_uid(node.get("profile", "0x7FFF").asString());
    for (unsigned i = 0; i < node["opts"].size(); i++)
    {
       unit.interfaces.push_back(0);
       from_json(node["opts"][i], unit.interfaces[i]);
    }
 }
void from_json (Json::Value & node, HF::Core::DeviceManagement::Device & device)
Fill a HF::Core::DeviceManagement::Device from the given Json::Value object.
Parameters
[in] node reference to the Json::Value containing the fields for the HF::Core::DeviceManagement::Device.
[out] device reference to the HF::Core::DeviceManagement::Device to update.
Definition at line 930 of file base.cpp.
References HF::Core::DeviceManagement::Device::address, HF::Protocol::BROADCAST_ADDR, HF::Core::DeviceManagement::Device::emc, from_json(), HF::Core::DeviceManagement::Device::uid, and HF::Core::DeviceManagement::Device::units.
 {
    dev.address = (uint16_t) node.get("address", HF::Protocol::BROADCAST_ADDR).asUInt();
    for (unsigned i = 0; i < node["units"].size(); i++)
    {
       dev.units.push_back(0);
       from_json(node["units"][i], dev.units[i]);
    }
    dev.emc = json_uid(node.get("emc", "0x0000").asString());
    from_json(node["uid"], dev.uid);
 }
void from_json (Json::Value & node, HF::Protocol::Address & address)
Fill a HF::Protocol::Address from the given Json::Value object.
Parameters
[in] node reference to the Json::Value containing the fields for the HF::Protocol::Address.
[out] address reference to the HF::Protocol::Address to update.
Definition at line 952 of file base.cpp.
References HF::Protocol::Address::device, HF::Protocol::Address::mod, and HF::Protocol::Address::unit.
 {
    addr.mod    = (uint16_t) node.get("mod", 0).asUInt();
    addr.device = (uint16_t) node.get("device", 0).asUInt();
    addr.unit   = (uint8_t) node.get("unit", 0).asUInt();
 }
void from_json (Json::Value & node, HF::Core::BindManagement::Entry & entry)
Fill a HF::Core::BindManagement::Entry from the given Json::Value object.
Parameters
[in] node reference to the Json::Value containing the fields for the HF::Core::BindManagement::Entry.
[out] entry reference to the HF::Core::BindManagement::Entry to update.
Definition at line 966 of file base.cpp.
References HF::Core::BindManagement::Entry::destination, from_json(), HF::Core::BindManagement::Entry::itf, and HF::Core::BindManagement::Entry::source.
 {
    from_json(node["src"], entry.source);
    from_json(node["dst"], entry.destination);
    from_json(node["itf"], entry.itf);
 }
bool Base::has_bind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Check if bind exists.
Parameters
[in] dev_addr_1 HAN-FUN address of the first device.
[in] dev_addr_2 HAN-FUN address of the second device.
Return values
true if the binding exist;
false otherwise.
Definition at line 609 of file base.cpp.
References HF::Interface::ON_OFF, and HF::Interface::SERVER_ROLE.
 {
    HF::Protocol::Address source(dev_addr_1, 1);
    HF::Common::Interface itf(HF::Interface::ON_OFF, HF::Interface::SERVER_ROLE);
    HF::Protocol::Address destination(dev_addr_2, 1);
    return _unit0.bind_management()->entries().find(source, itf, destination) != nullptr;
 }
void HF::Application::Initialize (HF::Transport::Layer & transport)
Initialize the application.
Parameters
[in] transport reference to the transport layer to use.
Definition at line 441 of file base_app.cpp.
References HF::Transport::Layer::add(), COMMAND_ADD, HF::Transport::Layer::initialize(), LOG, NL, and HF::Application::Restore().
Referenced by COMMAND(), and HF::Application::Restored().
 {
    LOG(TRACE) << __PRETTY_FUNCTION__ << NL;
    transport.initialize();
    transport.add(&base);
    COMMAND_ADD(ListRegs);
    COMMAND_ADD(ListBinds);
    COMMAND_ADD(Register);
    COMMAND_ADD(Deregister);
    COMMAND_ADD(Bind);
    COMMAND_ADD(Unbind);
    COMMAND_ADD(GlobalBind);
    COMMAND_ADD(On);
    COMMAND_ADD(Off);
    COMMAND_ADD(Toggle);
    COMMAND_ADD(Raw);
    COMMAND_ADD(DevInfo);
    COMMAND_ADD(Links);
    Restore();
 }
void HF::Application::Transport::initialize () virtual
Initialize the associated transport layer.
This method should initialize the transport layer using it's default values.
Reimplemented from HF::Transport::AbstractLayer.
Definition at line 474 of file transport.cpp.
References alloc_buffer(), CHECK_STATUS, LOG, NL, and print_error().
 {
    uv_loop_t *loop = uv_default_loop();
    uv_tcp_init(loop, &socket);
    socket.data = this;
    LOG(TRACE) << __PRETTY_FUNCTION__ << NL;
    struct sockaddr_in bind_addr = uv_ip4_addr("127.0.0.1", 8000);
    if (uv_tcp_bind(&socket, bind_addr) != 0)
    {
       print_error(loop->last_err);
       exit(-1);
    }
    if (uv_listen((uv_stream_t *) &socket, 128, on_connect) != 0)
    {
       print_error(loop->last_err);
       exit(-2);
    }
 }
void DeviceManagement::Entries::insert (const Device & device)
Insert a device management entry into the database.
This is used to add the entries when reading the configuration from the JSON database.
Parameters
[in] device device entry to add.
Definition at line 62 of file base.cpp.
References HF::Core::DeviceManagement::Entries::destroy(), and HF::Application::Save().
 {
    HF::Core::DeviceManagement::Entries::save(device);
 }
void BindManagement::Entries::insert (Entry & entry)
Insert a bind management entry into the database.
This is used to add the entries when reading the configuration from the JSON database.
Parameters
[in] entry device entry to add.
Definition at line 220 of file base.cpp.
References HF::Core::BindManagement::Entries::destroy(), and HF::Application::Save().
 {
    HF::Core::BindManagement::Entries::save(entry);
 }
uint16_t DeviceManagement::Server::next_address () protected virtual
Return next available address for registering a device.
Returns
the address to use in the next registration.
Reimplemented from HF::Core::DeviceManagement::IServer.
Definition at line 113 of file base.cpp.
References HF::Protocol::BROADCAST_ADDR, and HF::Core::DeviceManagement::IServer::next_address().
 {
    uint16_t result = _next_address;
    _next_address = HF::Protocol::BROADCAST_ADDR;
    if (result == HF::Protocol::BROADCAST_ADDR)
    {
       result = HF::Core::DeviceManagement::Server<Entries>::next_address();
    }
    return result;
 }
void SimpleLight::off (HF::Protocol::Address & source) virtual
Callback that is called when a OFF_CMD message is received.
Parameters
[in] source device address that sent the command.
Reimplemented from HF::Interfaces::OnOff::Server.
Definition at line 66 of file node.cpp.
References LOG, NL, and SimpleLight::off().
Referenced by SimpleLight::off().
 {
    HF::Units::Unit<HF::Profiles::SimpleLight>::off(source);
    LOG(INFO) << ">>>>>>>>>>>>> SimpleLight : OFF <<<<<<<<<<<<<" << NL;
 }
void SimpleLight::on (HF::Protocol::Address & source) virtual
Callback that is called when a ON_CMD message is received.
Parameters
[in] source device address that sent the command.
Reimplemented from HF::Interfaces::OnOff::Server.
Definition at line 60 of file node.cpp.
References LOG, NL, and SimpleLight::on().
Referenced by SimpleLight::on().
 {
    HF::Units::Unit<HF::Profiles::SimpleLight>::on(source);
    LOG(INFO) << ">>>>>>>>>>>>> SimpleLight : ON <<<<<<<<<<<<<" << NL;
 }
void print_error (uv_err_t status)
Print a user friendly string for given status code.
Parameters
[in] status status code to print.
Definition at line 227 of file transport.cpp.
References HF::Devices::Concentrator::Transport::add(), alloc_buffer(), CHECK_STATUS, HF::Common::Cloneable< T >::clone(), msg_t::data, DATA_MSG, HELLO_MSG, LOG, msg_t::nbytes, NL, msg_t::pack(), hello_msg_t::pack(), msg_t::primitive, HF::UID::UID::raw(), HF::Transport::AbstractLayer::receive(), msg_t::size(), hello_msg_t::size(), hello_msg_t::uid, HF::Transport::AbstractLayer::uid(), msg_t::unpack(), hello_msg_t::unpack(), and UNUSED.
Referenced by HF::Application::Transport::initialize().
 {
    LOG(ERROR) << uv_err_name((uv_err_t &) status) << " - "
               << uv_strerror((uv_err_t &) status) << NL;
 }
void Node::receive (HF::Protocol::Packet & packet, HF::Common::ByteArray & payload, uint16_t offset) virtual
Callback to deliver a packet received from the transport layer.
Parameters
[in] packet reference to the received packet.
[in] payload reference a ByteArray containing the received data.
[in] offset offset from where the received data starts on the payload byte array buffer.
Reimplemented from HF::Devices::Node::Abstract< CoreServices >.
Definition at line 45 of file node.cpp.
References LOG, NL, Node::receive(), and HF::Devices::Node::Abstract< CoreServices >::receive().
Referenced by Node::receive().
 {
    LOG(DEBUG) << ">>>>>>>>>>>>> Message Received <<<<<<<<<<<<<" << NL;
    LOG(TRACE) << "Payload : " << payload << NL;
    LOG(DEBUG) << packet << NL;
    HF::Devices::Node::Abstract<HF::Devices::Node::DefaultUnit0>::receive(packet, payload, offset);
 }
void Base::receive (HF::Protocol::Packet & packet, HF::Common::ByteArray & payload, uint16_t offset) virtual
Callback to deliver a packet received from the transport layer.
Parameters
[in] packet reference to the received packet.
[in] payload reference a ByteArray containing the received data.
[in] offset offset from where the received data starts on the payload byte array buffer.
Reimplemented from HF::Devices::Concentrator::AbstractBase.
Definition at line 591 of file base.cpp.
References LOG, NL, and HF::Devices::Concentrator::AbstractBase::receive().
Referenced by COMMAND().
 {
    LOG(DEBUG) << ">>>>>>>>>>>>> Message Received <<<<<<<<<<<<<" << NL;
    LOG(TRACE) << "Payload : " << payload << NL;
    LOG(DEBUG) << std::endl << packet << NL;
    HF::Devices::Concentrator::Abstract<Unit0>::receive(packet, payload, offset);
 }
void DeviceManagement::Server::restore (Json::Value root)
Restore the device entries from the JSON database.
Parameters
[in] root database root to start reading the entries.
Definition at line 182 of file base.cpp.
References HF::Core::DeviceManagement::Server< _Entries >::entries(), from_json(), LOG, NL, and HF::Application::Save().
 {
    LOG(INFO) << "Restoring registration entries ..." << NL;
    HF::Core::DeviceManagement::Device device;
    for (unsigned i = 0; i < root.size(); i++)
    {
       from_json(root[i], device);
       HF::Core::DeviceManagement::Server<Entries>::entries().insert(device);
    }
 }
void BindManagement::Server::restore (Json::Value root)
Restore the bind entries from the JSON database.
Parameters
[in] root database root to start reading the entries.
Definition at line 269 of file base.cpp.
References HF::Core::DeviceInformation::ACTUAL_RESP_TIME_ATTR, HF::Core::DeviceInformation::APP_VERSION_ATTR, HF::Core::DeviceInformation::CORE_VERSION_ATTR, HF::Core::DeviceInformation::create_attribute(), HF::Core::DeviceInformation::DECT_ID_ATTR, HF::Core::BindManagement::Entry::destination, HF::Protocol::Address::device, HF::Interface::DEVICE_INFORMATION, HF::Core::DeviceInformation::EMC_ATTR, HF::Core::DeviceInformation::ENABLED_ATTR, HF::Core::DeviceInformation::EXTRA_CAP_ATTR, HF::Common::FAIL_ARG, HF::Core::DeviceInformation::FRIENDLY_NAME_ATTR, from_json(), HF::Protocol::Message::GET_ATTR_PACK_RES, HF::Core::DeviceInformation::HW_VERSION_ATTR, HF::Common::Interface::id, HF::Core::DeviceInformation::INTERFACE_VERSION_ATTR, HF::Protocol::Message::itf, HF::Core::DeviceInformation::LOCATION_ATTR, LOG, HF::Core::DeviceInformation::MANUFACTURE_NAME_ATTR, HF::Protocol::Packet::message, HF::Core::DeviceInformation::MIN_SLEEP_TIME_ATTR, NL, HF::Common::OK, HF::Core::DeviceInformation::PROFILE_VERSION_ATTR, HF::Protocol::response(), HF::Core::DeviceInformation::SERIAL_NUMBER_ATTR, HF::Core::BindManagement::Entry::source, HF::Interfaces::Alert::Message::state, HF::Interfaces::Alert::Message::type, HF::Protocol::Message::type, HF::Core::DeviceInformation::UID_ATTR, HF::Protocol::GetAttributePack::Response::unpack(), and UNUSED.
 {
    LOG(INFO) << "Restoring binding entries ..." << NL;
    for (unsigned i = 0; i < root.size(); i++)
    {
       HF::Core::BindManagement::Entry entry;
       from_json(root[i], entry);
       entries().insert(entry);
       LOG(TRACE) << "Bind Add : " << entry.source.device
                  << " -> " << entry.destination.device << NL;
    }
 }
void DeviceManagement::Server::save (Json::Value & root)
Save the device entries into the JSON database.
Parameters
[in] root database root to start saving the entries.
Definition at line 159 of file base.cpp.
References HF::Core::DeviceManagement::Entries::begin(), HF::Core::DeviceManagement::Entries::end(), LOG, NL, and to_json().
 {
    LOG(INFO) << "Saving registration entries ..." << NL;
    unsigned i = 0;
    /* *INDENT-OFF* */
    for_each( entries ().begin (), entries ().end (),
              [&root, &i](HF::Core::DeviceManagement::Device &device)
    {
       to_json (device, root[i]);
       i++;
    });
    /* *INDENT-ON* */
 }
void BindManagement::Server::save (Json::Value & root)
Save the bind entries into the JSON database.
Parameters
[in] root database root to start saving the entries.
Definition at line 246 of file base.cpp.
References HF::Core::DeviceManagement::Entries::begin(), HF::Core::DeviceManagement::Entries::end(), LOG, NL, and to_json().
 {
    LOG(INFO) << "Saving binding entries ..." << NL;
    unsigned i = 0;
    /* *INDENT-OFF* */
    for_each(entries().begin(), entries().end(),
             [&root, &i](const HF::Core::BindManagement::Entry &entry)
             {
                to_json (entry, root[i]);
                i++;
             });
    /* *INDENT-ON* */
 }
void HF::Application::Link::send (HF::Common::ByteArray & array) virtual
Send the data in the given ByteArray using the link to the remote end-point.
Parameters
[in] array reference to the ByteArray containing the data to send.
Implements HF::Transport::Link.
Definition at line 588 of file transport.cpp.
References msg_t::data, DATA_MSG, LOG, and NL.
 {
    LOG(TRACE) << __PRETTY_FUNCTION__ << NL;
    msg_t msg(DATA_MSG);
    msg.data = array;
    send_message((uv_stream_t *) stream, msg);
 }
void to_json (HF::UID::UID * uid, Json::Value & node)
Serialize a HF::UID::UID pointer to the given Json::Value.
Parameters
[in] uid pointer to the HF::UID::UID to serialize to JSON.
[out] node reference to the Json::Value to place the serialization result in.
void to_json (const HF::Common::Interface & interface, Json::Value & node)
Serialize a HF::Common::Interface to the given Json::Value.
Parameters
[in] interface reference to the HF::Common::Interface to serialize to JSON.
[out] node reference to the Json::Value to place the serialization result in.
Definition at line 698 of file base.cpp.
References HF::UID::DECT_UID, HF::Common::Interface::id, HF::UID::ByteArray< DECT, 5, DECT_UID >::length(), HF::UID::MAC_UID, HF::UID::NONE_UID, HF::UID::UID::raw(), HF::Common::Interface::role, HF::Interface::SERVER_ROLE, HF::UID::UID::type(), and HF::UID::URI_UID.
Referenced by DeviceManagement::Server::save(), BindManagement::Server::save(), and to_json().
 {
    if (interface.role == HF::Interface::SERVER_ROLE)
    {
       node["role"] = "server";
    }
    else
    {
       node["role"] = "client";
    }
    node["id"] = json_uid(interface.id);
 }
void to_json (const HF::Core::DeviceManagement::Unit & unit, Json::Value & node)
Serialize a HF::Core::DeviceManagement::Unit to the given Json::Value.
Parameters
[in] unit reference to the HF::Core::DeviceManagement::Unit to serialize to JSON.
[out] node reference to the Json::Value to place the serialization result in.
Definition at line 773 of file base.cpp.
References HF::Core::DeviceManagement::Unit::id, HF::Core::DeviceManagement::Unit::interfaces, HF::Core::DeviceManagement::Unit::profile, and to_json().
 {
    node["id"]      = unit.id;
    node["profile"] = json_uid(unit.profile);
    for (unsigned i = 0; i < unit.interfaces.size(); i++)
    {
       to_json(unit.interfaces[i], node["opts"][i]);
    }
 }
void to_json (const HF::Core::DeviceManagement::Device & device, Json::Value & node)
Serialize a HF::Core::DeviceManagement::Device to the given Json::Value.
Parameters
[in] device reference to the HF::Core::DeviceManagement::Device to serialize to JSON.
[out] node reference to the Json::Value to place the serialization result in.
Definition at line 792 of file base.cpp.
References HF::Core::DeviceManagement::Device::address, HF::Core::DeviceManagement::Device::emc, to_json(), HF::Core::DeviceManagement::Device::uid, and HF::Core::DeviceManagement::Device::units.
 {
    node["address"] = device.address;
    for (unsigned i = 0; i < device.units.size(); i++)
    {
       to_json(device.units[i], node["units"][i]);
    }
    node["emc"] = json_uid(device.emc);
    to_json(device.uid, node["uid"]);
 }
void to_json (const HF::Protocol::Address & address, Json::Value & node)
Serialize a HF::Protocol::Address to the given Json::Value.
Parameters
[in] address reference to the HF::Protocol::Address to serialize to JSON.
[out] node reference to the Json::Value to place the serialization result in.
Definition at line 813 of file base.cpp.
References HF::Protocol::Address::device, HF::Protocol::Address::mod, and HF::Protocol::Address::unit.
 {
    node["mod"]    = (int) address.mod;
    node["device"] = (int) address.device;
    node["unit"]   = (int) address.unit;
 }
void to_json (const HF::Core::BindManagement::Entry & entry, Json::Value & node)
Serialize a HF::Core::BindManagement::Entry to the given Json::Value.
Parameters
[in] entry reference to the HF::Core::BindManagement::Entry to serialize to JSON.
[out] node reference to the Json::Value to place the serialization result in.
Definition at line 827 of file base.cpp.
References HF::Core::BindManagement::Entry::destination, HF::Core::BindManagement::Entry::itf, HF::Core::BindManagement::Entry::source, and to_json().
 {
    to_json(entry.source, node["src"]);
    to_json(entry.destination, node["dst"]);
    to_json(entry.itf, node["itf"]);
 }
void SimpleLight::toggle (HF::Protocol::Address & source) virtual
Callback that is called when a TOGGLE_CMD message is received.
Parameters
[in] source device address that sent the command.
Reimplemented from HF::Interfaces::OnOff::Server.
Definition at line 72 of file node.cpp.
References LOG, NL, and SimpleLight::toggle().
Referenced by SimpleLight::toggle().
 {
    HF::Units::Unit<HF::Profiles::SimpleLight>::toggle(source);
    LOG(INFO) << ">>>>>>>>>>>>> SimpleLight : TOGGLE <<<<<<<<<<<<<" << NL;
 }
bool Base::unbind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Remove the binding entry for the given devices.
If the bind does not exist, nothing changes.
Parameters
[in] dev_addr_1 HAN-FUN address of the first device.
[in] dev_addr_2 HAN-FUN address of the second device.
Return values
true if the bind entry was found and removed,
false otherwise.
Definition at line 663 of file base.cpp.
References HF::Common::OK, HF::Interface::ON_OFF, HF::Interface::SERVER_ROLE, and STRTOL_HEX.
Referenced by COMMAND().
 {
    HF::Protocol::Address source(dev_addr_1, 1);
    HF::Common::Interface itf(HF::Interface::ON_OFF, HF::Interface::SERVER_ROLE);
    HF::Protocol::Address destination(dev_addr_2, 1);
    return _unit0.bind_management()->remove(source, destination, itf) == HF::Common::Result::OK;
 }