HAN-FUN API: Simple Temperature
Simple Temperature
Interfaces
This module contains the classes that define and implement the Simple Temperature interface API.
Data Structures
struct HF::Interfaces::SimpleTemperature::Temperature
Helper class to handle the Measured Temperature attribute for the Simple Temperature interface.
struct HF::Interfaces::SimpleTemperature::MininumTemperature
Helper class to handle the Minimum Measured Temperature attribute for the Simple Temperature interface.
struct HF::Interfaces::SimpleTemperature::MaximumTemperature
Helper class to handle the Maximum Measured Temperature attribute for the Simple Temperature interface.
struct HF::Interfaces::SimpleTemperature::Tolerance
Helper class to handle the Tolerance attribute for the Simple Temperature interface.
struct HF::Interfaces::SimpleTemperature::Base
Simple Temperature Interface : Parent.
class HF::Interfaces::SimpleTemperature::Server
Simple Temperature Interface : Server side interface.
class HF::Interfaces::SimpleTemperature::Client
Level Control Interface : Client side implementation.
Enumerations
Functions
HF::Attributes::IAttribute * HF::Interfaces::create_attribute (SimpleTemperature::Server *server, uint8_t uid)
Create an attribute object that can hold the attribute with the given uid.
HF::Attributes::IAttribute * HF::Interfaces::SimpleTemperature::create_attribute (uint8_t uid)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimpleTemperature::Server *,uint8_t)
Detailed Description
This module contains the classes that define and implement the Simple Temperature interface API.
Enumeration Type Documentation
enum HF::Interfaces::SimpleTemperature::Attributes
Attributes.
Enumerator
VALUE_ATTR
Measured temperature attribute UID.
MINIMUM_ATTR
Minimum measured temperature attribute UID.
MAXIMUM_ATTR
Maximum measured temperature attribute UID.
TOLERANCE_ATTR
Tolerance attribute UID.
Definition at line 63 of file simple_temperature.h.
          {
             VALUE_ATTR     = 0x01,
             MINIMUM_ATTR   = 0x02,
             MAXIMUM_ATTR   = 0x03,
             TOLERANCE_ATTR = 0x04,
             __LAST_ATTR__  = TOLERANCE_ATTR,
          } Attributes;
Function Documentation
HF::Attributes::IAttribute* HF::Interfaces::create_attribute (SimpleTemperature::Server * server, uint8_t uid)
Create an attribute object that can hold the attribute with the given uid.
If server is not equal to nullptr then initialize it with the current value.
Parameters
[in] server pointer to the object to read the current value from.
[in] uid attribute's UID to create the attribute object for.
Returns
pointer to an attribute object or nullptr if the attribute UID does not exist.
HF::Attributes::IAttribute* HF::Interfaces::SimpleTemperature::create_attribute (uint8_t uid) inline
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimpleTemperature::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimpleVisualEffects::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimpleThermostat::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimplePowerMeter::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimpleLightSensor::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimpleKeypad::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimpleButton::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SimpleAirPressure::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::OnOff::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::LevelControl::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::ColourControl::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::Alert::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::Scheduling::Weekly::IServer *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::Time::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::SUOTA::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Interfaces::RSSI::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::GroupTable::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid.
Create an attribute object that can hold the attribute with the given uid. (HF::Core::Scheduling::Event::IServer *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceManagement::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceInformation::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::BindManagement::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::BatchProgramManagement::IServer *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::AttributeReporting::Server *,uint8_t)
See also
HF::Interfaces::create_attribute (HF::Interfaces::SimpleTemperature::Server *,uint8_t)
Parameters
[in] uid attribute UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
Definition at line 137 of file simple_temperature.h.
References HF::Interfaces::create_attribute().
Referenced by HF::Core::AttributeReporting::Report::Event::AddEntryMessage::entry_size(), BindManagement::Server::restore(), HF::Interfaces::SimpleKeypad::KeyPressed::size(), HF::Core::SUOTA::UpgradeStatus::unpack(), and HF::Interfaces::SimpleVisualEffects::BreatheEffect::unpack().
          {
             return Interfaces::create_attribute(static_cast<SimpleTemperature::Server *>(nullptr),
                                                 uid);
          }