HAN-FUN API: Device Information
Device Information
Core Services & Interfaces
This module contains the classes that implement the Device Information service.
Data Structures
struct HF::Core::DeviceInformation::FriendlyName
Data type to contain the Friendly name attribute.
class HF::Core::DeviceInformation::Base
Parent class for the Device Information interface implementation.
struct HF::Core::DeviceInformation::Server
Device Information interface : Server side.
Typedefs
typedef Base HF::Core::DeviceInformation::Abstract
Parent class for the Device Information interface implementation.
Enumerations
Functions
HF::Attributes::IAttribute * HF::Core::create_attribute (HF::Core::DeviceInformation::Server *server, uint8_t uid)
Create an attribute object that can hold the attribute with the given uid.
HF::Attributes::IAttribute * HF::Core::DeviceInformation::create_attribute (uint8_t uid)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceInformation::Server *,uint8_t)
Protocol::Message * HF::Core::DeviceInformation::mandatory ()
Create a message that can be used to retrieve the mandatory attributes on a remote device.
Protocol::Message * HF::Core::DeviceInformation::all ()
Create a message that can be used to retrieve all the attributes on a remote device.
Protocol::Message * HF::Core::DeviceInformation::get (HF::Attributes::UIDS &uids)
Create a message that can be used to retrieve the attributes with the given uids of the device information interface on a remote device.
Protocol::Message * HF::Core::DeviceInformation::get (uint8_t uid)
Create a message that can be used to retrieve the attribute with the given uid.
std::ostream & operator<< (std::ostream &stream, const HF::Core::DeviceInformation::Attributes attribute)
Convert the given attribute into a string and write it to the given stream.
Detailed Description
This module contains the classes that implement the Device Information service.
Typedef Documentation
typedef Base HF::Core::DeviceInformation::Abstract
Parent class for the Device Information interface implementation.
Deprecated:
This class is deprecated please use HF::Core::DeviceInformation::Base instead.
Definition at line 231 of file device_information.h.
Enumeration Type Documentation
enum HF::Core::DeviceInformation::Attributes
Attributes.
Enumerator
CORE_VERSION_ATTR
HF Core version attribute.
(M)
PROFILE_VERSION_ATTR
HF Profile version attribute.
(M)
INTERFACE_VERSION_ATTR
HF Interface version attribute.
(M)
EXTRA_CAP_ATTR
Extra capabilities attribute.
(M)
MIN_SLEEP_TIME_ATTR
Minimum sleep time attribute.
(O)
ACTUAL_RESP_TIME_ATTR
Actual response time attribute.
(O)
APP_VERSION_ATTR
Hardware version attribute.
(O)
HW_VERSION_ATTR
Hardware version attribute.
(O)
EMC_ATTR
Electronic Manufacture Code attribute.
(O)
DECT_ID_ATTR
RFPI / IPUI (0)
MANUFACTURER_NAME_ATTR
Manufacture's name attribute.
(O)
LOCATION_ATTR
Location attribute.
(O)
ENABLED_ATTR
Device enabled attribute.
(O)
FRIENDLY_NAME_ATTR
Device friendly name attribute.
(O)
UID_ATTR
Device UID attribute.
(O)
SERIAL_NUMBER_ATTR
Serial number attribute.
(O)
MANUFACTURE_NAME_ATTR
Deprecated:
Definition at line 123 of file device_information.h.
          {
             CORE_VERSION_ATTR      = 0x01,
             PROFILE_VERSION_ATTR   = 0x02,
             INTERFACE_VERSION_ATTR = 0x03,
             EXTRA_CAP_ATTR         = 0x04,
             MIN_SLEEP_TIME_ATTR    = 0x05,
             ACTUAL_RESP_TIME_ATTR  = 0x06,
             APP_VERSION_ATTR       = 0x07,
             HW_VERSION_ATTR        = 0x08,
             EMC_ATTR               = 0x09,
             DECT_ID_ATTR           = 0x0A,
             MANUFACTURER_NAME_ATTR = 0x0B,
             LOCATION_ATTR          = 0x0C,
             ENABLED_ATTR           = 0x0D,
             FRIENDLY_NAME_ATTR     = 0x0E,
             UID_ATTR               = 0x0F,
             SERIAL_NUMBER_ATTR     = 0x10,
             __LAST_ATTR__          = SERIAL_NUMBER_ATTR,
             MANUFACTURE_NAME_ATTR  = MANUFACTURER_NAME_ATTR,
          } Attributes;
Function Documentation
Protocol::Message* HF::Core::DeviceInformation::all ()
Create a message that can be used to retrieve all the attributes on a remote device.
Returns
pointer to a message to retrieve all the attributes.
Referenced by COMMAND(), and HF::Core::DeviceInformation::Server::Server().
HF::Attributes::IAttribute* HF::Core::create_attribute (HF::Core::DeviceInformation::Server * server, uint8_t uid)
Create an attribute object that can hold the attribute with the given uid.
If server is not equal to nullptr then initialize it with the current value.
Parameters
[in] server pointer to the object to read the current value from.
[in] uid attribute's UID to create the attribute object for.
Returns
pointer to an attribute object or nullptr if the attribute UID does not exist.
HF::Attributes::IAttribute* HF::Core::DeviceInformation::create_attribute (uint8_t uid) inline
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceInformation::Server *,uint8_t)
See also
HF::Core::create_attribute (HF::Core::DeviceInformation::Server *,uint8_t)
Parameters
[in] uid attribute UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceInformation::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::BindManagement::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::AttributeReporting::Server *,uint8_t)
See also
HF::Interfaces::create_attribute (HF::Interfaces::SimpleHumidity::Server *,uint8_t)
Parameters
[in] uid attribute UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
Create an attribute object that can hold the attribute with the given uid. (HF::Core::DeviceInformation::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::BindManagement::Server *,uint8_t)
Create an attribute object that can hold the attribute with the given uid. (HF::Core::AttributeReporting::Server *,uint8_t)
See also
HF::Interfaces::create_attribute (HF::Interfaces::SimpleTemperature::Server *,uint8_t)
Parameters
[in] uid attribute UID to create the attribute object for.
Return values
pointer to an attribute object
<tt>nullptr</tt> if the attribute UID does not exist.
Definition at line 107 of file simple_humidity.h.
Referenced by BindManagement::Server::restore().
          {
             return Interfaces::create_attribute(static_cast<SimpleHumidity::Server *>(nullptr),
                                                 uid);
          }
Protocol::Message* HF::Core::DeviceInformation::get (HF::Attributes::UIDS & uids)
Create a message that can be used to retrieve the attributes with the given uids of the device information interface on a remote device.
Parameters
[in] uids array containing the attribute uids to retrive from the remote device.
Returns
pointer to a message to retrieve the attributes with the given uid's.
Protocol::Message* HF::Core::DeviceInformation::get (uint8_t uid)
Create a message that can be used to retrieve the attribute with the given uid.
Parameters
[in] uid attribute's uid to retrieve.
Returns
pointer to a message to retrieve the attribute with the given uid.
Protocol::Message* HF::Core::DeviceInformation::mandatory ()
Create a message that can be used to retrieve the mandatory attributes on a remote device.
Returns
pointer to a message to retrieve the mandatory attributes.
Referenced by HF::Core::Unit0::attributes(), COMMAND(), and HF::Core::DeviceInformation::Server::Server().
std::ostream& operator<< (std::ostream & stream, const HF::Core::DeviceInformation::Attributes attribute)
Convert the given attribute into a string and write it to the given stream.
Parameters
[in] stream out stream to write the string to.
[in] attribute attribute value to convert to a string.
Returns
stream
Referenced by HF::Core::DeviceInformation::Server::Server().