HAN-FUN API: Packs
Packs
Protocol » Attributes
This module contains the classes used to implement the attribute pack functionality.
Namespaces
HF::Protocol::GetAttributePack
This namespace contains the classes that implement the HF::Message::GET_ATTR_PACK_REQ messages.
HF::Protocol::SetAttributePack
This namespace contains the classes that implement the HF::Message::SET_ATTR_PACK_REQ and HF::Message::SET_ATTR_PACK_RESP_REQ messages.
Enumerations
enum HF::Attributes::Pack { HF::Attributes::MANDATORY = 0x00, HF::Attributes::ALL = 0xFE, HF::Attributes::DYNAMIC = 0xFF }
Attribute Pack Special IDs.
Functions
List HF::Attributes::get (const HF::Interface &itf, uint8_t pack_id, const UIDS &uids)
Get a list with the attributes for the given interface, pack id or the uids passed in.
Detailed Description
This module contains the classes used to implement the attribute pack functionality.
An attribute pack is an identifier that can be use to get/set a number of attributes in block.
Enumeration Type Documentation
Pack
enum HF::Attributes::Pack
Attribute Pack Special IDs.
These IDs when received on a HF::Message::GET_ATTR_PACK_REQ, allow the return of all mandatory/optional attributes, without the need to indicate all the attribute UIDs.
Enumerator
MANDATORY
Return all mandatory attributes for the interface.
ALL
Return all mandatory and optional attributes for the interface.
DYNAMIC
Return the attributes with the given attributes.
Definition at line 839 of file attributes.h.
       {
          MANDATORY = 0x00,
          ALL       = 0xFE,
          DYNAMIC   = 0xFF,
       } Pack;
Function Documentation
get()
List HF::Attributes::get (const HF::Interface & itf, uint8_t pack_id, const UIDS & uids)
Get a list with the attributes for the given interface, pack id or the uids passed in.
Parameters
[in] itf reference to the interface to retrieve the attributes for.
[in] pack_id pack id used to get attributes UIDs for. If HF::Attributes::DYNAMIC, use uids present in uids.
[in] uids array containing the attribute UID's if pack id equals HF::Attributes::DYNAMIC.
Returns
list containing the attributes.
Referenced by HF::Profiles::Profile< SIMPLE_LIGHT_SENSOR, Interfaces::SimpleLightSensor::Server >::attributes(), HF::Profiles::Detector< FLOOD_DETECTOR >::attributes(), and HF::Interfaces::Container< HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... >, Proxy< ITF, HF::Units::Unit< HF::Profiles::SimpleOnOffSwitch, ITF... > >... >::attributes_itf().