HAN-FUN API: Attributes
Attributes
Protocol
This module contains the classes that define and implement the common API for handling attributes.
Modules
Packs
This module contains the classes used to implement the attribute pack functionality.
Data Structures
struct HF::Attributes::IAttribute
Interface/Service Attribute API.
struct HF::Attributes::UIDS
List of attributes UIDs.
class HF::Attributes::AbstractAttribute
Parent class for Attribute API implementation.
struct HF::Attributes::Attribute< T, _Owner, typename >
Helper template class to declare an attribute with the given T type.
struct HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>
Helper template class to declare an attribute with the given T type.
struct HF::Attributes::List
This class has the same behavior has a list, however the list element access methods where overwritten to allow using the attribute UIDs as indexes.
struct HF::Attributes::Response
This class represents the response sent when a Protocol::Message::GET_ATTR_REQ request.
Typedefs
typedef IAttribute *(* HF::Attributes::Factory) (uint8_t)
Attribute factory function type.
typedef Attributes::Factory(* HF::Attributes::FactoryGetter) (Common::Interface)
Function pointer to a function that returns the attribute factory associated with a given interface.
Functions
Factory HF::Attributes::get_factory (Common::Interface itf)
Return the attribute factory associated with the given interface identifier.
Detailed Description
This module contains the classes that define and implement the common API for handling attributes.
Function Documentation
Factory HF::Attributes::get_factory (Common::Interface itf)
Return the attribute factory associated with the given interface identifier.
Warning
This function only returns the factories for the build in interfaces.
Parameters
itf interface identifier.
Returns
the factory associated with the interface, or nullptr if the interface is unknown.
Referenced by HF::Core::AttributeReporting::Report::Entry::Entry(), HF::Core::AttributeReporting::Report::Event::Event(), and HF::Core::AttributeReporting::Report::Periodic::Periodic().