HAN-FUN API: HF::Transport::Group Namespace Reference
HF::Transport::Group Namespace Reference
Devices » Transport Layer API
This namespace contains the API used for managing groups of devices at the transport layer level.
Functions
Common::Result create (Endpoint &ep, uint16_t group)
Create a new group of devices at the transport layer with the given address.
Common::Result add (Endpoint &ep, uint16_t group, uint16_t device)
Add the given device to the given group for the given end-point ep.
void remove (Endpoint &ep, uint16_t group, uint16_t device)
Remove the given device from the given group for the given end-point ep.
void remove (Endpoint &ep, uint16_t group)
Remove the given group of devices at the transport layer.
Detailed Description
This namespace contains the API used for managing groups of devices at the transport layer level.
Function Documentation
Common::Result HF::Transport::Group::add (Endpoint & ep, uint16_t group, uint16_t device)
Add the given device to the given group for the given end-point ep.
Parameters
[in] ep reference to the end-point.
[in] group HF address for the group to add the device for.
[in] device HF address of the device to add to the group.
Returns
Common::Result::OK if the device was added to the group.
Referenced by HF::Application::Link::send().
Common::Result HF::Transport::Group::create (Endpoint & ep, uint16_t group)
Create a new group of devices at the transport layer with the given address.
The new link associated with the group MUST be sent to the given end-point via the Endpoint::connected API.
Parameters
[in] ep reference to the end-point to create the new group for.
[in] group HF address for the new group, i.e. the address for the new link.
Returns
Common::Result::OK if the group was created.
Referenced by HF::Application::Link::send().
void HF::Transport::Group::remove (Endpoint & ep, uint16_t group, uint16_t device)
Remove the given device from the given group for the given end-point ep.
Parameters
[in] ep reference to the end-point.
[in] group HF address for the group to remove the device from.
[in] device HF address of the device to remove from the group.
Referenced by HF::Core::GroupManagement::IGroupTable::IGroupTable(), and HF::Application::Link::send().
void HF::Transport::Group::remove (Endpoint & ep, uint16_t group)
Remove the given group of devices at the transport layer.
The link associated with the group MUST be disconnected from the given end-point via the Endpoint::disconnected API.
Parameters
[in] ep reference to the end-point to remove the group from.
[in] group HF address of the group to remove.