var namespaceHF_1_1Interfaces_1_1ColourControl =
[
    [ "Base", "structHF_1_1Interfaces_1_1ColourControl_1_1Base.html", "structHF_1_1Interfaces_1_1ColourControl_1_1Base" ],
    [ "Client", "structHF_1_1Interfaces_1_1ColourControl_1_1Client.html", "structHF_1_1Interfaces_1_1ColourControl_1_1Client" ],
    [ "ColourTemperature", "structHF_1_1Interfaces_1_1ColourControl_1_1ColourTemperature.html", null ],
    [ "HS_Colour", "structHF_1_1Interfaces_1_1ColourControl_1_1HS__Colour.html", "structHF_1_1Interfaces_1_1ColourControl_1_1HS__Colour" ],
    [ "HS_Transition", "structHF_1_1Interfaces_1_1ColourControl_1_1HS__Transition.html", "structHF_1_1Interfaces_1_1ColourControl_1_1HS__Transition" ],
    [ "Hue_Transition", "structHF_1_1Interfaces_1_1ColourControl_1_1Hue__Transition.html", "structHF_1_1Interfaces_1_1ColourControl_1_1Hue__Transition" ],
    [ "HueAndSaturation", "structHF_1_1Interfaces_1_1ColourControl_1_1HueAndSaturation.html", null ],
    [ "IServer", "classHF_1_1Interfaces_1_1ColourControl_1_1IServer.html", "classHF_1_1Interfaces_1_1ColourControl_1_1IServer" ],
    [ "ITransition", "structHF_1_1Interfaces_1_1ColourControl_1_1ITransition.html", "structHF_1_1Interfaces_1_1ColourControl_1_1ITransition" ],
    [ "Mode", "structHF_1_1Interfaces_1_1ColourControl_1_1Mode.html", null ],
    [ "MoveHueMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveHueMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveHueMessage" ],
    [ "MoveSaturationMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveSaturationMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveSaturationMessage" ],
    [ "MoveToHueMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToHueMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToHueMessage" ],
    [ "MoveToHueSaturationMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToHueSaturationMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToHueSaturationMessage" ],
    [ "MoveToSaturationMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToSaturationMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToSaturationMessage" ],
    [ "MoveToTemperatureMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToTemperatureMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToTemperatureMessage" ],
    [ "MoveToXYMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToXYMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveToXYMessage" ],
    [ "MoveXYMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveXYMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1MoveXYMessage" ],
    [ "Saturation_Transition", "structHF_1_1Interfaces_1_1ColourControl_1_1Saturation__Transition.html", "structHF_1_1Interfaces_1_1ColourControl_1_1Saturation__Transition" ],
    [ "Server", "structHF_1_1Interfaces_1_1ColourControl_1_1Server.html", "structHF_1_1Interfaces_1_1ColourControl_1_1Server" ],
    [ "StepHueMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1StepHueMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1StepHueMessage" ],
    [ "StepSaturationMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1StepSaturationMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1StepSaturationMessage" ],
    [ "StepXYMessage", "structHF_1_1Interfaces_1_1ColourControl_1_1StepXYMessage.html", "structHF_1_1Interfaces_1_1ColourControl_1_1StepXYMessage" ],
    [ "Supported", "structHF_1_1Interfaces_1_1ColourControl_1_1Supported.html", null ],
    [ "Temperature_Transition", "structHF_1_1Interfaces_1_1ColourControl_1_1Temperature__Transition.html", "structHF_1_1Interfaces_1_1ColourControl_1_1Temperature__Transition" ],
    [ "Xy", "structHF_1_1Interfaces_1_1ColourControl_1_1Xy.html", null ],
    [ "XY_Colour", "structHF_1_1Interfaces_1_1ColourControl_1_1XY__Colour.html", "structHF_1_1Interfaces_1_1ColourControl_1_1XY__Colour" ],
    [ "XY_Transition", "structHF_1_1Interfaces_1_1ColourControl_1_1XY__Transition.html", "structHF_1_1Interfaces_1_1ColourControl_1_1XY__Transition" ],
    [ "XY_Transition_Continuous", "structHF_1_1Interfaces_1_1ColourControl_1_1XY__Transition__Continuous.html", "structHF_1_1Interfaces_1_1ColourControl_1_1XY__Transition__Continuous" ]
];