HAN-FUN API: HF::Core::DeviceInformation::Server Struct Reference
HF::Core::DeviceInformation::Server Struct Reference
Core Services & Interfaces » Device Information
Device Information interface : Server side.
#include <device_information.h>
Public Member Functions
Server (HF::Core::Unit0 &unit)
Device UID.
void paging (bool value)
Set extra capabilities attribute paging bit to given value.
bool has_paging () const
Get extra capabilities attribute paging bit.
void broadcast (bool value)
Set extra capabilities attribute broadcast bit to given value.
bool has_broadcast () const
Get extra capabilities attribute broadcast bit.
void capabilities (uint8_t value)
Setter for the extra capabilities attribute.
uint8_t capabilities ()
Getter for the extra capabilities attribute bitmask.
Public Member Functions inherited from HF::Core::ServiceRole< Base, HF::Interface::SERVER_ROLE >
Interface::Role role () const
Return the Interface::Role this interface implements.
Public Member Functions inherited from Base
void receive (HF::Protocol::Packet &packet, HF::Common::ByteArray &payload, uint16_t offset)
Callback to deliver a packet received from the transport layer.
bool has_bind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Check if bind exists.
uint8_t bind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Create a new bind entry.
bool unbind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Remove the binding entry for the given devices.
Public Member Functions inherited from HF::Devices::Concentrator::Abstract< CoreServices >
CoreServices * unit0 () const
Get the unit 0 used by this concentrator device.
Public Member Functions inherited from HF::Devices::Concentrator::AbstractBase
uint16_t address () const
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
void connected (HF::Transport::Link *link)
Callback to report that a new transport link was been created to a remote device.
void disconnected (HF::Transport::Link *link)
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
Public Member Functions inherited from HF::Devices::AbstractDevice
const IUnits & units () const
Return the list of units registered in this device.
void add (Units::IUnit *unit)
Add unit to devices unit lists.
void remove (Units::IUnit *unit)
Remove unit from device's unit list.
Units::IUnit * unit (uint8_t id) const
Return pointer to the unit with the given id.
void send (Protocol::Packet &packet)
Send given packet into the HAN-FUN network.
void periodic (uint32_t time)
Handle periodic processing.
Events
Additional Inherited Members
Protected Member Functions inherited from HF::Core::ServiceRole< Base, HF::Interface::SERVER_ROLE >
ServiceRole (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Devices::Concentrator::AbstractBase
HF::Transport::Link * link (uint16_t addr) const
Return the link that can be used to send a packet to the device with the given address.
virtual void route_packet (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Route the given packet to the corresponding device.
Protected Member Functions inherited from HF::Devices::AbstractDevice
virtual bool is_local (Protocol::Packet &packet)
Check if the given packet is for this device.
bool is_registered ()
Check if the device has a valid, i.e.
Protected Attributes inherited from HF::Devices::Concentrator::AbstractBase
Common::SimpleList< Transport::Link * > _links
List of links present in this concentrator.
Protected Attributes inherited from HF::Devices::AbstractDevice
uint8_t next_reference
Last reference number used to send a packet.
IUnits _units
List containing pointers to the units present in the device.
Protocol::Filters::ResponseRequired response_filter
Support for generating missing responses for messages.
Detailed Description
Device Information interface : Server side.
Definition at line 236 of file device_information.h.
Constructor & Destructor Documentation
HF::Core::DeviceInformation::Server::Server (HF::Core::Unit0 & unit) inline
Device UID.
Constructor.
Parameters
[in] unit reference to the unit containing this service.
Definition at line 245 of file device_information.h.
References HF::Core::DeviceInformation::all(), HF::Core::DeviceInformation::mandatory(), HF::Attributes::MANDATORY, and operator<<().
                                      :
                ServiceRole<Base, HF::Interface::SERVER_ROLE>(unit), _capabilities(0)
             {}
Member Function Documentation
void HF::Core::DeviceInformation::Server::broadcast (bool value)
Set extra capabilities attribute broadcast bit to given value.
Parameters
[in] value broadcast bit value to place in extra capabilities attribute.
void HF::Core::DeviceInformation::Server::capabilities (uint8_t value)
Setter for the extra capabilities attribute.
Parameters
[in] value bitmask value for the extra capabilities attribute.
uint8_t HF::Core::DeviceInformation::Server::capabilities ()
Getter for the extra capabilities attribute bitmask.
Returns
the bitmask value of the extra capabilities attribute.
bool HF::Core::DeviceInformation::Server::has_broadcast () const
Get extra capabilities attribute broadcast bit.
Return values
true the broadcast bit is 1.
false the broadcast bit is 0.
bool HF::Core::DeviceInformation::Server::has_paging () const
Get extra capabilities attribute paging bit.
Return values
true the broadcast bit is 1.
false the broadcast bit is 0.
void HF::Core::DeviceInformation::Server::paging (bool value)
Set extra capabilities attribute paging bit to given value.
Parameters
[in] value paging bit value to place in extra capabilities attribute.
The documentation for this struct was generated from the following file:
device_information.h