HAN-FUN API: HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))> Struct Template Reference
HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))> Struct Template Reference
Protocol » Attributes
Helper template class to declare an attribute with the given T type.
#include <attributes.h>
Public Member Functions
Attribute (_Owner &__owner, const uint8_t uid, getter_t _getter, setter_t _setter, bool writable=false)
Attribute template constructor.
Attribute (_Owner &__owner, const uint8_t uid, getter_t _getter, bool writable=false)
Attribute template constructor.
Attribute (_Owner *__owner, const uint8_t uid, getter_t _getter, setter_t _setter, bool writable=false)
Attribute template constructor.
Attribute (_Owner *__owner, const uint8_t uid, getter_t _getter, bool writable=false)
Attribute template constructor.
HF::Interface const * owner () const
Pointer to the interface that owns this attribute.
uint16_t size (bool with_uid) const
Number bytes needed to serialize the message.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset, bool with_uid) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset, bool with_uid)
Read a message from a ByteArray.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
IAttribute * clone () const
Create a clone object of the object where this method is being called.
int compare (const IAttribute &other) const
Compare this attribute with the given attribute in other.
float changed (const IAttribute &other) const
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Public Member Functions inherited from HF::Attributes::AbstractAttribute
uint8_t uid () const
Attribute's UID.
bool isWritable () const
Indicate if the attribute is writable.
uint16_t interface () const
Return the UID of the interface the attribute belongs to.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from HF::Attributes::AbstractAttribute
const uint16_t _itf_uid
Interface this attribute belongs to.
const uint8_t _uid
Attribute unique identifier.
const bool _writable
Attribute access mode.
Detailed Description
template<typename T, typename _Owner>
struct HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>
Helper template class to declare an attribute with the given T type.
Template Parameters
T underling data type for the attribute.
_Owwer underling data type for the attribute's owner.
Definition at line 528 of file attributes.h.
Constructor & Destructor Documentation
Attribute() [1/4]
template<typename T , typename _Owner > HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::Attribute (_Owner & __owner, const uint8_t uid, getter_t _getter, setter_t _setter, bool writable = false) inline
Attribute template constructor.
Parameters
[in] __owner reference to attribute's interface owner object.
[in] uid attribute's UID.
[in] _getter owner's member function to get the value of the attribute.
[in] _setter owner's member function to set the value of the attribute.
[in] writable attribute's writable information.
Definition at line 545 of file attributes.h.
                                          :
             AbstractAttribute(__owner.uid(), uid, writable), _owner(&__owner), getter(_getter),
             setter(_setter)
          {}
Attribute() [2/4]
template<typename T , typename _Owner > HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::Attribute (_Owner & __owner, const uint8_t uid, getter_t _getter, bool writable = false) inline
Attribute template constructor.
Parameters
[in] __owner reference to attribute's interface owner object.
[in] uid attribute's UID.
[in] _getter owner's member function to get the value of the attribute.
[in] writable attribute's writable information.
Definition at line 559 of file attributes.h.
                                                                                                :
             AbstractAttribute(__owner.uid(), uid, writable), _owner(&__owner), getter(_getter)
          {}
Attribute() [3/4]
template<typename T , typename _Owner > HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::Attribute (_Owner * __owner, const uint8_t uid, getter_t _getter, setter_t _setter, bool writable = false) inline
Attribute template constructor.
Parameters
[in] __owner reference to attribute's interface owner object.
[in] uid attribute's UID.
[in] _getter owner's member function to get the value of the attribute.
[in] _setter owner's member function to set the value of the attribute.
[in] writable attribute's writable information.
Definition at line 573 of file attributes.h.
                                          :
             AbstractAttribute(__owner->uid(), uid, writable), _owner(__owner), getter(_getter),
             setter(_setter)
          {}
Attribute() [4/4]
template<typename T , typename _Owner > HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::Attribute (_Owner * __owner, const uint8_t uid, getter_t _getter, bool writable = false) inline
Attribute template constructor.
Parameters
[in] __owner reference to attribute's interface owner object.
[in] uid attribute's UID.
[in] _getter owner's member function to get the value of the attribute.
[in] writable attribute's writable information.
Definition at line 588 of file attributes.h.
                                                                                                :
             AbstractAttribute(__owner->uid(), uid, writable), _owner(__owner), getter(_getter)
          {}
Member Function Documentation
changed()
template<typename T , typename _Owner > float HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::changed (const IAttribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))> & other) const inline virtual
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Parameters
[in] other attribute holding a previous value.
Returns
float indicating the percentage of change.
Implements HF::Attributes::IAttribute.
Definition at line 717 of file attributes.h.
References HF::Attributes::AbstractAttribute::compare().
          {
             int res = AbstractAttribute::compare(other);
             if (res == 0)
             {
                Common::SerializableHelper<value_type> lhs(value());
                Common::SerializableHelper<value_type> rhs(((Attribute<T> *) & other)->value());
                return lhs.changed(rhs);
             }
             return 0.0;
          }
clone()
template<typename T , typename _Owner > IAttribute* HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::clone () const inline virtual
Create a clone object of the object where this method is being called.
Returns
a new object that is a clone of this object.
Implements HF::Common::Cloneable< IAttribute >.
Definition at line 695 of file attributes.h.
References HF::Attributes::AbstractAttribute::isWritable(), and HF::Attributes::AbstractAttribute::uid().
          {
             return new HF::Attributes::Attribute<T, _Owner>(this->_owner, this->uid(),
                                                             this->getter, this->setter,
                                                             this->isWritable());
          }
compare()
template<typename T , typename _Owner > int HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::compare (const IAttribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))> & other) const inline virtual
Compare this attribute with the given attribute in other.
This method should return < 0 if this attribute is less that, 0 if it is equal and > 0 if greater that the other attribute.
Parameters
[in] other attribute to compare to.
Return values
<0 if attribute less than other;
0 if attribute equal to other;
>0 if attribute greater than other.
Reimplemented from HF::Attributes::AbstractAttribute.
Definition at line 702 of file attributes.h.
References HF::Attributes::AbstractAttribute::compare().
          {
             int res = AbstractAttribute::compare(other);
             if (res == 0)
             {
                Common::SerializableHelper<value_type> lhs(value());
                Common::SerializableHelper<value_type> rhs(((Attribute<T> *) & other)->value());
                res = lhs.compare(rhs);
             }
             return res;
          }
owner()
template<typename T , typename _Owner > HF::Interface const* HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::owner () const inline virtual
Pointer to the interface that owns this attribute.
This can return nullptr if the attribute was created for a remote interface.
Returns
pointer to the interface that owns this attribute, or nullptr if owner is a remote object.
Implements HF::Attributes::IAttribute.
Definition at line 619 of file attributes.h.
          {
             return _owner;
          }
pack() [1/2]
template<typename T , typename _Owner > uint16_t HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::pack (Common::ByteArray & array, uint16_t offset, bool with_uid) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
[in] with_uid include uid field in the serialization.
Returns
the number of bytes written.
Implements HF::Attributes::IAttribute.
Definition at line 635 of file attributes.h.
References HF_SERIALIZABLE_CHECK, HF::Common::SerializableHelper< T, typename >::pack(), HF::Attributes::Attribute< T, _Owner, typename >::size(), HF::Attributes::AbstractAttribute::uid(), and HF::Common::ByteArray::write().
          {
             HF_SERIALIZABLE_CHECK(array, offset, size(with_uid));
             uint16_t start = offset;
             if (with_uid)
             {
                offset += array.write(offset, uid());
             }
             Common::SerializableHelper<value_type> helper(value());
             offset += helper.pack(array, offset);
             return offset - start;
          }
pack() [2/2]
template<typename T , typename _Owner > uint16_t HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::pack (Common::ByteArray & array, uint16_t offset = 0) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Implements HF::Common::Serializable.
Definition at line 653 of file attributes.h.
References HF::Common::SerializableHelper< T, typename >::pack().
          {
             Common::SerializableHelper<value_type> helper(value());
             return helper.pack(array, offset);
          }
size() [1/2]
template<typename T , typename _Owner > uint16_t HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::size (bool with_uid) const inline virtual
Number bytes needed to serialize the message.
Parameters
[in] with_uid include uid size in the calculation.
Returns
number of bytes the message requires to be serialized.
Implements HF::Attributes::IAttribute.
Definition at line 624 of file attributes.h.
References HF::Attributes::Attribute< T, _Owner, typename >::size().
          {
             return size() + (with_uid ? sizeof(uint8_t) : 0);
          }
size() [2/2]
template<typename T , typename _Owner > uint16_t HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::size () const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Implements HF::Common::Serializable.
Definition at line 629 of file attributes.h.
References HF::Common::SerializableHelper< T, typename >::size().
          {
             Common::SerializableHelper<value_type> helper(value());
             return helper.size();
          }
unpack() [1/2]
template<typename T , typename _Owner > uint16_t HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::unpack (const Common::ByteArray & array, uint16_t offset, bool with_uid) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
[in] with_uid true if the uid field was included in the serialization, false otherwise.
Returns
the number of bytes read.
Implements HF::Attributes::IAttribute.
Definition at line 660 of file attributes.h.
References HF::Common::SerializableHelper< T, typename >::data, HF_SERIALIZABLE_CHECK, HF::Common::ByteArray::read(), HF::Attributes::Attribute< T, _Owner, typename >::size(), HF::Attributes::AbstractAttribute::uid(), and HF::Common::SerializableHelper< T, typename >::unpack().
          {
             HF_SERIALIZABLE_CHECK(array, offset, size(with_uid));
             Common::SerializableHelper<value_type> helper;
             uint16_t start = offset;
             if (with_uid)
             {
                uint8_t temp;
                offset += array.read(offset, temp);
                if (temp != uid())
                {
                   goto _end;
                }
             }
             offset += helper.unpack(array, offset);
             setter(*_owner, helper.data);
             _end:
             return offset - start;
          }
unpack() [2/2]
template<typename T , typename _Owner > uint16_t HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Implements HF::Common::Serializable.
Definition at line 686 of file attributes.h.
References HF::Common::SerializableHelper< T, typename >::data, and HF::Common::SerializableHelper< T, typename >::unpack().
          {
             Common::SerializableHelper<value_type> helper;
             uint16_t result = helper.unpack(array, offset);
             setter(*_owner, helper.data);
             return result;
          }
The documentation for this struct was generated from the following file:
attributes.h