HAN-FUN API: HF::Core::Scheduling::GetEntryResponse< _Type > Struct Template Reference
HF::Core::Scheduling::GetEntryResponse< _Type > Struct Template Reference
Core Services & Interfaces » Scheduling Services (Common)
Response message payload for a Scheduling::GET_ENTRY_CMD request.
#include <scheduling.h>
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Public Member Functions inherited from HF::Protocol::Response
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
Entry< _Type > entry
&Entry data to return to client.
Additional Inherited Members
Static Public Attributes inherited from HF::Protocol::Response
static constexpr uint16_t min_size = sizeof(uint8_t)
Minimum number of bytes required by this message.
Detailed Description
template<typename _Type>
struct HF::Core::Scheduling::GetEntryResponse< _Type >
Response message payload for a Scheduling::GET_ENTRY_CMD request.
Template Parameters
_Type the specific data for scheduling service entry.
Definition at line 400 of file scheduling.h.
Member Function Documentation
pack()
template<typename _Type > uint16_t HF::Core::Scheduling::GetEntryResponse< _Type >::pack (Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 425 of file scheduling.h.
References HF::Core::Scheduling::GetEntryResponse< _Type >::entry, HF_SERIALIZABLE_CHECK, HF::Common::OK, HF::Protocol::Response::pack(), and HF::Core::Scheduling::GetEntryResponse< _Type >::size().
             {
                HF_SERIALIZABLE_CHECK(array, offset, size());
                uint8_t start = offset;
                offset += Protocol::Response::pack(array, offset);
                if (code != Common::Result::OK)
                {
                   goto _end;
                }
                offset += entry.pack(array, offset);
                _end:
                return offset - start;
             }
size()
template<typename _Type > uint16_t HF::Core::Scheduling::GetEntryResponse< _Type >::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 414 of file scheduling.h.
References HF::Protocol::Response::min_size, and HF::Common::OK.
Referenced by HF::Core::Scheduling::GetEntryResponse< _Type >::pack().
             {
                if (code != Common::Result::OK)
                {
                   return min_size;
                }
                return min_size + Entry<_Type>::min_size;
             }
unpack()
template<typename _Type > uint16_t HF::Core::Scheduling::GetEntryResponse< _Type >::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 445 of file scheduling.h.
References HF::Core::Scheduling::GetEntryResponse< _Type >::entry, HF_SERIALIZABLE_CHECK, HF::Protocol::Response::min_size, HF::Common::OK, and HF::Protocol::Response::unpack().
             {
                HF_SERIALIZABLE_CHECK(array, offset, min_size);
                uint8_t start = offset;
                offset += Protocol::Response::unpack(array, offset);
                if (code != Common::Result::OK)
                {
                   goto _end;
                }
                HF_SERIALIZABLE_CHECK(array, offset, entry.size());
                offset += entry.unpack(array, offset);
                _end:
                return offset - start;
             }
Field Documentation
entry
template<typename _Type > Entry<_Type> HF::Core::Scheduling::GetEntryResponse< _Type >::entry
&Entry data to return to client.
Definition at line 402 of file scheduling.h.
Referenced by HF::Core::Scheduling::GetEntryResponse< _Type >::pack(), and HF::Core::Scheduling::GetEntryResponse< _Type >::unpack().
The documentation for this struct was generated from the following file:
scheduling.h