HAN-FUN API: HF::Attributes::IAttribute Struct Reference
HF::Attributes::IAttribute Struct Reference abstract
Protocol » Attributes
Interface/Service Attribute API.
#include <attributes.h>
Public Member Functions
virtual uint8_t uid () const =0
Attribute's UID.
virtual bool isWritable () const =0
Indicate if the attribute is writable.
virtual uint16_t interface () const =0
Return the UID of the interface the attribute belongs to.
virtual HF::Interface const * owner () const =0
Pointer to the interface that owns this attribute.
virtual uint16_t size (bool with_uid) const =0
Number bytes needed to serialize the message.
virtual uint16_t pack (Common::ByteArray &array, uint16_t offset, bool with_uid) const =0
Write the object on to a ByteArray so it can be sent over the network.
virtual uint16_t unpack (const Common::ByteArray &array, uint16_t offset, bool with_uid)=0
Read a message from a ByteArray.
virtual float changed (const IAttribute &other) const =0
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
virtual int compare (const IAttribute &other) const =0
Compare this attribute with the given attribute in other.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
virtual uint16_t size () const =0
Number bytes needed to serialize the message.
virtual uint16_t pack (ByteArray &array, uint16_t offset=0) const =0
Write the object on to a ByteArray so it can be sent over the network.
virtual uint16_t unpack (const ByteArray &array, uint16_t offset=0)=0
Read a message from a ByteArray.
Public Member Functions inherited from HF::Common::Cloneable< IAttribute >
virtual IAttribute * clone () const =0
Create a clone object of the object where this method is being called.
Detailed Description
Interface/Service Attribute API.
Definition at line 44 of file attributes.h.
Member Function Documentation
virtual float HF::Attributes::IAttribute::changed (const IAttribute & other) const pure virtual
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Parameters
[in] other attribute holding a previous value.
Returns
float indicating the percentage of change.
Implemented in HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, and HF::Attributes::Attribute< bool >.
Referenced by HF::Attributes::Attribute< bool >::changed(), and HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::changed().
virtual int HF::Attributes::IAttribute::compare (const IAttribute & other) const pure virtual
Compare this attribute with the given attribute in other.
This method should return < 0 if this attribute is less that, 0 if it is equal and > 0 if greater that the other attribute.
Parameters
[in] other attribute to compare to.
Return values
<0 if attribute less than other;
0 if attribute equal to other;
>0 if attribute greater than other.
Implemented in HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, HF::Attributes::Attribute< bool >, and HF::Attributes::AbstractAttribute.
Referenced by HF::Attributes::Attribute< bool >::compare(), HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::compare(), and HF::Attributes::AbstractAttribute::interface().
virtual uint16_t HF::Attributes::IAttribute::interface () const pure virtual
Return the UID of the interface the attribute belongs to.
Returns
UID of the interface the attribute belongs to.
Implemented in HF::Attributes::AbstractAttribute.
Referenced by HF::Attributes::AbstractAttribute::compare().
virtual bool HF::Attributes::IAttribute::isWritable () const pure virtual
Indicate if the attribute is writable.
Return values
true if the attribute is writable,
false otherwise.
Implemented in HF::Attributes::AbstractAttribute.
Referenced by HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::clone().
virtual HF::Interface const* HF::Attributes::IAttribute::owner () const pure virtual
Pointer to the interface that owns this attribute.
This can return nullptr if the attribute was created for a remote interface.
Returns
pointer to the interface that owns this attribute, or nullptr if owner is a remote object.
Implemented in HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, and HF::Attributes::Attribute< bool >.
virtual uint16_t HF::Attributes::IAttribute::pack (Common::ByteArray & array, uint16_t offset, bool with_uid) const pure virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
[in] with_uid include uid field in the serialization.
Returns
the number of bytes written.
Implemented in HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, and HF::Attributes::Attribute< bool >.
Referenced by HF::Attributes::Response::Response(), and HF::Protocol::SetAttributePack::Response::size().
virtual uint16_t HF::Attributes::IAttribute::size (bool with_uid) const pure virtual
Number bytes needed to serialize the message.
Parameters
[in] with_uid include uid size in the calculation.
Returns
number of bytes the message requires to be serialized.
Implemented in HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, and HF::Attributes::Attribute< bool >.
Referenced by HF::Attributes::Response::Response().
virtual uint8_t HF::Attributes::IAttribute::uid () const pure virtual
Attribute's UID.
Returns
the attribute's UID value.
Implemented in HF::Attributes::AbstractAttribute.
Referenced by HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::clone(), HF::Attributes::AbstractAttribute::compare(), HF::Attributes::Attribute< bool >::pack(), HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::pack(), HF::Attributes::UIDS::unpack(), HF::Attributes::Attribute< bool >::unpack(), and HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::unpack().
virtual uint16_t HF::Attributes::IAttribute::unpack (const Common::ByteArray & array, uint16_t offset, bool with_uid) pure virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
[in] with_uid true if the uid field was included in the serialization, false otherwise.
Returns
the number of bytes read.
Implemented in HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, and HF::Attributes::Attribute< bool >.
Referenced by HF::Attributes::Response::Response(), and HF::Protocol::SetAttributePack::Response::size().
The documentation for this struct was generated from the following file:
attributes.h