HAN-FUN API: HF::Common::SerializableHelper< std::string > Struct Template Reference
HF::Common::SerializableHelper< std::string > Struct Template Reference
Common
Wrapper for std::string implementing the Serializable API.
#include <common.h>
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
int compare (const SerializableHelper< std::string > &other) const
Compare this attribute with the given attribute in other.
float changed (const SerializableHelper< std::string > &other) const
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Static Public Attributes
static constexpr uint16_t min_size = sizeof(uint8_t)
Minimum pack/unpack required data size.
Detailed Description
template<>
struct HF::Common::SerializableHelper< std::string >
Wrapper for std::string implementing the Serializable API.
Definition at line 685 of file common.h.
Member Function Documentation
float HF::Common::SerializableHelper< std::string >::changed (const SerializableHelper< std::string > & other) const inline
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Parameters
[in] other attribute holding a previous value.
Returns
float indicating the percentage of change.
Definition at line 768 of file common.h.
References UNUSED.
          {
             UNUSED(other);
             return 0.0;
          }
int HF::Common::SerializableHelper< std::string >::compare (const SerializableHelper< std::string > & other) const inline
Compare this attribute with the given attribute in other.
This method should return < 0 if this attribute is less that, 0 if it is equal and > 0 if greater that the other attribute.
Parameters
[in] other attribute to compare to.
Return values
<0 if attribute less than other;
0 if attribute equal to other;
>0 if attribute greater than other.
Definition at line 762 of file common.h.
          {
             return strcmp(data.data(), other.data.data());
          }
uint16_t HF::Common::SerializableHelper< std::string >::pack (Common::ByteArray & array, uint16_t offset = 0) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Implements HF::Common::Serializable.
Definition at line 751 of file common.h.
References HF::Common::SerializableHelper< T, typename >::pack().
          {
             return pack(data, array, offset);
          }
uint16_t HF::Common::SerializableHelper< std::string >::size () const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Implements HF::Common::Serializable.
Definition at line 746 of file common.h.
References HF::Common::SerializableHelper< T, typename >::size().
          {
             return size(data);
          }
uint16_t HF::Common::SerializableHelper< std::string >::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Implements HF::Common::Serializable.
Definition at line 756 of file common.h.
References HF::Common::SerializableHelper< T, typename >::unpack().
          {
             return unpack(data, array, offset);
          }
The documentation for this struct was generated from the following file:
inc/hanfun/common.h