HAN-FUN API: HF::Core::SUOTA::Version Struct Reference
HF::Core::SUOTA::Version Struct Reference
Core Services & Interfaces » SUOTA
Helper class that represents the information of a particular version.
#include <suota.h>
Public Member Functions
Version (const std::string _sw_version="", const std::string _hw_version="", const std::string _url="")
Constructor.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
std::string sw_version
Current/Available software version.
std::string hw_version
Current/Minimum required hardware version.
std::string url
Update URL.
Static Public Attributes
static constexpr uint16_t min_size = 2 * sizeof(uint8_t)
Minimum pack/unpack required data size.
Detailed Description
Helper class that represents the information of a particular version.
Definition at line 91 of file suota.h.
Constructor & Destructor Documentation
HF::Core::SUOTA::Version::Version (const std::string _sw_version = "", const std::string _hw_version = "", const std::string _url = "") inline
Constructor.
Parameters
[in] _sw_version software version string.
[in] _hw_version hardware version string.
[in] _url update URL string.
Definition at line 104 of file suota.h.
                                               :
                sw_version(_sw_version), hw_version(_hw_version), url(_url)
             {}
Member Function Documentation
uint16_t HF::Core::SUOTA::Version::pack (Common::ByteArray & array, uint16_t offset = 0) const
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Referenced by HF::Core::SUOTA::CheckVersionResponse::pack().
uint16_t HF::Core::SUOTA::Version::size () const
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Referenced by HF::Core::SUOTA::CheckVersionResponse::size().
uint16_t HF::Core::SUOTA::Version::unpack (const Common::ByteArray & array, uint16_t offset = 0)
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Referenced by HF::Core::SUOTA::CheckVersionResponse::unpack().
Field Documentation
std::string HF::Core::SUOTA::Version::hw_version
Current/Minimum required hardware version.
Definition at line 94 of file suota.h.
std::string HF::Core::SUOTA::Version::sw_version
Current/Available software version.
Definition at line 93 of file suota.h.
std::string HF::Core::SUOTA::Version::url
Update URL.
Definition at line 95 of file suota.h.
The documentation for this struct was generated from the following file:
suota.h