HAN-FUN API: ICommand Struct Reference
ICommand Struct Reference abstract
Examples
Example application menu entry API.
#include <common.h>
Public Member Functions
virtual const std::string & key () const =0
Get the command key.
virtual const std::string usage (bool format=false) const =0
Get the command help documentation.
virtual void run (std::vector< std::string > &args)=0
Execute the command code.
Static Public Member Functions
static void add (ICommand *command)
Add a command to the registry.
static void remove (ICommand *command)
Remove a command to the registry.
static void run (std::string &cmd, std::vector< std::string > &args)
Find and run the command with the given key, using the arguments in args.
static std::ostream & help (std::ostream &stream)
Generate the help screen, based on the commands in the registry.
Static Protected Attributes
static std::map< std::string, ICommand * > registry
Command registry.
Detailed Description
Example application menu entry API.
Definition at line 37 of file apps/common.h.
Member Function Documentation
add()
void ICommand::add (ICommand * command) static
Add a command to the registry.
Parameters
[in] command command to be added to the registry.
Definition at line 47 of file common.cpp.
References key(), and registry.
 {
    registry.insert(std::pair<std::string, ICommand *>(command->key(), command));
 }
help()
std::ostream & ICommand::help (std::ostream & stream) static
Generate the help screen, based on the commands in the registry.
Parameters
[in] stream reference to the stream to print the help screen.
Returns
reference to the stream.
Definition at line 71 of file common.cpp.
References registry.
 {
    struct entry
    {
       std::string cmd;
       std::string help;
    };
    static std::string cache   = "";
    static uint8_t cache_count = 0;
    if (cache_count == ICommand::registry.size())
    {
       _stream << cache;
       return _stream;
    }
    std::stringstream stream;
    uint16_t size = 0;
    std::vector<entry> entries;
    /* *INDENT-OFF* */
    std::for_each (ICommand::registry.begin (), ICommand::registry.end (),
                   [&entries, &size](std::pair <std::string, ICommand *> e)
    {
       // LOG (TRACE) << "E F : " << e.first << NL;
       // LOG (TRACE) << "E S : " << e.second << NL;
       const std::string &raw = e.second->usage ();
       char *temp = new char[raw.size ()+1];
       strncpy (temp, raw.c_str (), raw.size ())[raw.size ()] = 0;
       std::vector <char *> lines;
       char *saveptr = NULL;
       for (char *p = strtok_r (temp, "\n", &saveptr); p != NULL; p = strtok_r (NULL, "\n", &saveptr))
       {
          lines.push_back (p);
       }
       std::for_each (lines.begin (), lines.end (), [&entries, &size](char *line)
       {
          entry e;
          char *saveptr = NULL;
          char *p = strtok_r (line, ":", &saveptr);
          e.cmd = std::string (p);
          p = strtok_r (NULL, ":", &saveptr);
          e.help = std::string (p);
          entries.push_back (e);
          if (size < e.cmd.size ())
          {
             size = e.cmd.size ();
          }
       });
       delete[] temp;
    });
    /* *INDENT-ON* */
    size++;
    stream << std::endl;
    stream << "================================================" << std::endl;
    stream << "HAN-FUN Example Application : v" << HF_VERSION << std::endl;
    stream << "================================================" << std::endl << std::endl;
    stream << std::setfill(' ');
    /* *INDENT-OFF* */
    std::for_each (entries.begin (), entries.end (), [&stream, size](entry &e)
    {
       stream << std::left << std::setw (size) << e.cmd << "\t: " << e.help << std::endl;
    });
    /* *INDENT-ON* */
    stream << std::left << std::setw(size) << "h/?" << "\t: " << "this help menu."
           << std::endl << std::endl;
    stream << "Select an Option (Q/q to exit): " << std::endl;
    cache = stream.str();
    _stream << cache;
    return _stream;
 }
key()
virtual const std::string& ICommand::key () const pure virtual
Get the command key.
Returns
the string that represents the command key.
Implemented in Command.
Referenced by add(), remove(), and run().
remove()
void ICommand::remove (ICommand * command) static
Remove a command to the registry.
Parameters
[in] command command to be removed from the registry.
Definition at line 59 of file common.cpp.
References key(), and registry.
 {
    registry.erase(command->key());
 }
run() [1/2]
virtual void ICommand::run (std::vector< std::string > & args) pure virtual
Execute the command code.
Parameters
[in] args the arguments passed to the code.
run() [2/2]
void ICommand::run (std::string & cmd, std::vector< std::string > & args) static
Find and run the command with the given key, using the arguments in args.
Parameters
[in] cmd the key for the command to be run.
[in] args vector containing the arguments to call the command with.
Definition at line 171 of file common.cpp.
References key(), LOG, and registry.
 {
    auto it = registry.find(key);
    if (it == registry.end())
    {
       LOG(ERROR) << "Command '" << key << "' not found !" << NL;
       ICommand::help(std::cout);
    }
    else
    {
       it->second->run(args);
    }
 }
usage()
virtual const std::string ICommand::usage (bool format = false) const pure virtual
Get the command help documentation.
Parameters
[in] format if true the usage string SHOULD be formatted to be displayed to the user.
Returns
command help documentation.
Implemented in Command.
The documentation for this struct was generated from the following files:
apps/common.h
common.cpp