HAN-FUN API: HF::Core::DeviceManagement::IServer Struct Reference
HF::Core::DeviceManagement::IServer Struct Reference abstract
Core Services & Interfaces » Device Management
Device Management interface : Server side API.
#include <device_management.h>
Public Member Functions
HF::Devices::Concentrator::IUnit0 & unit0 () const
Return a reference to the unit that this service belongs to.
DevicePtr entry (uint16_t address) const
Return the Device entry for the given address.
DevicePtr entry (const HF::UID::UID &uid) const
Return the Device entry for the given UID.
virtual IEntries & entries () const =0
Get a reference to the current object implementing the persistence API, for the device information.
virtual SessionManagement::IServer & sessions ()=0
Reference to the session management API.
virtual uint16_t next_address ()
Return next available address for registering a device.
Events
virtual void registered (DevicePtr &device)
Indicate that a device has been registered.
virtual void deregistered (DevicePtr &device)
Indicate that a device has been de-registered.
Public Member Functions inherited from HF::Core::ServiceRole< Base, HF::Interface::SERVER_ROLE >
Interface::Role role () const
Return the Interface::Role this interface implements.
Public Member Functions inherited from Base
void receive (HF::Protocol::Packet &packet, HF::Common::ByteArray &payload, uint16_t offset)
Callback to deliver a packet received from the transport layer.
bool has_bind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Check if bind exists.
uint8_t bind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Create a new bind entry.
bool unbind (uint16_t dev_addr_1, uint16_t dev_addr_2)
Remove the binding entry for the given devices.
Public Member Functions inherited from HF::Devices::Concentrator::Abstract< CoreServices >
CoreServices * unit0 () const
Get the unit 0 used by this concentrator device.
Public Member Functions inherited from HF::Devices::Concentrator::AbstractBase
uint16_t address () const
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
void connected (HF::Transport::Link *link)
Callback to report that a new transport link was been created to a remote device.
void disconnected (HF::Transport::Link *link)
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
Public Member Functions inherited from HF::Devices::AbstractDevice
const IUnits & units () const
Return the list of units registered in this device.
void add (Units::IUnit *unit)
Add unit to devices unit lists.
void remove (Units::IUnit *unit)
Remove unit from device's unit list.
Units::IUnit * unit (uint8_t id) const
Return pointer to the unit with the given id.
void send (Protocol::Packet &packet)
Send given packet into the HAN-FUN network.
void periodic (uint32_t time)
Handle periodic processing.
Events
Protected Member Functions
IServer (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Core::ServiceRole< Base, HF::Interface::SERVER_ROLE >
ServiceRole (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Devices::Concentrator::AbstractBase
HF::Transport::Link * link (uint16_t addr) const
Return the link that can be used to send a packet to the device with the given address.
virtual void route_packet (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Route the given packet to the corresponding device.
Protected Member Functions inherited from HF::Devices::AbstractDevice
virtual bool to_local (const Protocol::Packet &packet) const
Check if the given packet is for this device.
bool from_local (const Protocol::Packet &packet) const
Check if the given packet is from the local device.
bool from_remote (const Protocol::Packet &packet)
Check if the given packet is from the a remote device.
bool is_registered ()
Check if the device has a valid, i.e.
Additional Inherited Members
Protected Attributes inherited from HF::Devices::Concentrator::AbstractBase
Common::SimpleList< Transport::Link * > _links
List of links present in this concentrator.
Protected Attributes inherited from HF::Devices::AbstractDevice
uint8_t next_reference
Last reference number used to send a packet.
IUnits _units
List containing pointers to the units present in the device.
Protocol::Filters::ResponseRequired response_filter
Support for generating missing responses for messages.
Detailed Description
Device Management interface : Server side API.
Definition at line 558 of file device_management.h.
Constructor & Destructor Documentation
IServer()
HF::Core::DeviceManagement::IServer::IServer (Unit0 & unit) inline protected
Constructor.
Parameters
[in] unit reference to the unit containing this service.
Definition at line 679 of file device_management.h.
                                 : ServiceRole(unit)
             {}
Member Function Documentation
deregistered()
virtual void HF::Core::DeviceManagement::IServer::deregistered (DevicePtr & device) inline virtual
Indicate that a device has been de-registered.
Parameters
[in] device pointer to the device entry corresponding to the de-registered device.
Definition at line 664 of file device_management.h.
References UNUSED.
             {
                UNUSED(device);
             }
entries()
virtual IEntries& HF::Core::DeviceManagement::IServer::entries () const pure virtual
Get a reference to the current object implementing the persistence API, for the device information.
Returns
reference to the current object for the persistence API.
Implemented in HF::Core::DeviceManagement::Server< _Entries >, and HF::Core::DeviceManagement::Server< Entries >.
Referenced by entry(), and next_address().
entry() [1/2]
DevicePtr HF::Core::DeviceManagement::IServer::entry (uint16_t address) const
Return the Device entry for the given address.
Parameters
[in] address the device address.
Return values
a pointer the Device entry associated with the given address,
nullptr if the entry does not exist.
entry() [2/2]
DevicePtr HF::Core::DeviceManagement::IServer::entry (const HF::UID::UID & uid) const inline
Return the Device entry for the given UID.
Parameters
[in] uid the device UID.
Return values
a pointer the Device entry associated with the given UID,
nullptr if the entry does not exist.
Definition at line 594 of file device_management.h.
References entries(), and HF::Core::DeviceManagement::IEntries::find().
             {
                return entries().find(uid);
             }
next_address()
virtual uint16_t HF::Core::DeviceManagement::IServer::next_address () inline virtual
Return next available address for registering a device.
Returns
the address to use in the next registration.
Reimplemented in DeviceManagement::Server.
Definition at line 636 of file device_management.h.
References entries(), and HF::Core::DeviceManagement::IEntries::next_address().
Referenced by DeviceManagement::Server::next_address().
             {
                return entries().next_address();
             }
registered()
virtual void HF::Core::DeviceManagement::IServer::registered (DevicePtr & device) inline virtual
Indicate that a device has been registered.
Parameters
[in] device pointer to the device entry corresponding to the registered device.
Definition at line 653 of file device_management.h.
References UNUSED.
             {
                UNUSED(device);
             }
sessions()
virtual SessionManagement::IServer& HF::Core::DeviceManagement::IServer::sessions () pure virtual
Reference to the session management API.
Returns
reference to the object implementing the session management API for this device management server.
Implemented in HF::Core::DeviceManagement::Server< _Entries >, and HF::Core::DeviceManagement::Server< Entries >.
unit0()
HF::Devices::Concentrator::IUnit0& HF::Core::DeviceManagement::IServer::unit0 () const virtual
Return a reference to the unit that this service belongs to.
This is the same reference as AbstractService::unit, but static casted to allow access to the the other interfaces.
Returns
a reference to the unit that holds this interface.
Implements HF::Devices::Concentrator::AbstractBase.
The documentation for this struct was generated from the following file:
device_management.h