HAN-FUN API: HF::UID::NONE Struct Reference
HF::UID::NONE Struct Reference
Devices » UIDs
This class represents an empty UID.
#include <uids.h>
Public Member Functions
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
NONE * clone () const
Create a clone object of the object where this method is being called.
Public Member Functions inherited from HF::UID::UID_T
virtual int compare (const UID_T &other) const
Compare the current UID with the given UID.
uint16_t size () const
Number bytes needed to serialize the message.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Additional Inherited Members
Static Public Attributes inherited from HF::UID::UID_T
static constexpr uint16_t min_size
Minimum pack/unpack required data size.
Detailed Description
This class represents an empty UID.
Definition at line 144 of file uids.h.
Member Function Documentation
NONE* HF::UID::NONE::clone () const inline virtual
Create a clone object of the object where this method is being called.
Returns
a new object that is a clone of this object.
Implements HF::Common::Cloneable< UID_T >.
Definition at line 178 of file uids.h.
          {
             return new NONE (*this);
          }
uint16_t HF::UID::NONE::pack (Common::ByteArray & array, uint16_t offset = 0) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Reimplemented from HF::UID::UID_T.
Definition at line 146 of file uids.h.
References HF::UID::UID_T::min_size, HF::UID::UID_T::pack(), SERIALIZABLE_CHECK, and HF::Common::ByteArray::write().
          {
             SERIALIZABLE_CHECK (array, offset, min_size);
             offset += UID_T::pack (array, offset);
             array.write (offset, (uint8_t) 0);
             return min_size;
          }
uint16_t HF::UID::NONE::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Reimplemented from HF::UID::UID_T.
Definition at line 157 of file uids.h.
References HF::UID::UID_T::min_size, HF::Common::ByteArray::read(), SERIALIZABLE_CHECK, HF::UID::UID_T::size(), and HF::UID::UID_T::unpack().
          {
             SERIALIZABLE_CHECK (array, offset, min_size);
             uint16_t res = UID_T::unpack (array, offset);
             if (res == 0)
             {
                return 0;
             }
             offset += res;
             uint8_t size;
             array.read (offset, size);
             assert (size == 0);
             return min_size;
          }
The documentation for this struct was generated from the following file:
uids.h