HAN-FUN API: HF::Core::SUOTA::CheckVersionResponse Struct Reference
HF::Core::SUOTA::CheckVersionResponse Struct Reference
Core Services & Interfaces » SUOTA
This class represents the message for the response of a SUOTA::CHECK_VERSION_CMD.
#include <suota.h>
Public Types
enum Status { VERSION_AVAILABLE = 0x00, NO_VERSION_AVAILABLE = 0x11, FAIL_INFRASTUCTURE = 0x12, FAIL_UNKNOWN = Common::FAIL_UNKNOWN }
Possible result codes for a SUOTA::CHECK_VERSION_CMD.
Public Member Functions
CheckVersionResponse (Status _status=FAIL_UNKNOWN, const std::string _sw_version="", const std::string _hw_version="", const std::string _url="")
Constructor.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Public Member Functions inherited from HF::Protocol::Response
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Public Member Functions inherited from HF::Core::SUOTA::Version
Version (const std::string _sw_version="", const std::string _hw_version="", const std::string _url="")
Constructor.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Static Public Attributes
static constexpr uint16_t min_size = Protocol::Response::min_size + Version::min_size
Minimum pack/unpack required data size.
Static Public Attributes inherited from HF::Protocol::Response
static constexpr uint16_t min_size = sizeof(uint8_t)
Minimum number of bytes required by this message.
Static Public Attributes inherited from HF::Core::SUOTA::Version
static constexpr uint16_t min_size = 2 * sizeof(uint8_t)
Minimum pack/unpack required data size.
Additional Inherited Members
Data Fields inherited from HF::Core::SUOTA::Version
std::string sw_version
Current/Available software version.
std::string hw_version
Current/Minimum required hardware version.
std::string url
Update URL.
Detailed Description
This class represents the message for the response of a SUOTA::CHECK_VERSION_CMD.
Definition at line 127 of file suota.h.
Member Enumeration Documentation
Status
enum HF::Core::SUOTA::CheckVersionResponse::Status
Possible result codes for a SUOTA::CHECK_VERSION_CMD.
Enumerator
VERSION_AVAILABLE
New version available.
NO_VERSION_AVAILABLE
No newer version available.
FAIL_INFRASTUCTURE
Server or Network are down.
FAIL_UNKNOWN
Fail: Unknown Error.
Definition at line 132 of file suota.h.
             {
                VERSION_AVAILABLE    = 0x00,
                NO_VERSION_AVAILABLE = 0x11,
                FAIL_INFRASTUCTURE   = 0x12,
                FAIL_UNKNOWN         = Common::FAIL_UNKNOWN,
             } Status;
Constructor & Destructor Documentation
CheckVersionResponse()
HF::Core::SUOTA::CheckVersionResponse::CheckVersionResponse (Status _status = FAIL_UNKNOWN, const std::string _sw_version = "", const std::string _hw_version = "", const std::string _url = "") inline
Constructor.
Parameters
[in] _status response status to send (M)
[in] _sw_version software version to send (M)
[in] _hw_version hardware version to send (M)
[in] _url update URL (O)
Definition at line 148 of file suota.h.
                                                                                              :
                Protocol::Response(_status),
                Version(_sw_version, _hw_version, _url) {}
Member Function Documentation
pack()
uint16_t HF::Core::SUOTA::CheckVersionResponse::pack (Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 166 of file suota.h.
References HF_SERIALIZABLE_CHECK, HF::Core::SUOTA::Version::pack(), HF::Protocol::Response::pack(), and size().
             {
                HF_SERIALIZABLE_CHECK(array, offset, size());
                uint16_t start = offset;
                offset += Protocol::Response::pack(array, offset);
                offset += Version::pack(array, offset);
                return offset - start;
             }
size()
uint16_t HF::Core::SUOTA::CheckVersionResponse::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 160 of file suota.h.
References HF::Core::SUOTA::Version::size(), and HF::Protocol::Response::size().
Referenced by pack(), and unpack().
             {
                return Protocol::Response::size() + Version::size();
             }
unpack()
uint16_t HF::Core::SUOTA::CheckVersionResponse::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 179 of file suota.h.
References HF_ASSERT, HF_SERIALIZABLE_CHECK, min_size, size(), HF::Core::SUOTA::Version::unpack(), and HF::Protocol::Response::unpack().
             {
                HF_SERIALIZABLE_CHECK(array, offset, min_size);
                uint16_t start = offset;
                uint16_t size  = Protocol::Response::unpack(array, offset);
                HF_ASSERT(size != 0, {return 0;});
                offset += size;
                size    = Version::unpack(array, offset);
                HF_ASSERT(size != 0, {return 0;});
                offset += size;
                return offset - start;
             }
The documentation for this struct was generated from the following file:
suota.h