HAN-FUN API: HF::Core::SUOTA::UpgradeStatus Struct Reference
HF::Core::SUOTA::UpgradeStatus Struct Reference
Core Services & Interfaces » SUOTA
This class contains the required parameters for a SUOTA::UPGRADE_COMPLETE_CMD command.
#include <suota.h>
Public Types
enum Code {
UPGRADE_SUCCESSFUL = 0x00, UPGRADE_ABORTED = 0x11, GMEP_SESSION_ERROR = 0x12, INVALID_IMAGE = 0x13,
MEMORY_ACCESS_ERROR = 0x14, BATTERY_TOO_LOW = 0x15, FAIL_UNKNOWN = Common::FAIL_UNKNOWN
}
Possible status in a.
Public Member Functions
UpgradeStatus (Code _code=FAIL_UNKNOWN, std::string _sw_version="")
Software version after update.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
std::string sw_version
Update status.
Static Public Attributes
static constexpr uint16_t min_size = sizeof(uint8_t)
Minimum pack/unpack required data size.
Detailed Description
This class contains the required parameters for a SUOTA::UPGRADE_COMPLETE_CMD command.
Definition at line 200 of file suota.h.
Member Enumeration Documentation
Code
enum HF::Core::SUOTA::UpgradeStatus::Code
Possible status in a.
Enumerator
UPGRADE_SUCCESSFUL
Upgrade successful.
UPGRADE_ABORTED
Upgrade aborted.
GMEP_SESSION_ERROR
GMEP session error.
INVALID_IMAGE
Invalid image.
MEMORY_ACCESS_ERROR
Memory access error.
BATTERY_TOO_LOW
Battery too low.
FAIL_UNKNOWN
Fail: Unknown Error.
Definition at line 205 of file suota.h.
             {
                UPGRADE_SUCCESSFUL  = 0x00,
                UPGRADE_ABORTED     = 0x11,
                GMEP_SESSION_ERROR  = 0x12,
                INVALID_IMAGE       = 0x13,
                MEMORY_ACCESS_ERROR = 0x14,
                BATTERY_TOO_LOW     = 0x15,
                FAIL_UNKNOWN        = Common::FAIL_UNKNOWN,
             } Code;
Constructor & Destructor Documentation
UpgradeStatus()
HF::Core::SUOTA::UpgradeStatus::UpgradeStatus (Code _code = FAIL_UNKNOWN, std::string _sw_version = "") inline
Software version after update.
Constructor.
Parameters
[in] _code update status to send in the command.
[in] _sw_version new software version of the update.
Definition at line 225 of file suota.h.
                                                                                 :
                code(_code), sw_version(_sw_version) {}
Member Function Documentation
pack()
uint16_t HF::Core::SUOTA::UpgradeStatus::pack (Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 240 of file suota.h.
References HF_SERIALIZABLE_CHECK, HF::Common::SerializableHelper< T, typename >::pack(), size(), sw_version, and HF::Common::ByteArray::write().
             {
                HF_SERIALIZABLE_CHECK(array, offset, size());
                uint16_t start = offset;
                offset += array.write(offset, static_cast<uint8_t>(code));
                if (!sw_version.empty())
                {
                   offset +=
                      Common::SerializableHelper<std::string>::pack(sw_version, array, offset);
                }
                return offset - start;
             }
size()
uint16_t HF::Core::SUOTA::UpgradeStatus::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 232 of file suota.h.
References HF::Common::SerializableHelper< T, typename >::size(), and sw_version.
Referenced by pack().
             {
                return sizeof(uint8_t) +
                       (sw_version.empty() ? 0 :
                        Common::SerializableHelper<std::string>::size(sw_version));
             }
unpack()
uint16_t HF::Core::SUOTA::UpgradeStatus::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 258 of file suota.h.
References HF_SERIALIZABLE_CHECK, min_size, HF::Common::ByteArray::read(), sw_version, and HF::Common::SerializableHelper< T, typename >::unpack().
             {
                HF_SERIALIZABLE_CHECK(array, offset, min_size);
                uint16_t start = offset;
                uint8_t temp;
                offset += array.read(offset, temp);
                code    = static_cast<Code>(temp);
                offset += Common::SerializableHelper<std::string>::unpack(sw_version, array, offset);
                return offset - start;
             }
The documentation for this struct was generated from the following file:
suota.h