HAN-FUN API: HF::Protocol::GetAttributePack::Request Struct Reference
HF::Protocol::GetAttributePack::Request Struct Reference
Protocol » Attributes » Packs
This class represents the payload of a HF::Message::GET_ATTR_PACK_REQ request, when the payload is Type::DYNAMIC.
#include <attributes.h>
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
HF::Attributes::UIDS attributes
Vector containing the attributes UID's to get.
uint8_t count
Unpack attribute count.
Detailed Description
This class represents the payload of a HF::Message::GET_ATTR_PACK_REQ request, when the payload is Type::DYNAMIC.
Definition at line 826 of file attributes.h.
Member Function Documentation
uint16_t HF::Protocol::GetAttributePack::Request::pack (Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 851 of file attributes.h.
References HF::Attributes::UIDS::pack().
             {
                return attributes.pack (array, offset);
             }
uint16_t HF::Protocol::GetAttributePack::Request::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 845 of file attributes.h.
References HF::Attributes::UIDS::size().
             {
                return attributes.size ();
             }
uint16_t HF::Protocol::GetAttributePack::Request::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 857 of file attributes.h.
References HF::Attributes::UIDS::unpack().
             {
                return attributes.unpack (array, offset, count);
             }
Field Documentation
HF::Attributes::UIDS HF::Protocol::GetAttributePack::Request::attributes
Vector containing the attributes UID's to get.
Definition at line 828 of file attributes.h.
uint8_t HF::Protocol::GetAttributePack::Request::count
Unpack attribute count.
Warning
This value will not be used as the number of attributes, when packing the request.
Definition at line 836 of file attributes.h.
The documentation for this struct was generated from the following file:
attributes.h