HAN-FUN API: hello_msg_t Struct Reference
hello_msg_t Struct Reference
Examples
Hello message payload.
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (HF::Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (HF::Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
uint8_t core
HAN-FUN Core Services & Interfaces version.
uint8_t profiles
HAN-FUN Profiles version.
uint8_t interfaces
HAN-FUN Interfaces version.
HF::UID::UID uid
Remote device UID.
Static Public Attributes
static constexpr uint16_t min_size = 3 * sizeof(uint8_t)
Minimum pack/unpack required data size.
Detailed Description
Hello message payload.
Definition at line 142 of file transport.cpp.
Member Function Documentation
pack()
uint16_t hello_msg_t::pack (HF::Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 164 of file transport.cpp.
References core, HF_SERIALIZABLE_CHECK, interfaces, HF::UID::UID::pack(), profiles, size(), uid, and HF::Common::ByteArray::write().
    {
       HF_SERIALIZABLE_CHECK(array, offset, size());
       uint16_t start = offset;
       offset += array.write(offset, core);
       offset += array.write(offset, profiles);
       offset += array.write(offset, interfaces);
       offset += uid.pack(array, offset);
       return offset - start;
    }
size()
uint16_t hello_msg_t::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 158 of file transport.cpp.
References min_size, HF::UID::UID::size(), and uid.
Referenced by pack().
    {
       return min_size + uid.size();
    }
unpack()
uint16_t hello_msg_t::unpack (HF::Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 180 of file transport.cpp.
References core, HF_SERIALIZABLE_CHECK, interfaces, min_size, profiles, HF::Common::ByteArray::read(), uid, and HF::UID::UID::unpack().
    {
       HF_SERIALIZABLE_CHECK(array, offset, min_size);
       uint16_t start = offset;
       offset += array.read(offset, core);
       offset += array.read(offset, profiles);
       offset += array.read(offset, interfaces);
       uid.unpack(array, offset);
       return offset - start;
    }
Field Documentation
core
uint8_t hello_msg_t::core
HAN-FUN Core Services & Interfaces version.
Definition at line 144 of file transport.cpp.
Referenced by pack(), and unpack().
interfaces
uint8_t hello_msg_t::interfaces
HAN-FUN Interfaces version.
Definition at line 146 of file transport.cpp.
Referenced by pack(), and unpack().
profiles
uint8_t hello_msg_t::profiles
HAN-FUN Profiles version.
Definition at line 145 of file transport.cpp.
Referenced by pack(), and unpack().
uid
HF::UID::UID hello_msg_t::uid
Remote device UID.
Definition at line 148 of file transport.cpp.
Referenced by pack(), size(), and unpack().
The documentation for this struct was generated from the following file:
transport.cpp