HAN-FUN API: HF::Common::SerializableHelper< T, typename > Struct Template Reference
HF::Common::SerializableHelper< T, typename > Struct Template Reference
Common
Wrapper for classes that implement the Serializable concept.
#include <common.h>
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
int compare (const SerializableHelper< T > &other) const
Compare this attribute with the given attribute in other.
float changed (const SerializableHelper< T > &other) const
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Data Fields
T data
Data type instance wrapped.
Detailed Description
template<typename T, typename = void>
struct HF::Common::SerializableHelper< T, typename >
Wrapper for classes that implement the Serializable concept.
Template Parameters
T data type to warp.
Warning
T should be POD (Plain Old Data)
Definition at line 406 of file inc/hanfun/common.h.
Member Function Documentation
template<typename T, typename = void> float HF::Common::SerializableHelper< T, typename >::changed (const SerializableHelper< T > & other) const inline
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Parameters
[in] other attribute holding a previous value.
Returns
float indicating the percentage of change.
Definition at line 443 of file inc/hanfun/common.h.
Referenced by HF::Attributes::Attribute< bool >::changed(), and HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::changed().
          {
             return data.changed (other.data);
          }
template<typename T, typename = void> int HF::Common::SerializableHelper< T, typename >::compare (const SerializableHelper< T > & other) const inline
Compare this attribute with the given attribute in other.
This method should return < 0 if this attribute is less that, 0 if it is equal and > 0 if greater that the other attribute.
Parameters
[in] other attribute to compare to.
Return values
<0 if attribute less than other;
0 if attribute equal to other;
>0 if attribute greater than other.
Definition at line 437 of file inc/hanfun/common.h.
Referenced by HF::Attributes::Attribute< bool >::compare(), and HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::compare().
          {
             return data.compare (other.data);
          }
template<typename T, typename = void> uint16_t HF::Common::SerializableHelper< T, typename >::pack (ByteArray & array, uint16_t offset = 0) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Implements HF::Common::Serializable.
Definition at line 424 of file inc/hanfun/common.h.
Referenced by HF::Attributes::Attribute< bool >::pack(), and HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::pack().
          {
             SERIALIZABLE_CHECK (array, offset, size ());
             return data.pack (array, offset);
          }
template<typename T, typename = void> uint16_t HF::Common::SerializableHelper< T, typename >::size () const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Implements HF::Common::Serializable.
Definition at line 419 of file inc/hanfun/common.h.
Referenced by HF::Attributes::Attribute< bool >::size(), HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::size(), and HF::Common::SerializableHelper< std::string >::size().
          {
             return data.size ();
          }
template<typename T, typename = void> uint16_t HF::Common::SerializableHelper< T, typename >::unpack (const ByteArray & array, uint16_t offset = 0) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Implements HF::Common::Serializable.
Definition at line 430 of file inc/hanfun/common.h.
Referenced by HF::Attributes::Attribute< bool >::unpack(), and HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::unpack().
          {
             SERIALIZABLE_CHECK (array, offset, size ());
             return data.unpack (array, offset);
          }
The documentation for this struct was generated from the following file:
inc/hanfun/common.h