HAN-FUN API: msg_t Struct Reference
msg_t Struct Reference
Examples
Message sent between the concentrator and the nodes.
Public Member Functions
msg_t (uint16_t primitive=NONE_MSG)
Constructor.
msg_t (uint16_t primitive, HF::Common::ByteArray &data)
Constructor.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (HF::Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (HF::Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
uint16_t nbytes
Number of bytes in the message.
uint16_t primitive
Message type.
HF::Common::ByteArray data
Message payload.
Static Public Attributes
static constexpr uint16_t min_size = sizeof(nbytes) + sizeof(primitive)
Minimum pack/unpack required data size.
Detailed Description
Message sent between the concentrator and the nodes.
Definition at line 60 of file transport.cpp.
Constructor & Destructor Documentation
msg_t::msg_t (uint16_t primitive = NONE_MSG) inline
Constructor.
Parameters
[in] primitive message type.
Definition at line 71 of file transport.cpp.
                                        :
       primitive(primitive)
    {}
msg_t::msg_t (uint16_t primitive, HF::Common::ByteArray & data) inline
Constructor.
Parameters
[in] primitive message type.
[in] data message payload.
Definition at line 81 of file transport.cpp.
                                                      :
       primitive(primitive), data(data)
    {}
Member Function Documentation
uint16_t msg_t::pack (HF::Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 95 of file transport.cpp.
References data, HF_SERIALIZABLE_CHECK, primitive, size(), and HF::Common::ByteArray::write().
    {
       HF_SERIALIZABLE_CHECK(array, offset, size());
       uint16_t start = offset;
       uint16_t temp  = (uint16_t) (sizeof(uint16_t) + data.size());
       offset += array.write(offset, temp);
       offset += array.write(offset, primitive);
       std::copy(data.begin(), data.end(), array.begin() + offset);
       return offset - start;
    }
uint16_t msg_t::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 89 of file transport.cpp.
References data, and min_size.
Referenced by pack().
    {
       return min_size + data.size();
    }
uint16_t msg_t::unpack (HF::Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 113 of file transport.cpp.
References data, HF_SERIALIZABLE_CHECK, min_size, nbytes, primitive, and HF::Common::ByteArray::read().
    {
       HF_SERIALIZABLE_CHECK(array, offset, min_size);
       uint16_t start = offset;
       offset += array.read(offset, nbytes);
       offset += array.read(offset, primitive);
       uint16_t data_size = nbytes - sizeof(primitive);
       data = HF::Common::ByteArray(data_size);
       auto begin = array.begin();
       begin += offset;
       auto end = begin + data_size;
       std::copy(begin, end, data.begin());
       return offset - start;
    }
Field Documentation
HF::Common::ByteArray msg_t::data
Message payload.
Definition at line 64 of file transport.cpp.
Referenced by pack(), HF::Application::Link::send(), size(), and unpack().
uint16_t msg_t::nbytes
Number of bytes in the message.
Definition at line 62 of file transport.cpp.
Referenced by unpack().
uint16_t msg_t::primitive
Message type.
Definition at line 63 of file transport.cpp.
Referenced by pack(), and unpack().
The documentation for this struct was generated from the following file:
transport.cpp