HAN-FUN API: HF::Core::BatchProgramManagement::Client Struct Reference
HF::Core::BatchProgramManagement::Client Struct Reference abstract
Core Services & Interfaces » Batch Program Management
Batch Program Management Interfaces::Interface : Client side implementation.
#include <batch_program_management.h>
Public Member Functions
Commands
Common::Result define_program (const Protocol::Address &addr, const uint8_t pid, const std::string name, std::vector< Action > &actions)
Send a HAN-FUN message containing a BatchProgramManagement::DEFINE_PROGRAM_CMD, to the given network address.
Common::Result define_program (const Protocol::Address &addr, Entry &program)
Send a HAN-FUN message containing a BatchProgramManagement::DEFINE_PROGRAM_CMD, to the given network address.
void invoke_program (const Protocol::Address &addr, uint8_t pid)
Send a HAN-FUN message containing a BatchProgramManagement::INVOKE_PROGRAM_CMD, to the given network address.
void delete_program (const Protocol::Address &addr, uint8_t pid)
Send a HAN-FUN message containing a BatchProgramManagement::DELETE_PROGRAM_CMD, to the given network address.
void delete_all_programs (const Protocol::Address &addr)
Send a HAN-FUN message containing a BatchProgramManagement::DELETE_ALL_PROGRAMS_CMD, to the given network address.
Events
virtual void defined (DefineProgramResponse &response)=0
This method is called when a response to a create program is received.
virtual void deleted (DeleteProgramResponse &response)=0
This method is called when a response to a delete program is received.
virtual void deleted (DeleteAllProgramsResponse &response)=0
This method is called when a response to a delete all programs is received.
virtual void invoked (InvokeProgramResponse &response)=0
This method is called when a response to a invoke program message is received.
virtual void got_actions (GetProgramActionsResponse &response)=0
This method is called when a response to a get info message is received.
Public Member Functions inherited from HF::Core::ServiceRole< BatchProgramManagement::Base, HF::Interface::CLIENT_ROLE >
Interface::Role role () const
Return the Interface::Role this interface implements.
Public Member Functions inherited from HF::Core::Service< HF::Interface::BATCH_PROGRAM_MANAGEMENT >
uint16_t uid () const
This method returns the interface UID.
Public Member Functions inherited from HF::Core::AbstractService
Unit0 & unit () const
The device this unit is associated with.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
HF::Attributes::UIDS attributes (uint8_t pack_id=HF::Attributes::Pack::MANDATORY) const
Return a vector containing the attribute UIDs, for the given pack ID.
Public Member Functions inherited from HF::Interfaces::AbstractInterface
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void periodic (uint32_t time)
Handle periodic processing.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
Protected Member Functions
uint16_t payload_size (Protocol::Message::Interface &itf) const
Return the minimal payload size that a message should hold when addressed at the given interface.
Common::Result handle_command (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
Protected Member Functions inherited from HF::Core::ServiceRole< BatchProgramManagement::Base, HF::Interface::CLIENT_ROLE >
ServiceRole (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Core::BatchProgramManagement::Base
Base (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Core::Service< HF::Interface::BATCH_PROGRAM_MANAGEMENT >
Service (Unit0 &unit)
Constructor.
bool check_uid (uint16_t uid) const
Check if the given uid value matches the service's UID value.
Protected Member Functions inherited from HF::Core::AbstractService
AbstractService (Unit0 &unit)
Constructor.
void send (const Protocol::Address &addr, Protocol::Message &message)
Send message msg to the network address given by addr.
void send (const Protocol::Address &addr, Protocol::Message &message, Transport::Link *link)
Create and send a new packet with the given message to the given address.
Protected Member Functions inherited from HF::Interfaces::AbstractInterface
virtual void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify that an attribute value as changed.
Common::Result check (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if message has correct attributes to be processed by the interface.
Common::Result check_payload_size (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if payload data size if sufficient for processing the message.
virtual uint16_t payload_size (Protocol::Message &message) const
Return the minimal payload size that should be present for the given message.
template<typename _Message >
uint16_t payload_size_helper () const
Helper function template to retrieve minimum size required for serializing/deserializing the class given.
virtual Common::Result handle_attribute (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
Additional Inherited Members
Public Types inherited from HF::Interface
Static Public Attributes inherited from HF::Interface
static constexpr uint8_t MAX_CMD_ID = 0xFF
Maximum value for command IDs in interfaces.
Protected Attributes inherited from HF::Core::AbstractService
Unit0 & _unit
Reference to the unit the service belongs to.
Detailed Description
Batch Program Management Interfaces::Interface : Client side implementation.
This class provides the client side of the Batch Program Management interface.
Definition at line 723 of file batch_program_management.h.
Member Function Documentation
Common::Result HF::Core::BatchProgramManagement::Client::define_program (const Protocol::Address & addr, const uint8_t pid, const std::string name, std::vector< Action > & actions) inline
Send a HAN-FUN message containing a BatchProgramManagement::DEFINE_PROGRAM_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] pid the program ID.
[in] name the name for the program.
[in] actions the list of actions that makes the program.
Return values
Result:OK if the message could be created and sent,
REsult::FAIL_ARG otherwise.
Definition at line 749 of file batch_program_management.h.
References operator<<(), HF::Protocol::request(), and HF::Protocol::response().
             {
                DefineProgram request(pid, name, actions);
                return define_program(addr, request);
             }
Common::Result HF::Core::BatchProgramManagement::Client::define_program (const Protocol::Address & addr, Entry & program)
Send a HAN-FUN message containing a BatchProgramManagement::DEFINE_PROGRAM_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] program the program to send to the device.
Return values
Result:OK if the message could be created and sent,
REsult::FAIL_ARG otherwise.
virtual void HF::Core::BatchProgramManagement::Client::defined (DefineProgramResponse & response) pure virtual
This method is called when a response to a create program is received.
Parameters
[in] response the create program response that was received.
void HF::Core::BatchProgramManagement::Client::delete_all_programs (const Protocol::Address & addr)
Send a HAN-FUN message containing a BatchProgramManagement::DELETE_ALL_PROGRAMS_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
void HF::Core::BatchProgramManagement::Client::delete_program (const Protocol::Address & addr, uint8_t pid)
Send a HAN-FUN message containing a BatchProgramManagement::DELETE_PROGRAM_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] pid the ID of the program to delete.
virtual void HF::Core::BatchProgramManagement::Client::deleted (DeleteProgramResponse & response) pure virtual
This method is called when a response to a delete program is received.
Parameters
[in] response the deleted response that was received.
virtual void HF::Core::BatchProgramManagement::Client::deleted (DeleteAllProgramsResponse & response) pure virtual
This method is called when a response to a delete all programs is received.
Parameters
[in] response the deleted all response that was received.
virtual void HF::Core::BatchProgramManagement::Client::got_actions (GetProgramActionsResponse & response) pure virtual
This method is called when a response to a get info message is received.
Parameters
[in] response the get program actions response that was received.
Common::Result HF::Core::BatchProgramManagement::Client::handle_command (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) protected virtual
Handle incoming messages from the network.
Parameters
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
Handle command request/response messages, i.e. :
Protocol::Message:Type::COMMAND_REQ;
Protocol::Message:Type::COMMAND_RESP_REQ;
Protocol::Message:Type::COMMAND_RES;
Reimplemented from HF::Interfaces::AbstractInterface.
void HF::Core::BatchProgramManagement::Client::invoke_program (const Protocol::Address & addr, uint8_t pid)
Send a HAN-FUN message containing a BatchProgramManagement::INVOKE_PROGRAM_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] pid the ID of the program to run.
virtual void HF::Core::BatchProgramManagement::Client::invoked (InvokeProgramResponse & response) pure virtual
This method is called when a response to a invoke program message is received.
Parameters
[in] response the invoke program response that was received.
uint16_t HF::Core::BatchProgramManagement::Client::payload_size (Protocol::Message::Interface & itf) const protected virtual
Return the minimal payload size that a message should hold when addressed at the given interface.
Parameters
[in] itf the interface being address.
Returns
the minimum number of bytes for the message for the interface.
Reimplemented from HF::Interfaces::AbstractInterface.
The documentation for this struct was generated from the following file:
batch_program_management.h