HAN-FUN API: HF::UID::UID_T Struct Reference
HF::UID::UID_T Struct Reference abstract
Devices » UIDs
API for all UIDs.
#include <uids.h>
Public Member Functions
virtual uint8_t type () const =0
Type of the UID.
virtual int compare (const UID_T &other) const
Compare the current UID with the given UID.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from HF::Common::Cloneable< UID_T >
virtual UID_T * clone () const =0
Create a clone object of the object where this method is being called.
Static Public Attributes
static constexpr uint16_t min_size
Minimum pack/unpack required data size.
Detailed Description
API for all UIDs.
Parent UID class.
Definition at line 55 of file uids.h.
Member Function Documentation
virtual int HF::UID::UID_T::compare (const UID_T & other) const inline virtual
Compare the current UID with the given UID.
This function returns a value less that 0 if the current UID object order is lower that the given UID, 0 if the UIDs represent the same entity and a value greater that 0 if current UID object is above the given UID.
Parameters
[in] other a pointer to a UID object to compare to.
Return values
<0 the current UID is lower that the given UID.
0 the current UID is the same as given UID.
>0 the current UID is greater that the given UID.
Reimplemented in HF::UID::URI, HF::UID::ByteArray< _Class, _size, _type >, HF::UID::ByteArray< DECT, 5, DECT_UID >, and HF::UID::ByteArray< MAC, 6, MAC_UID >.
Definition at line 88 of file uids.h.
References type().
Referenced by HF::UID::ByteArray< MAC, 6, MAC_UID >::compare(), HF::UID::URI::compare(), HF::UID::UID::compare(), and HF::UID::UID::type().
          {
             return (this->type() - other.type());
          }
uint16_t HF::UID::UID_T::pack (Common::ByteArray & array, uint16_t offset = 0) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Implements HF::Common::Serializable.
Reimplemented in HF::UID::URI, HF::UID::ByteArray< _Class, _size, _type >, HF::UID::ByteArray< DECT, 5, DECT_UID >, HF::UID::ByteArray< MAC, 6, MAC_UID >, and HF::UID::NONE.
Definition at line 104 of file uids.h.
References HF_SERIALIZABLE_CHECK, type(), and HF::Common::ByteArray::write().
Referenced by HF::UID::NONE::pack(), HF::UID::ByteArray< MAC, 6, MAC_UID >::pack(), HF::UID::URI::pack(), and HF::UID::UID::pack().
          {
             HF_SERIALIZABLE_CHECK(array, offset, min_size);
             array.write(offset, this->type());
             return sizeof(uint8_t);
          }
uint16_t HF::UID::UID_T::size () const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Implements HF::Common::Serializable.
Reimplemented in HF::UID::URI, HF::UID::ByteArray< _Class, _size, _type >, HF::UID::ByteArray< DECT, 5, DECT_UID >, and HF::UID::ByteArray< MAC, 6, MAC_UID >.
Definition at line 98 of file uids.h.
References min_size.
Referenced by HF::UID::URI::pack(), HF::UID::URI::size(), HF::UID::UID::size(), HF::UID::NONE::unpack(), HF::UID::ByteArray< MAC, 6, MAC_UID >::unpack(), and HF::UID::URI::unpack().
          {
             return min_size;
          }
virtual uint8_t HF::UID::UID_T::type () const pure virtual
Type of the UID.
See also
HF::UID::Type.
Returns
type of the UID.
Implemented in HF::UID::Abstract< _type >, HF::UID::Abstract< URI_UID >, and HF::UID::Abstract< NONE_UID >.
Referenced by compare(), pack(), HF::UID::UID::type(), and unpack().
uint16_t HF::UID::UID_T::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Implements HF::Common::Serializable.
Reimplemented in HF::UID::URI, HF::UID::ByteArray< _Class, _size, _type >, HF::UID::ByteArray< DECT, 5, DECT_UID >, HF::UID::ByteArray< MAC, 6, MAC_UID >, and HF::UID::NONE.
Definition at line 114 of file uids.h.
References HF_SERIALIZABLE_CHECK, HF::Common::ByteArray::read(), and type().
Referenced by HF::UID::UID::pack(), HF::UID::NONE::unpack(), HF::UID::ByteArray< MAC, 6, MAC_UID >::unpack(), and HF::UID::URI::unpack().
          {
             HF_SERIALIZABLE_CHECK(array, offset, min_size);
             uint8_t type;
             array.read(offset, type);
             assert((type & (~0x80)) == this->type());
             return sizeof(uint8_t);
          }
The documentation for this struct was generated from the following file:
uids.h