HAN-FUN API: HF::Common::Serializable Struct Reference
HF::Common::Serializable Struct Reference abstract
Common
This represents the common interface for message serialization.
#include <common.h>
Public Member Functions
virtual ~Serializable ()
Destructor.
virtual uint16_t size () const =0
Number bytes needed to serialize the message.
virtual uint16_t pack (ByteArray &array, uint16_t offset=0) const =0
Write the object on to a ByteArray so it can be sent over the network.
virtual uint16_t unpack (const ByteArray &array, uint16_t offset=0)=0
Read a message from a ByteArray.
Detailed Description
This represents the common interface for message serialization.
Definition at line 447 of file inc/hanfun/common.h.
Member Function Documentation
virtual uint16_t HF::Common::Serializable::pack (ByteArray & array, uint16_t offset = 0) const pure virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Implemented in HF::Common::SerializableHelper< std::vector< uint8_t > >, HF::Common::SerializableHelper< std::string >, HF::Common::SerializableHelper< Common::ByteArray >, HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Common::SerializableHelper< T, EnableIf(IsIntegral(T))>, HF::UID::UID, HF::Common::SerializableHelper< T, EnableIf(IsClassPointer(T))>, HF::Common::SerializableHelper< T, typename >, HF::Common::SerializableHelper< int8_t >, HF::Common::SerializableHelper< uint32_t >, HF::Common::SerializableHelper< value_type >, HF::Common::SerializableHelper< int16_t >, HF::Common::SerializableHelper< T >, HF::Common::SerializableHelper< HS_Colour >, HF::Common::SerializableHelper< XY_Colour >, HF::Common::SerializableHelper< uint8_t >, HF::Common::SerializableHelper< uint16_t >, HF::Common::SerializableHelper< bool >, HF::UID::URI, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, HF::Attributes::Attribute< bool >, HF::UID::ByteArray< _Class, _size, _type >, HF::UID::ByteArray< DECT, 5, DECT_UID >, HF::UID::ByteArray< MAC, 6, MAC_UID >, HF::UID::NONE, and HF::UID::UID_T.
virtual uint16_t HF::Common::Serializable::size () const pure virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Implemented in HF::Common::SerializableHelper< std::vector< uint8_t > >, HF::Common::SerializableHelper< std::string >, HF::Common::SerializableHelper< Common::ByteArray >, HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Common::SerializableHelper< T, EnableIf(IsIntegral(T))>, HF::UID::UID, HF::Common::SerializableHelper< T, EnableIf(IsClassPointer(T))>, HF::Common::SerializableHelper< T, typename >, HF::Common::SerializableHelper< int8_t >, HF::Common::SerializableHelper< uint32_t >, HF::Common::SerializableHelper< value_type >, HF::Common::SerializableHelper< int16_t >, HF::Common::SerializableHelper< T >, HF::Common::SerializableHelper< HS_Colour >, HF::Common::SerializableHelper< XY_Colour >, HF::Common::SerializableHelper< uint8_t >, HF::Common::SerializableHelper< uint16_t >, HF::Common::SerializableHelper< bool >, HF::UID::URI, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, HF::Attributes::Attribute< bool >, HF::UID::ByteArray< _Class, _size, _type >, HF::UID::ByteArray< DECT, 5, DECT_UID >, HF::UID::ByteArray< MAC, 6, MAC_UID >, and HF::UID::UID_T.
Referenced by HF::Attributes::Attribute< bool >::pack(), HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::pack(), HF::Attributes::Response::Response(), HF::Attributes::Attribute< bool >::size(), HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::size(), HF::Attributes::Attribute< bool >::unpack(), and HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::unpack().
virtual uint16_t HF::Common::Serializable::unpack (const ByteArray & array, uint16_t offset = 0) pure virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Implemented in HF::Common::SerializableHelper< std::vector< uint8_t > >, HF::Common::SerializableHelper< std::string >, HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>, HF::Common::SerializableHelper< Common::ByteArray >, HF::Common::SerializableHelper< T, EnableIf(IsIntegral(T))>, HF::UID::UID, HF::Common::SerializableHelper< T, EnableIf(IsClassPointer(T))>, HF::Common::SerializableHelper< T, typename >, HF::Common::SerializableHelper< int8_t >, HF::Common::SerializableHelper< uint32_t >, HF::Common::SerializableHelper< value_type >, HF::Common::SerializableHelper< int16_t >, HF::Common::SerializableHelper< T >, HF::Common::SerializableHelper< HS_Colour >, HF::Common::SerializableHelper< XY_Colour >, HF::Common::SerializableHelper< uint8_t >, HF::Common::SerializableHelper< uint16_t >, HF::Common::SerializableHelper< bool >, HF::Attributes::Attribute< T, _Owner, typename >, HF::Attributes::Attribute< int8_t >, HF::Attributes::Attribute< uint32_t >, HF::Attributes::Attribute< int16_t >, HF::Attributes::Attribute< HS_Colour >, HF::Attributes::Attribute< XY_Colour >, HF::Attributes::Attribute< uint8_t >, HF::Attributes::Attribute< uint16_t >, HF::Attributes::Attribute< bool >, HF::UID::URI, HF::UID::ByteArray< _Class, _size, _type >, HF::UID::ByteArray< DECT, 5, DECT_UID >, HF::UID::ByteArray< MAC, 6, MAC_UID >, HF::UID::NONE, and HF::UID::UID_T.
The documentation for this struct was generated from the following file:
inc/hanfun/common.h