HAN-FUN API: HF::Core::AttributeReporting::Report::Event::AddEntryMessage Struct Reference
HF::Core::AttributeReporting::Report::Event::AddEntryMessage Struct Reference
Add entries into a event rule message.
#include <attribute_reporting.h>
Public Member Functions
void add (const AttributeReporting::Event::Entry &entry)
Add a event entry into this message.
iterator begin ()
Get a iterator to the start of the entries in this rule.
iterator end ()
Get a iterator to the end of the entries in this message.
const_iterator cbegin () const
Get a constant iterator to the start of the entries in this message.
const_iterator cend () const
Get constant iterator to the end of the entries in this message.
Public Member Functions inherited from HF::Core::AttributeReporting::Report::AddEntryMessage
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Protected Member Functions
uint16_t unpack_entry (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
uint8_t count () const
Get number of entries in this message.
uint16_t entry_size () const
Get the minimum number of bytes required for unpacking an entry.
Protected Attributes
Container entries
Container that holds the entries present in the message.
Additional Inherited Members
Data Fields inherited from HF::Core::AttributeReporting::Report::AddEntryMessage
Reference report
Identification of the rule to add the entries to.
Static Public Attributes inherited from HF::Core::AttributeReporting::Report::AddEntryMessage
static constexpr uint16_t min_size
Minimum pack/unpack required data size.
Detailed Description
Add entries into a event rule message.
Definition at line 1119 of file attribute_reporting.h.
Member Function Documentation
void HF::Core::AttributeReporting::Report::Event::AddEntryMessage::add (const AttributeReporting::Event::Entry & entry) inline
Add a event entry into this message.
Parameters
[in] entry entry to add to this message.
Definition at line 1141 of file attribute_reporting.h.
                   {
                      entries.push_front(entry);
                   }
iterator HF::Core::AttributeReporting::Report::Event::AddEntryMessage::begin () inline
Get a iterator to the start of the entries in this rule.
Returns
iterator to the start of the entries present in this rule.
Definition at line 1151 of file attribute_reporting.h.
                   {
                      return entries.begin();
                   }
const_iterator HF::Core::AttributeReporting::Report::Event::AddEntryMessage::cbegin () const inline
Get a constant iterator to the start of the entries in this message.
Returns
constant iterator to the start of the entries present in this message.
Definition at line 1171 of file attribute_reporting.h.
                   {
                      return entries.cbegin();
                   }
const_iterator HF::Core::AttributeReporting::Report::Event::AddEntryMessage::cend () const inline
Get constant iterator to the end of the entries in this message.
Returns
constant iterator to the end of the entries present in this message.
Definition at line 1181 of file attribute_reporting.h.
                   {
                      return entries.cend();
                   }
uint8_t HF::Core::AttributeReporting::Report::Event::AddEntryMessage::count () const inline protected virtual
Get number of entries in this message.
Returns
number of entries in this message.
Reimplemented from HF::Core::AttributeReporting::Report::AddEntryMessage.
Definition at line 1193 of file attribute_reporting.h.
                   {
                      return std::distance(entries.begin(), entries.end());
                   }
iterator HF::Core::AttributeReporting::Report::Event::AddEntryMessage::end () inline
Get a iterator to the end of the entries in this message.
Returns
iterator to the end of the entries present in this message.
Definition at line 1161 of file attribute_reporting.h.
                   {
                      return entries.end();
                   }
uint16_t HF::Core::AttributeReporting::Report::Event::AddEntryMessage::entry_size () const inline protected virtual
Get the minimum number of bytes required for unpacking an entry.
Returns
minimum number of bytes required for unpacking an entry.
Reimplemented from HF::Core::AttributeReporting::Report::AddEntryMessage.
Definition at line 1198 of file attribute_reporting.h.
References HF::Core::AttributeReporting::add(), HF::Core::AttributeReporting::create(), HF::Core::AttributeReporting::create_attribute(), HF::Core::AttributeReporting::destroy(), HF::Core::AttributeReporting::Entry::min_size, and HF::Core::AttributeReporting::update().
                   {
                      return AttributeReporting::Event::Entry::min_size;
                   }
uint16_t HF::Core::AttributeReporting::Report::Event::AddEntryMessage::unpack_entry (const Common::ByteArray & array, uint16_t offset = 0) protected virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Unpack an underling entry for the add entry command.
Reimplemented from HF::Core::AttributeReporting::Report::AddEntryMessage.
The documentation for this struct was generated from the following file:
attribute_reporting.h