HAN-FUN API: HF::Core::Scheduling::Weekly::IServer Struct Reference
HF::Core::Scheduling::Weekly::IServer Struct Reference abstract
Core Services & Interfaces » Weekly Scheduling
Scheduling Service : Server side implementation.
#include <weekly_scheduling.h>
Public Member Functions
virtual Common::Result define_event (const Protocol::Packet &packet, Scheduling::Entry< Day > &msg)
Callback that is called when a Scheduling::DEFINE_EVENT_CMD, is received.
virtual Common::Result update_event_status (const Protocol::Packet &packet, const UpdateStatus &msg)
Callback that is called when a Scheduling::UPDATE_STATUS_CMD, is received.
virtual Common::Result get_event_entry (const Protocol::Packet &packet, const GetEntry &msg)
Callback that is called when a Scheduling::GET_ENTRY_CMD, is received.
virtual Common::Result delete_event (const Protocol::Packet &packet, const DeleteEvent &msg)
Callback that is called when a Scheduling::DELETE_CMD, is received.
virtual Common::Result delete_all_events (const Protocol::Packet &packet)
Callback that is called when a Scheduling::DELETE_ALL_CMD, is received.
IServer (Unit0 &unit)
Constructor.
virtual ~IServer ()
Destructor.
virtual IEntries< Day > & entries () const =0
Get a reference to the current object implementing the persistence API, for the device information.
Common::Pointer< Entry > entry (const uint8_t id) const
Get the Weekly Scheduling entry given by id.
uint8_t next_id () const
Return next available id for event.
Public Member Functions inherited from HF::Core::Service< _ITF, _Parent >
uint16_t uid () const
This method returns the interface UID.
Additional Inherited Members
Protected Member Functions inherited from HF::Core::Scheduling::Base< _ITF, _Parent >
Base (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Core::Service< _ITF, _Parent >
Service (Unit0 &unit)
Constructor.
bool check_uid (uint16_t uid) const
Check if the given uid value matches the service's UID value.
Detailed Description
Scheduling Service : Server side implementation.
This class provides the server side of the Scheduling interface.
Definition at line 363 of file weekly_scheduling.h.
Member Function Documentation
define_event()
virtual Common::Result HF::Core::Scheduling::Weekly::IServer::define_event (const Protocol::Packet & packet, Scheduling::Entry< Day > & msg) virtual
Callback that is called when a Scheduling::DEFINE_EVENT_CMD, is received.
Parameters
[in] packet the packet received.
[in] msg the define event message received.
Return values
Common::Result::OK if the entry was created;
Common::Result::FAIL_ARG if the entry ID already exists;
Common::Result::FAIL_RESOURCES if the entry could not be created;
Common::Result::FAIL_UNKNOWN otherwise.
delete_all_events()
virtual Common::Result HF::Core::Scheduling::Weekly::IServer::delete_all_events (const Protocol::Packet & packet) virtual
Callback that is called when a Scheduling::DELETE_ALL_CMD, is received.
Parameters
[in] packet the packet received.
Return values
Common::Result::OK
delete_event()
virtual Common::Result HF::Core::Scheduling::Weekly::IServer::delete_event (const Protocol::Packet & packet, const DeleteEvent & msg) virtual
Callback that is called when a Scheduling::DELETE_CMD, is received.
Parameters
[in] packet the packet received.
[in] msg the delete event message received.
Return values
Common::Result::OK if the entry was deleted,
Common::Result::FAIL_ARG otherwise.
entries()
virtual IEntries<Day>& HF::Core::Scheduling::Weekly::IServer::entries () const pure virtual
Get a reference to the current object implementing the persistence API, for the device information.
Returns
reference to the current object for the persistence API.
Implemented in HF::Core::Scheduling::Weekly::Server< _Entries >.
Referenced by entry(), and next_id().
entry()
Common::Pointer<Entry> HF::Core::Scheduling::Weekly::IServer::entry (const uint8_t id) const inline
Get the Weekly Scheduling entry given by id.
Parameters
[in] id event id of the event to retrieve.
Return values
pointer to the event entry if it exists,
nullptr otherwise.
Definition at line 470 of file weekly_scheduling.h.
References entries().
                {
                   return entries().find(id);
                }
get_event_entry()
virtual Common::Result HF::Core::Scheduling::Weekly::IServer::get_event_entry (const Protocol::Packet & packet, const GetEntry & msg) virtual
Callback that is called when a Scheduling::GET_ENTRY_CMD, is received.
Parameters
[in] packet the packet received.
[in] msg the get event message received.
Return values
Common::Result::OK if the entry exists,
Common::Result::FAIL_ARG otherwise.
next_id()
uint8_t HF::Core::Scheduling::Weekly::IServer::next_id () const inline
Return next available id for event.
Returns
the id to use in the next event, or Scheduler::Entry::AVAILABLE_ID if no id is available.
Definition at line 478 of file weekly_scheduling.h.
References entries().
                {
                   return entries().next_id();
                }
update_event_status()
virtual Common::Result HF::Core::Scheduling::Weekly::IServer::update_event_status (const Protocol::Packet & packet, const UpdateStatus & msg) virtual
Callback that is called when a Scheduling::UPDATE_STATUS_CMD, is received.
Parameters
[in] packet the packet received.
[in] msg the update event status message received.
Return values
Common::Result::OK if the entry was updated;
Common::Result::FAIL_ARG if the entry does not exists;
The documentation for this struct was generated from the following file:
weekly_scheduling.h