HAN-FUN API: HF::Profiles::Profile2< _uid, Interface1, Interface2 > Struct Template Reference
HF::Profiles::Profile2< _uid, Interface1, Interface2 > Struct Template Reference abstract
Profiles » Common
Class template for profiles containing two interfaces.
#include <profiles.h>
Public Member Functions
virtual Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
virtual void periodic (uint32_t time)
Handle periodic processing.
Interface1 * first ()
Pointer to the first interface instance.
Interface2 * second ()
Pointer to the second interface instance.
const Interface1 * first () const
Pointer to the first interface instance.
const Interface2 * second () const
Pointer to the second interface instance.
virtual void send (const Protocol::Address &addr, Protocol::Message &message)=0
Send message msg to the network address given by addr.
virtual void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const =0
Notify that an attribute value as changed.
HF::Attributes::List attributes (Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
Public Member Functions inherited from HF::Profiles::AbstractProfile< _uid >
uint16_t uid () const
Return this profile HAN-FUN UID.
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
Protected Attributes
std::pair< first_itf_t,
second_itf_t > interfaces
Pair holding the two interface wrappers.
Detailed Description
template<uint16_t _uid, typename Interface1, typename Interface2>
struct HF::Profiles::Profile2< _uid, Interface1, Interface2 >
Class template for profiles containing two interfaces.
Definition at line 292 of file profiles.h.
Member Function Documentation
template<uint16_t _uid, typename Interface1, typename Interface2> HF::Attributes::List HF::Profiles::Profile2< _uid, Interface1, Interface2 >::attributes (Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS & uids) const inline virtual
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
Parameters
[in] itf interface UID.
[in] pack_id attribute pack id.
[in] uids list of attributes UID's.
Returns
attribute list.
Reimplemented from HF::Profiles::AbstractProfile< _uid >.
Definition at line 373 of file profiles.h.
          {
             if (first ()->uid () == itf.id)
             {
                return HF::Attributes::get (*first (), pack_id, uids);
             }
             else if (second ()->uid () == itf.id)
             {
                return HF::Attributes::get (*second (), pack_id, uids);
             }
             else
             {
                return HF::Attributes::List ();
             }
          }
template<uint16_t _uid, typename Interface1, typename Interface2> Interface1* HF::Profiles::Profile2< _uid, Interface1, Interface2 >::first () inline
Pointer to the first interface instance.
Returns
pointer to the interface instance.
Definition at line 330 of file profiles.h.
Referenced by HF::Profiles::Profile2< SIMPLE_LEVEL_CONTROLLABLE_SWITCHABLE, OnOffServer, LevelControlServer >::attributes(), and HF::Profiles::Profile2< SIMPLE_LEVEL_CONTROLLABLE_SWITCHABLE, OnOffServer, LevelControlServer >::periodic().
          {
             return static_cast <Interface1 *>(&(this->interfaces.first));
          }
template<uint16_t _uid, typename Interface1, typename Interface2> const Interface1* HF::Profiles::Profile2< _uid, Interface1, Interface2 >::first () const inline
Pointer to the first interface instance.
Returns
pointer to the interface instance.
Definition at line 350 of file profiles.h.
          {
             return static_cast <const Interface1 *>(&(this->interfaces.first));
          }
template<uint16_t _uid, typename Interface1, typename Interface2> virtual Common::Result HF::Profiles::Profile2< _uid, Interface1, Interface2 >::handle (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) inline virtual
Handle incoming messages from the network.
Parameters
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
Definition at line 303 of file profiles.h.
          {
             Common::Result result = interfaces.first.handle (packet, payload, offset);
             if (result == Common::Result::OK || result == Common::Result::FAIL_SUPPORT)
             {
                return result;
             }
             else
             {
                return interfaces.second.handle (packet, payload, offset);
             }
          }
template<uint16_t _uid, typename Interface1, typename Interface2> virtual void HF::Profiles::Profile2< _uid, Interface1, Interface2 >::notify (const HF::Attributes::IAttribute & old_value, const HF::Attributes::IAttribute & new_value) const pure virtual
Notify that an attribute value as changed.
Parameters
[in] old_value attribute's old value.
[in] new_value attribute's new value.
template<uint16_t _uid, typename Interface1, typename Interface2> virtual void HF::Profiles::Profile2< _uid, Interface1, Interface2 >::periodic (uint32_t time) inline virtual
Handle periodic processing.
Parameters
[in] time current system clock value in seconds.
Definition at line 319 of file profiles.h.
          {
             first ()->periodic (time);
             second ()->periodic (time);
          }
template<uint16_t _uid, typename Interface1, typename Interface2> Interface2* HF::Profiles::Profile2< _uid, Interface1, Interface2 >::second () inline
Pointer to the second interface instance.
Returns
pointer to the interface instance.
Definition at line 340 of file profiles.h.
Referenced by HF::Profiles::Profile2< SIMPLE_LEVEL_CONTROLLABLE_SWITCHABLE, OnOffServer, LevelControlServer >::attributes(), and HF::Profiles::Profile2< SIMPLE_LEVEL_CONTROLLABLE_SWITCHABLE, OnOffServer, LevelControlServer >::periodic().
          {
             return static_cast <Interface2 *>(&(this->interfaces.second));
          }
template<uint16_t _uid, typename Interface1, typename Interface2> const Interface2* HF::Profiles::Profile2< _uid, Interface1, Interface2 >::second () const inline
Pointer to the second interface instance.
Returns
pointer to the interface instance.
Definition at line 360 of file profiles.h.
          {
             return static_cast <const Interface2 *>(&(this->interfaces.second));
          }
template<uint16_t _uid, typename Interface1, typename Interface2> virtual void HF::Profiles::Profile2< _uid, Interface1, Interface2 >::send (const Protocol::Address & addr, Protocol::Message & message) pure virtual
Send message msg to the network address given by addr.
Parameters
[in] addr HF network address.
[in] message pointer to the message to be sent to the network.
The documentation for this struct was generated from the following file:
profiles.h