HAN-FUN API: HF::Common::SerializableHelper< Common::ByteArray > Struct Template Reference
HF::Common::SerializableHelper< Common::ByteArray > Struct Template Reference
Common
Wrapper for Common::ByteArray implementing the Serializable API.
#include <common.h>
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
int compare (const SerializableHelper< Common::ByteArray > &other) const
Compare this attribute with the given attribute in other.
float changed (const SerializableHelper< Common::ByteArray > &other) const
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Static Public Attributes
static constexpr uint16_t min_size = sizeof(uint8_t)
Minimum pack/unpack required data size.
Detailed Description
template<>
struct HF::Common::SerializableHelper< Common::ByteArray >
Wrapper for Common::ByteArray implementing the Serializable API.
Definition at line 603 of file common.h.
Member Function Documentation
float HF::Common::SerializableHelper< Common::ByteArray >::changed (const SerializableHelper< Common::ByteArray > & other) const inline
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Parameters
[in] other attribute holding a previous value.
Returns
float indicating the percentage of change.
Definition at line 674 of file common.h.
References UNUSED.
          {
             UNUSED(other);
             return 0.0;
          }
int HF::Common::SerializableHelper< Common::ByteArray >::compare (const SerializableHelper< Common::ByteArray > & other) const inline
Compare this attribute with the given attribute in other.
This method should return < 0 if this attribute is less that, 0 if it is equal and > 0 if greater that the other attribute.
Parameters
[in] other attribute to compare to.
Return values
<0 if attribute less than other;
0 if attribute equal to other;
>0 if attribute greater than other.
Definition at line 661 of file common.h.
References size().
          {
             int res = data.size() - other.size();
             if (res == 0)
             {
                return memcmp(data.data(), other.data.data(), data.size());
             }
             return res;
          }
uint16_t HF::Common::SerializableHelper< Common::ByteArray >::pack (Common::ByteArray & array, uint16_t offset = 0) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Implements HF::Common::Serializable.
Definition at line 621 of file common.h.
References HF_SERIALIZABLE_CHECK, HF::Common::SerializableHelper< T, typename >::size(), and HF::Common::ByteArray::write().
          {
             HF_SERIALIZABLE_CHECK(array, offset, size());
             uint16_t start = offset;
             offset += array.write(offset, (uint8_t) data.size());
             auto it = array.begin();
             std::advance(it, offset);
             std::copy(data.begin(), data.end(), it);
             offset += data.size();
             return offset - start;
          }
uint16_t HF::Common::SerializableHelper< Common::ByteArray >::size () const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Implements HF::Common::Serializable.
Definition at line 616 of file common.h.
Referenced by compare().
          {
             return min_size + data.size();
          }
uint16_t HF::Common::SerializableHelper< Common::ByteArray >::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Implements HF::Common::Serializable.
Definition at line 639 of file common.h.
References HF_SERIALIZABLE_CHECK, and HF::Common::ByteArray::read().
          {
             HF_SERIALIZABLE_CHECK(array, offset, min_size);
             uint16_t start = offset;
             uint8_t _size  = 0;
             offset += array.read(offset, _size);
             HF_SERIALIZABLE_CHECK(array, offset, _size);
             auto it = array.begin();
             std::advance(it, offset);
             std::copy_n(it, _size, data.begin());
             offset += _size;
             return offset - start;
          }
The documentation for this struct was generated from the following file:
inc/hanfun/common.h