HAN-FUN API: HF::IDevice Struct Reference
HF::IDevice Struct Reference abstract
Devices » Common
This class represents the interface common to all HAN-FUN devices.
#include <device.h>
Data Structures
struct IUnit0
HAN-FUN device Unit 0 common API.
struct IUnits
Unit list type.
Public Member Functions
virtual uint16_t address () const =0
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
virtual const IUnits & units () const =0
Return the list of units registered in this device.
virtual Units::IUnit * unit (uint8_t id) const =0
Return pointer to the unit with the given id.
virtual IUnit0 * unit0 () const =0
Return pointer to the unit 0 for this device.
virtual void add (Units::IUnit *unit)=0
Add unit to devices unit lists.
virtual void remove (Units::IUnit *unit)=0
Remove unit from device's unit list.
virtual void send (Protocol::Packet &packet)=0
Send given packet into the HAN-FUN network.
virtual void periodic (uint32_t time)=0
Handle periodic processing.
Public Member Functions inherited from HF::Transport::Endpoint
virtual void connected (Link *link)=0
Callback to report that a new transport link was been created to a remote device.
virtual void disconnected (Link *link)=0
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
virtual void receive (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)=0
Callback to deliver a packet received from the transport layer.
Detailed Description
This class represents the interface common to all HAN-FUN devices.
Definition at line 67 of file device.h.
Member Function Documentation
virtual void HF::IDevice::add (Units::IUnit * unit) pure virtual
Add unit to devices unit lists.
Parameters
unit pointer to the unit to add to the list.
Implemented in HF::Devices::AbstractDevice.
Referenced by HF::Units::AbstractUnit::AbstractUnit().
virtual uint16_t HF::IDevice::address () const pure virtual
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
Returns
the device address on the HAN-FUN network, HF_BROADCAST_ADDR otherwise.
Implemented in HF::Devices::Concentrator::AbstractBase, HF::Core::DeviceManagement::Client, HF::Devices::Node::Abstract< CoreServices >, HF::Devices::Node::Abstract< NodeUnit0 >, and HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >.
Referenced by HF::Devices::AbstractDevice::is_local(), and HF::Devices::AbstractDevice::is_registered().
virtual void HF::IDevice::periodic (uint32_t time) pure virtual
Handle periodic processing.
Parameters
[in] time current system clock value in seconds.
Implemented in HF::Unit0< Base, ITF >, and HF::Devices::AbstractDevice.
virtual void HF::IDevice::remove (Units::IUnit * unit) pure virtual
Remove unit from device's unit list.
Parameters
unit pointer to the unit to remove from the list.
Implemented in HF::Devices::AbstractDevice.
virtual void HF::IDevice::send (Protocol::Packet & packet) pure virtual
Send given packet into the HAN-FUN network.
Parameters
packet reference to the packet to send to the network.
Implemented in HF::Devices::AbstractDevice.
virtual Units::IUnit* HF::IDevice::unit (uint8_t id) const pure virtual
Return pointer to the unit with the given id.
Parameters
[in] id unit identifier.
Returns
pointer to the unit with the given id, nullptr otherwise.
Implemented in HF::Devices::AbstractDevice.
virtual IUnit0* HF::IDevice::unit0 () const pure virtual
Return pointer to the unit 0 for this device.
Returns
pointer to the unit 0 for this device.
Implemented in HF::Devices::Concentrator::Abstract< CoreServices >, HF::Devices::Concentrator::Abstract< Unit0 >, HF::Devices::Concentrator::Abstract< BaseUnit0 >, HF::Devices::Concentrator::AbstractBase, HF::Core::DeviceManagement::IServer, HF::Core::BindManagement::IServer, HF::Devices::Node::Abstract< CoreServices >, HF::Devices::Node::Abstract< NodeUnit0 >, and HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >.
virtual const IUnits& HF::IDevice::units () const pure virtual
Return the list of units registered in this device.
Returns
list containing the device's registered units.
Implemented in HF::Devices::AbstractDevice.
The documentation for this struct was generated from the following file:
inc/hanfun/device.h