HAN-FUN API: HF::Devices::AbstractDevice Struct Reference
HF::Devices::AbstractDevice Struct Reference abstract
Devices » Common
This class provides the basic implementation for the Device's interface.
#include <devices.h>
Public Member Functions
const IUnits & units () const
Return the list of units registered in this device.
void add (Units::IUnit *unit)
Add unit to devices unit lists.
void remove (Units::IUnit *unit)
Remove unit from device's unit list.
Units::IUnit * unit (uint8_t id) const
Return pointer to the unit with the given id.
void send (Protocol::Packet &packet)
Send given packet into the HAN-FUN network.
void receive (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Callback to deliver a packet received from the transport layer.
void periodic (uint32_t time)
Handle periodic processing.
Public Member Functions inherited from HF::IDevice
virtual uint16_t address () const =0
Return the device address on the HAN-FUN network, when the device is registered, or HF_BROADCAST_ADDR otherwise.
virtual IUnit0 * unit0 () const =0
Return pointer to the unit 0 for this device.
Public Member Functions inherited from HF::Transport::Endpoint
virtual void connected (Link *link)=0
Callback to report that a new transport link was been created to a remote device.
virtual void disconnected (Link *link)=0
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
Protected Member Functions
virtual Transport::Link * link (uint16_t addr) const =0
Return the link that can be used to send a packet to the device with the given address.
virtual bool to_local (const Protocol::Packet &packet) const
Check if the given packet is for this device.
bool from_local (const Protocol::Packet &packet) const
Check if the given packet is from the local device.
bool from_remote (const Protocol::Packet &packet)
Check if the given packet is from the a remote device.
bool is_registered ()
Check if the device has a valid, i.e.
Protected Attributes
uint8_t next_reference
Last reference number used to send a packet.
IUnits _units
List containing pointers to the units present in the device.
Protocol::Filters::ResponseRequired response_filter
Support for generating missing responses for messages.
Detailed Description
This class provides the basic implementation for the Device's interface.
Definition at line 74 of file devices.h.
Member Function Documentation
add()
void HF::Devices::AbstractDevice::add (Units::IUnit * unit) inline virtual
Add unit to devices unit lists.
Parameters
unit pointer to the unit to add to the list.
Implements HF::IDevice.
Definition at line 85 of file devices.h.
References _units, and unit().
          {
             _units.push_front(unit);
          }
from_local()
bool HF::Devices::AbstractDevice::from_local (const Protocol::Packet & packet) const inline protected
Check if the given packet is from the local device.
Parameters
[in] packet reference to the incoming packet.
Return values
true if the source is the local device;
false otherwise.
Definition at line 152 of file devices.h.
References HF::IDevice::address(), HF::Protocol::Address::device, and HF::Protocol::Packet::source.
Referenced by from_remote().
          {
             return packet.source.device == address();
          }
from_remote()
bool HF::Devices::AbstractDevice::from_remote (const Protocol::Packet & packet) inline protected
Check if the given packet is from the a remote device.
Parameters
[in] packet reference to the incoming packet.
Return values
true if the source is a remote device;
false otherwise.
Definition at line 165 of file devices.h.
References from_local().
          {
             return !from_local(packet);
          }
is_registered()
bool HF::Devices::AbstractDevice::is_registered () inline protected
Check if the device has a valid, i.e.
not HF::Protocol::BROADCAST_ADDR.
Returns
if the device address is different from HF::Protocol::BROADCAST_ADDR.
Definition at line 175 of file devices.h.
References HF::IDevice::address(), and HF::Protocol::BROADCAST_ADDR.
          {
             return this->address() != Protocol::BROADCAST_ADDR;
          }
link()
virtual Transport::Link* HF::Devices::AbstractDevice::link (uint16_t addr) const protected pure virtual
Return the link that can be used to send a packet to the device with the given address.
Parameters
[in] addr the address of the device to send the packet to.
Returns
a pointer to the link that can be used to send the packet, nullptr otherwise;
Implemented in HF::Devices::Concentrator::AbstractBase, HF::Devices::Node::Abstract< CoreServices >, HF::Devices::Node::Abstract< NodeUnit0 >, and HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >.
periodic()
void HF::Devices::AbstractDevice::periodic (uint32_t time) virtual
Handle periodic processing.
Parameters
[in] time current system clock value in seconds.
Implements HF::IDevice.
Referenced by HF::Unit0< IUnit0, ITF... >::periodic().
receive()
void HF::Devices::AbstractDevice::receive (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) virtual
Callback to deliver a packet received from the transport layer.
Parameters
[in] packet reference to the received packet.
[in] payload reference a ByteArray containing the received data.
[in] offset offset from where the received data starts on the payload byte array buffer.
Implements HF::Transport::Endpoint.
Reimplemented in HF::Devices::Concentrator::AbstractBase, HF::Devices::Node::Abstract< CoreServices >, HF::Devices::Node::Abstract< NodeUnit0 >, HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >, Base, and Node.
remove()
void HF::Devices::AbstractDevice::remove (Units::IUnit * unit) inline virtual
Remove unit from device's unit list.
Parameters
unit pointer to the unit to remove from the list.
Implements HF::IDevice.
Definition at line 90 of file devices.h.
References _units, and unit().
          {
             _units.remove(unit);
          }
send()
void HF::Devices::AbstractDevice::send (Protocol::Packet & packet) virtual
Send given packet into the HAN-FUN network.
Parameters
packet reference to the packet to send to the network.
Implements HF::IDevice.
Referenced by HF::Core::BindManagement::Client::send(), HF::Core::DeviceManagement::Client::send(), HF::Core::BindManagement::Server< Entries >::send(), and HF::Core::DeviceManagement::Server< Entries >::send().
to_local()
virtual bool HF::Devices::AbstractDevice::to_local (const Protocol::Packet & packet) const inline protected virtual
Check if the given packet is for this device.
Parameters
[in] packet reference to the incoming packet.
Return values
true if the destination is the local device;
false otherwise.
Reimplemented in HF::Devices::Node::Abstract< CoreServices >, HF::Devices::Node::Abstract< NodeUnit0 >, and HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >.
Definition at line 139 of file devices.h.
References HF::IDevice::address(), HF::Protocol::Packet::destination, and HF::Protocol::Address::device.
          {
             return packet.destination.device == address();
          }
unit()
Units::IUnit* HF::Devices::AbstractDevice::unit (uint8_t id) const virtual
Return pointer to the unit with the given id.
Parameters
[in] id unit identifier.
Returns
pointer to the unit with the given id, nullptr otherwise.
Implements HF::IDevice.
Referenced by add(), and remove().
units()
const IUnits& HF::Devices::AbstractDevice::units () const inline virtual
Return the list of units registered in this device.
Returns
list containing the device's registered units.
Implements HF::IDevice.
Definition at line 80 of file devices.h.
References _units.
          {
             return _units;
          }
The documentation for this struct was generated from the following file:
devices.h