HAN-FUN API: HF::Core::GroupTable::Response Struct Reference
HF::Core::GroupTable::Response Struct Reference
Core Services & Interfaces » Group Table
Base class for responses.
#include <group_table.h>
Public Member Functions
Response (Common::Result code=Common::Result::FAIL_UNKNOWN, uint16_t group=0x0000, uint8_t unit=0x00)
Constructor.
Response (Common::Result code, const Entry &entry)
Constructor.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Public Member Functions inherited from HF::Protocol::Response
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Public Member Functions inherited from HF::Core::GroupTable::Entry
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Static Public Attributes
static constexpr uint16_t min_size
Minimum pack/unpack required data size.
Static Public Attributes inherited from HF::Protocol::Response
static constexpr uint16_t min_size = sizeof(uint8_t)
Minimum number of bytes required by this message.
Static Public Attributes inherited from HF::Core::GroupTable::Entry
static constexpr uint16_t min_size
Minimum pack/unpack required data size.
Additional Inherited Members
Data Fields inherited from HF::Core::GroupTable::Entry
uint16_t group
Group address the entry belongs to.
uint8_t unit
Unit ID to route the group messages to.
Detailed Description
Base class for responses.
Definition at line 156 of file group_table.h.
Constructor & Destructor Documentation
Response() [1/2]
HF::Core::GroupTable::Response::Response (Common::Result code = Common::Result::FAIL_UNKNOWN, uint16_t group = 0x0000, uint8_t unit = 0x00) inline
Constructor.
Parameters
[in] code response code.
[in] group group address for response.
[in] unit unit ID for response.
Definition at line 165 of file group_table.h.
                                                                   :
                Protocol::Response(code), Entry(group, unit) {}
Response() [2/2]
HF::Core::GroupTable::Response::Response (Common::Result code, const Entry & entry) inline
Constructor.
Parameters
[in] code response code.
[in] entry group entry for response.
Definition at line 175 of file group_table.h.
                                                            :
                Protocol::Response(code), Entry(entry) {}
Member Function Documentation
pack()
uint16_t HF::Core::GroupTable::Response::pack (Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 193 of file group_table.h.
References HF_SERIALIZABLE_CHECK, HF::Core::GroupTable::Entry::pack(), HF::Protocol::Response::pack(), and size().
             {
                HF_SERIALIZABLE_CHECK(array, offset, size());
                uint16_t start = offset;
                offset += Protocol::Response::pack(array, offset);
                offset += Entry::pack(array, offset);
                return offset - start;
             }
size()
uint16_t HF::Core::GroupTable::Response::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 187 of file group_table.h.
References HF::Core::GroupTable::Entry::size(), and HF::Protocol::Response::size().
Referenced by pack(), and unpack().
             {
                return Protocol::Response::size() + Entry::size();
             }
unpack()
uint16_t HF::Core::GroupTable::Response::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 206 of file group_table.h.
References HF_SERIALIZABLE_CHECK, size(), HF::Core::GroupTable::Entry::unpack(), and HF::Protocol::Response::unpack().
             {
                HF_SERIALIZABLE_CHECK(array, offset, size());
                uint16_t start = offset;
                offset += Protocol::Response::unpack(array, offset);
                offset += Entry::unpack(array, offset);
                return offset - start;
             }
The documentation for this struct was generated from the following file:
group_table.h