HAN-FUN API: HF::Core::GroupTable::Entry Struct Reference
HF::Core::GroupTable::Entry Struct Reference
Core Services & Interfaces » Group Table
This represents a group table entry data structure.
#include <group_table.h>
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
uint16_t group
Group address the entry belongs to.
uint8_t unit
Unit ID to route the group messages to.
Static Public Attributes
static constexpr uint16_t min_size
Minimum pack/unpack required data size.
Detailed Description
This represents a group table entry data structure.
Definition at line 82 of file group_table.h.
Member Function Documentation
uint16_t HF::Core::GroupTable::Entry::pack (Common::ByteArray & array, uint16_t offset = 0) const
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Referenced by HF::Core::GroupTable::Response::pack(), and HF::Core::GroupTable::ReadEntriesResponse::pack().
uint16_t HF::Core::GroupTable::Entry::size () const
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Referenced by HF::Core::GroupTable::Response::size(), and HF::Core::GroupTable::ReadEntriesResponse::size().
uint16_t HF::Core::GroupTable::Entry::unpack (const Common::ByteArray & array, uint16_t offset = 0)
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Referenced by HF::Core::GroupTable::Response::unpack(), and HF::Core::GroupTable::ReadEntriesResponse::unpack().
Field Documentation
uint16_t HF::Core::GroupTable::Entry::group
Group address the entry belongs to.
Definition at line 84 of file group_table.h.
Referenced by HF::Core::GroupTable::Client::read_entries().
uint8_t HF::Core::GroupTable::Entry::unit
Unit ID to route the group messages to.
Definition at line 86 of file group_table.h.
Referenced by HF::Core::GroupTable::Client::read_entries().
The documentation for this struct was generated from the following file:
group_table.h