HAN-FUN API: HF::Devices::Node::Unit0< ITF > Struct Template Reference
HF::Devices::Node::Unit0< ITF > Struct Template Reference
Devices » Node device API.
Template to create Unit 0 for HAN-FUN node devices.
#include <devices.h>
Public Member Functions
Unit0 (IDevice &device)
Constructor.
DeviceInfo * device_info () const
Get the pointer to the node's Device Information service.
DeviceInfo * device_info ()
Get the pointer to the node's Device Information service.
AttrReporting * attribute_reporting () const
Get the pointer to the node's Attribute Reporting service.
AttrReporting * attribute_reporting ()
Get the pointer to the node's Attribute Reporting service.
DeviceMgt * device_management ()
Get the pointer to the node's Device Management service.
DeviceMgt * device_management () const
Get the pointer to the node's Device Management service.
Public Member Functions inherited from HF::Unit0< IUnit0, ITF... >
Unit0 (HF::IDevice &device)
Constructor.
DeviceInfo * device_info () const
Device Information service.
DeviceInfo * device_info ()
Device Information service.
DeviceMgt * device_management () const
Device Management service.
DeviceMgt * device_management ()
Device Management service.
AttrReporting * attribute_reporting () const
Attribute Reporting service.
AttrReporting * attribute_reporting ()
Attribute Reporting service.
Common::Result handle (HF::Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
HF::Attributes::List attributes (Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
Public Member Functions inherited from HF::Interfaces::Container< IUnit0, Proxy< ITF, IUnit0 >... >
Container (IUnit0 &base)
Constructor.
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void attributes (HF::Attributes::List &attr_list, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Return a list of all the attributes for a given interface, pack id and list of attributes UID's.
std::vector< Common::Interface > interfaces () const
Return the list of interfaces present in the wrapper.
const std::tuple_element< N, interfaces_t >::type::base * get () const
Retrieve a pointer to the N optional interface implemented by this unit.
Additional Inherited Members
Public Types inherited from HF::Unit0< IUnit0, ITF... >
enum Inferface
Core Services indexs.
Protected Member Functions inherited from HF::Interfaces::Container< IUnit0, Proxy< ITF, IUnit0 >... >
void for_each (std::function< void(HF::Interface &)> func) const
Call the given function for all the interfaces.
void for_each (std::function< void(HF::Interface &)> func)
Call the given function for all the interfaces.
void for_each (std::function< void(HF::Interface &)> func) const
Helper template function to implement the HF::Units::Unit::for_each functionality.
void for_each (std::function< void(HF::Interface &)> func) const
Helper template function to implement the HF::Units::Unit::for_each functionality.
HF::Interface * find (uint16_t itf_uid) const
Find the interface with the given UID.
HF::Interface * find (uint16_t itf_uid) const
Final template instantiation that finds the wrapped interface with the given UID.
void attributes_itf (HF::Attributes::List &attrs, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Helper function used to provide HF::Units::Unit::attributes functionality.
void attributes_itf (HF::Attributes::List &attrs, Common::Interface itf, uint8_t pack_id, const HF::Attributes::UIDS &uids) const
Helper function used to provide HF::Units::Unit::attributes functionality.
Detailed Description
template<typename... ITF>
struct HF::Devices::Node::Unit0< ITF >
Template to create Unit 0 for HAN-FUN node devices.
Definition at line 230 of file devices.h.
Constructor & Destructor Documentation
Unit0()
template<typename... ITF> HF::Devices::Node::Unit0< ITF >::Unit0 (IDevice & device) inline
Constructor.
Parameters
device reference to the device this unit 0 belongs to.
Definition at line 264 of file devices.h.
                                   :
                HF::Unit0<IUnit0, ITF...>(device)
             {}
Member Function Documentation
attribute_reporting() [1/2]
template<typename... ITF> AttrReporting* HF::Devices::Node::Unit0< ITF >::attribute_reporting () const inline
Get the pointer to the node's Attribute Reporting service.
Returns
pointer to the node's Attribute Reporting service.
Definition at line 293 of file devices.h.
References HF::Unit0< IUnit0, ITF... >::attribute_reporting().
             {
                return _Parent::attribute_reporting();
             }
attribute_reporting() [2/2]
template<typename... ITF> AttrReporting* HF::Devices::Node::Unit0< ITF >::attribute_reporting () inline
Get the pointer to the node's Attribute Reporting service.
Returns
pointer to the node's Attribute Reporting service.
Definition at line 303 of file devices.h.
References HF::Unit0< IUnit0, ITF... >::attribute_reporting().
             {
                return _Parent::attribute_reporting();
             }
device_info() [1/2]
template<typename... ITF> DeviceInfo* HF::Devices::Node::Unit0< ITF >::device_info () const inline
Get the pointer to the node's Device Information service.
Returns
pointer to the node's Device Information service.
Definition at line 273 of file devices.h.
References HF::Unit0< IUnit0, ITF... >::device_info().
             {
                return _Parent::device_info();
             }
device_info() [2/2]
template<typename... ITF> DeviceInfo* HF::Devices::Node::Unit0< ITF >::device_info () inline
Get the pointer to the node's Device Information service.
Returns
pointer to the node's Device Information service.
Definition at line 283 of file devices.h.
References HF::Unit0< IUnit0, ITF... >::device_info().
             {
                return _Parent::device_info();
             }
device_management() [1/2]
template<typename... ITF> DeviceMgt* HF::Devices::Node::Unit0< ITF >::device_management () inline
Get the pointer to the node's Device Management service.
Returns
pointer to the node's Device Management service.
Definition at line 313 of file devices.h.
References HF::Unit0< IUnit0, ITF... >::device_management().
             {
                return _Parent::device_management();
             }
device_management() [2/2]
template<typename... ITF> DeviceMgt* HF::Devices::Node::Unit0< ITF >::device_management () const inline
Get the pointer to the node's Device Management service.
Returns
pointer to the node's Device Management service.
Definition at line 323 of file devices.h.
References HF::Unit0< IUnit0, ITF... >::device_management().
             {
                return _Parent::device_management();
             }
The documentation for this struct was generated from the following file:
devices.h