HAN-FUN API: HF::Core::GroupManagement::Group Struct Reference
HF::Core::GroupManagement::Group Struct Reference
Core Services & Interfaces » Group Management
This class represents a group of devices.
#include <group_management.h>
Public Member Functions
Group (uint16_t address=0, std::string name="")
Constructor.
const Container & members () const
Return a reference to the members of the group.
Container::iterator find_member (const Member &member)
Find a group member equal to the given member.
Container::iterator find_member (uint16_t device, uint8_t unit)
Find a group member equal to the given member.
bool exists (const Member &member)
Check if a member equal to the given member already exists in the group.
bool exists (uint16_t device, uint8_t unit)
Check if a member equal to the given member already exists in the group.
bool add (const Member &member)
Add the given member to the group.
bool add (uint16_t device, uint8_t unit)
Add the given member to the group.
bool reserve ()
Reserve a member in group members entries.
bool update (const Member &member)
Update a reserved entry with the given member.
bool update (uint16_t device, uint8_t unit)
Update a reserved entry with the given member.
bool remove (const Member &member)
Remove the given member from the entries of the group.
bool remove (uint16_t device, uint8_t unit)
Remove the given member from the entries of the group.
bool operator== (const Group &other) const
Equals operator.
bool operator!= (const Group &other) const
Not equals operator.
Public Member Functions inherited from HF::Core::GroupManagement::GroupAddress
GroupAddress (uint16_t address=0)
Constructor.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
std::string name
Group Name
Data Fields inherited from HF::Core::GroupManagement::GroupAddress
uint16_t address
Group Address
Protected Attributes
Container _members
Group Members
Additional Inherited Members
Static Public Attributes inherited from HF::Core::GroupManagement::GroupAddress
static constexpr uint16_t NO_ADDR = 0x0000
Empty Group Address.
static constexpr uint16_t START_ADDR = 0x0001
First HAN-FUN Group Address.
static constexpr uint16_t END_ADDR = 0x7FFF
Last HAN-FUN Group Address.
static constexpr uint16_t min_size = sizeof(uint16_t)
Minimum pack/unpack required data size.
Detailed Description
This class represents a group of devices.
Definition at line 145 of file group_management.h.
Constructor & Destructor Documentation
Group()
HF::Core::GroupManagement::Group::Group (uint16_t address = 0, std::string name = "") inline
Constructor.
Parameters
[in] address the group's address.
[in] name the group's name.
Definition at line 166 of file group_management.h.
                                                             :
                GroupAddress(address), name(name)
             {}
Member Function Documentation
add() [1/2]
bool HF::Core::GroupManagement::Group::add (const Member & member)
Add the given member to the group.
Parameters
[in] member reference to a member to add to the group.
Return values
true if the member was added;
false otherwise.
Referenced by add().
add() [2/2]
bool HF::Core::GroupManagement::Group::add (uint16_t device, uint8_t unit) inline
Add the given member to the group.
Parameters
[in] device device address for the new member to add.
[in] unit unit ID for the new member to add.
Return values
true if the member was added;
false otherwise.
Definition at line 259 of file group_management.h.
References add().
             {
                const Member member(device, unit);
                return add(member);
             }
exists() [1/2]
bool HF::Core::GroupManagement::Group::exists (const Member & member) inline
Check if a member equal to the given member already exists in the group.
Parameters
[in] member reference to the member to check presence of.
Return values
true if the member is already present in the group;
false otherwise.
Definition at line 219 of file group_management.h.
References find_member(), and members().
             {
                return !(find_member(member) == members().end());
             }
exists() [2/2]
bool HF::Core::GroupManagement::Group::exists (uint16_t device, uint8_t unit) inline
Check if a member equal to the given member already exists in the group.
Parameters
[in] device device address to check the existence for.
[in] unit unit ID to check the existence for.
Return values
true if the member is already present in the group;
false otherwise.
Definition at line 233 of file group_management.h.
References find_member(), and members().
             {
                const Member member(device, unit);
                return !(find_member(member) == members().end());
             }
find_member() [1/2]
Container::iterator HF::Core::GroupManagement::Group::find_member (const Member & member)
Find a group member equal to the given member.
Parameters
[in] member reference to a Member instance to look for.
Return values
iterator to the element in the Container if exists,
Container::end() otherwise.
Referenced by exists(), and find_member().
find_member() [2/2]
Container::iterator HF::Core::GroupManagement::Group::find_member (uint16_t device, uint8_t unit) inline
Find a group member equal to the given member.
Parameters
[in] device device address for the member to look for.
[in] unit unit ID for the member to look for.
Return values
iterator to the element in the Container if exists,
Container::end() otherwise.
Definition at line 203 of file group_management.h.
References find_member().
             {
                const Member member(device, unit);
                return find_member(member);
             }
members()
const Container& HF::Core::GroupManagement::Group::members () const inline
Return a reference to the members of the group.
Returns
reference to the members of the group.
Definition at line 179 of file group_management.h.
References _members.
Referenced by exists(), and reserve().
             {
                return _members;
             }
remove() [1/2]
bool HF::Core::GroupManagement::Group::remove (const Member & member)
Remove the given member from the entries of the group.
Parameters
[in] member reference to the member to remove from the group.
Return values
true if the entry was removed;
false otherwise.
remove() [2/2]
bool HF::Core::GroupManagement::Group::remove (uint16_t device, uint8_t unit) inline
Remove the given member from the entries of the group.
Parameters
device device address of the member to remove.
unit unit ID of the member to remove.
Return values
true if the entry was removed;
false otherwise.
Definition at line 324 of file group_management.h.
             {
                const Member member(device, unit);
                return remove(member);
             }
reserve()
bool HF::Core::GroupManagement::Group::reserve () inline
Reserve a member in group members entries.
Return values
true if the entry was reserved;
false otherwise.
Definition at line 272 of file group_management.h.
References _members, HF_ASSERT, members(), and HF::Core::GroupManagement::GroupAddress::size().
             {
                HF_ASSERT(members().size() < MAX_MEMBERS, {return false;});
                _members.push_back(Member());
                return true;
             }
update() [1/2]
bool HF::Core::GroupManagement::Group::update (const Member & member)
Update a reserved entry with the given member.
Parameters
[in] member reference to the member to update the reserved entry to.
Return values
true if the entry was updated;
false otherwise.
Referenced by update().
update() [2/2]
bool HF::Core::GroupManagement::Group::update (uint16_t device, uint8_t unit) inline
Update a reserved entry with the given member.
Parameters
device device address to update the reserved entry with.
unit unit ID to update the reserved entry with.
Return values
true if the entry was updated;
false otherwise.
Definition at line 298 of file group_management.h.
References update().
             {
                const Member member(device, unit);
                return update(member);
             }
The documentation for this struct was generated from the following file:
group_management.h