HAN-FUN API: HF::Core::GroupTable::Client Struct Reference
HF::Core::GroupTable::Client Struct Reference
Core Services & Interfaces » Group Table
Group Table Service : Client side implementation.
#include <group_table.h>
Public Member Functions
Commands
void add (const Protocol::Address &addr, const Entry &entry)
Send a HAN-FUN message containing a GroupTable::ADD_CMD, to the given network address.
void add (const uint16_t device, const Entry &entry)
Send a HAN-FUN message containing a GroupTable::ADD_CMD, to the given device and the given entry.
void add (const Protocol::Address &addr, uint16_t group, uint8_t unit)
Send a HAN-FUN message containing a GroupTable::ADD_CMD, to the given network address, for the given group and unit.
void add (const uint16_t device, uint16_t group, uint8_t unit)
Send a HAN-FUN message containing a GroupTable::ADD_CMD, to the given device, for the given group and unit.
void remove (const Protocol::Address &addr, const Entry &entry)
Send a HAN-FUN message containing a GroupTable::REMOVE_CMD, to the given network address.
void remove (const uint16_t device, const Entry &entry)
Send a HAN-FUN message containing a GroupTable::REMOVE_CMD, to the given device and the given entry.
void remove (const Protocol::Address &addr, uint16_t group, uint8_t unit)
Send a HAN-FUN message containing a GroupTable::REMOVE_CMD, to the given network address, for the given group and unit.
void remove (const uint16_t device, uint16_t group, uint8_t unit)
Send a HAN-FUN message containing a GroupTable::REMOVE_CMD, to the given device, for the given group and unit.
void remove_all (const Protocol::Address &addr)
Send a HAN-FUN message containing a GroupTable::REMOVE_ALL_CMD, to the given network address.
void remove_all (uint16_t device)
Send a HAN-FUN message containing a GroupTable::REMOVE_ALL_CMD, to the device with the given address.
void read_entries (const Protocol::Address &addr, const ReadEntries &params)
Send a HAN-FUN message containing a GroupTable::READ_ENTRIES_CMD, to the given network address.
void read_entries (const Protocol::Address &addr, const uint8_t offset, const uint8_t count)
Send a HAN-FUN message containing a GroupTable::READ_ENTRIES_CMD, to the given network address.
void read_entries (const uint16_t device, const ReadEntries &params)
Send a HAN-FUN message containing a GroupTable::REMOVE_ALL_CMD, to the device with the given address.
void read_entries (const uint16_t device, const uint8_t offset, const uint8_t count)
Send a HAN-FUN message containing a GroupTable::REMOVE_ALL_CMD, to the device with the given address.
Events
virtual void added (const Protocol::Address &addr, const GroupTable::Response &response)
Callback for processing the response of a GroupTable::ADD_CMD.
virtual void removed (const Protocol::Address &addr, const GroupTable::Response &response)
Callback for processing the response of a GroupTable::REMOVE_CMD.
virtual void removed_all (const Protocol::Address &addr, const Protocol::Response &response)
Callback for processing the response of a GroupTable::REMOVE_ALL_CMD.
virtual void read_entries (const Protocol::Address &addr, const ReadEntriesResponse &response)
Callback for processing the response of a GroupTable::READ_ENTRIES_CMD.
Public Member Functions inherited from HF::Core::ServiceRole< GroupTable::Base, HF::Interface::CLIENT_ROLE >
Interface::Role role () const
Return the Interface::Role this interface implements.
Public Member Functions inherited from HF::Core::Service< HF::Interface::GROUP_TABLE >
uint16_t uid () const
This method returns the interface UID.
Public Member Functions inherited from HF::Core::AbstractService
Unit0 & unit () const
The device this unit is associated with.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
HF::Attributes::UIDS attributes (uint8_t pack_id=HF::Attributes::Pack::MANDATORY) const
Return a vector containing the attribute UIDs, for the given pack ID.
Public Member Functions inherited from HF::Interfaces::AbstractInterface
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void periodic (uint32_t time)
Handle periodic processing.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
Protected Member Functions
Common::Result handle_command (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
uint16_t payload_size (Protocol::Message::Interface &itf) const
Return the minimal payload size that a message should hold when addressed at the given interface.
Protected Member Functions inherited from HF::Core::ServiceRole< GroupTable::Base, HF::Interface::CLIENT_ROLE >
ServiceRole (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Core::GroupTable::Base
Base (Unit0 &unit)
Constructor.
Protected Member Functions inherited from HF::Core::Service< HF::Interface::GROUP_TABLE >
Service (Unit0 &unit)
Constructor.
bool check_uid (uint16_t uid) const
Check if the given uid value matches the service's UID value.
Protected Member Functions inherited from HF::Core::AbstractService
AbstractService (Unit0 &unit)
Constructor.
void send (const Protocol::Address &addr, Protocol::Message &message)
Send message msg to the network address given by addr.
void send (const Protocol::Address &addr, Protocol::Message &message, Transport::Link *link)
Create and send a new packet with the given message to the given address.
Protected Member Functions inherited from HF::Interfaces::AbstractInterface
virtual void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify that an attribute value as changed.
Common::Result check (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if message has correct attributes to be processed by the interface.
Common::Result check_payload_size (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if payload data size if sufficient for processing the message.
virtual uint16_t payload_size (Protocol::Message &message) const
Return the minimal payload size that should be present for the given message.
template<typename _Message >
uint16_t payload_size_helper () const
Helper function template to retrieve minimum size required for serializing/deserializing the class given.
virtual Common::Result handle_attribute (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
Additional Inherited Members
Public Types inherited from HF::Interface
enum Role { CLIENT_ROLE = 0, SERVER_ROLE = 1 }
Interface roles.
enum UID {
DEVICE_MANAGEMENT = 0x0001, BIND_MANAGEMENT = 0x0002, GROUP_MANAGEMENT = 0x0003, IDENTIFY = 0x0004,
DEVICE_INFORMATION = 0x0005, ATTRIBUTE_REPORTING = 0x0006, BATCH_PROGRAM_MANAGEMENT = 0x0007, EVENT_SCHEDULING = 0x0008,
WEEKLY_SCHEDULING = 0x0009, GROUP_TABLE = 0x000A, TAMPER_ALERT = 0x0101, TIME = 0x0102,
POWER = 0x0110, KEEP_ALIVE = 0x0115, RSSI = 0x0111, SUOTA = 0x0400,
ALERT = 0x0100, ON_OFF = 0x0200, LEVEL_CONTROL = 0x0201, COLOUR_CONTROL = 0x0202,
SIMPLE_KEYPAD = 0x0203, SIMPLE_POWER_METER = 0x0300, SIMPLE_TEMPERATURE = 0x0301, SIMPLE_HUMIDITY = 0x0302,
SIMPLE_THERMOSTAT = 0x0303, SIMPLE_BUTTON = 0x0304, SIMPLE_VISUAL_EFFECTS = 0x0305, SIMPLE_AIR_PRESSURE = 0x0306,
SIMPLE_LIGHT_SENSOR = 0x0307, RESERVED = 0x7F00, MAX_UID = 0x7FFE, ANY_UID = 0x7FFF
}
Interfaces Unique Identifiers (UID).
Static Public Attributes inherited from HF::Interface
static constexpr uint8_t MAX_CMD_ID = 0xFF
Maximum value for command IDs in interfaces.
Protected Attributes inherited from HF::Core::AbstractService
Unit0 & _unit
Reference to the unit the service belongs to.
Detailed Description
Group Table Service : Client side implementation.
This class provides the client side of the Group Table interface.
Definition at line 610 of file group_table.h.
Member Function Documentation
add() [1/4]
void HF::Core::GroupTable::Client::add (const Protocol::Address & addr, const Entry & entry)
Send a HAN-FUN message containing a GroupTable::ADD_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] entry the group table entry to add.
Referenced by add().
add() [2/4]
void HF::Core::GroupTable::Client::add (const uint16_t device, const Entry & entry) inline
Send a HAN-FUN message containing a GroupTable::ADD_CMD, to the given device and the given entry.
Parameters
[in] device the device address to send the entry to.
[in] entry the group table entry to add.
Definition at line 638 of file group_table.h.
References add().
             {
                Protocol::Address addr(device, 0);
                add(addr, entry);
             }
add() [3/4]
void HF::Core::GroupTable::Client::add (const Protocol::Address & addr, uint16_t group, uint8_t unit) inline
Send a HAN-FUN message containing a GroupTable::ADD_CMD, to the given network address, for the given group and unit.
Parameters
[in] addr the network address to send the message to.
[in] group the group address for the entry to add.
[in] unit the unit ID for the entry to add.
Definition at line 652 of file group_table.h.
References add(), and HF::Core::AbstractService::unit().
             {
                Entry entry(group, unit);
                add(addr, entry);
             }
add() [4/4]
void HF::Core::GroupTable::Client::add (const uint16_t device, uint16_t group, uint8_t unit) inline
Send a HAN-FUN message containing a GroupTable::ADD_CMD, to the given device, for the given group and unit.
Parameters
[in] device the device address to send the entry to.
[in] group the group address for the entry to add.
[in] unit the unit ID for the entry to add.
Definition at line 667 of file group_table.h.
References add(), and HF::Core::AbstractService::unit().
             {
                Protocol::Address addr(device, 0);
                Entry entry(group, unit);
                add(addr, entry);
             }
added()
virtual void HF::Core::GroupTable::Client::added (const Protocol::Address & addr, const GroupTable::Response & response) virtual
Callback for processing the response of a GroupTable::ADD_CMD.
Parameters
[in] addr address for device that sent the response.
[in] response the response received.
Reimplemented in HF::Core::GroupManagement::GroupTableClient.
handle_command()
Common::Result HF::Core::GroupTable::Client::handle_command (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) protected virtual
Handle incoming messages from the network.
Parameters
[in] packet the packet receive from the network.
[in] payload the byte array containing the data received from the network.
[in] offset the offset the payload start at in the byte array.
Returns
the result of the message processing.
Handle command request/response messages, i.e. :
Protocol::Message:Type::COMMAND_REQ;
Protocol::Message:Type::COMMAND_RESP_REQ;
Protocol::Message:Type::COMMAND_RES;
Reimplemented from HF::Interfaces::AbstractInterface.
payload_size()
uint16_t HF::Core::GroupTable::Client::payload_size (Protocol::Message::Interface & itf) const protected virtual
Return the minimal payload size that a message should hold when addressed at the given interface.
Parameters
[in] itf the interface being address.
Returns
the minimum number of bytes for the message for the interface.
Reimplemented from HF::Interfaces::AbstractInterface.
read_entries() [1/5]
void HF::Core::GroupTable::Client::read_entries (const Protocol::Address & addr, const ReadEntries & params)
Send a HAN-FUN message containing a GroupTable::READ_ENTRIES_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] params parameters to the GroupTable::READ_ENTRIES_CMD.
Referenced by read_entries().
read_entries() [2/5]
void HF::Core::GroupTable::Client::read_entries (const Protocol::Address & addr, const uint8_t offset, const uint8_t count) inline
Send a HAN-FUN message containing a GroupTable::READ_ENTRIES_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] offset offset to start reading the entries from.
[in] count number of entries to read.
Definition at line 763 of file group_table.h.
References read_entries().
             {
                ReadEntries params(offset, count);
                read_entries(addr, params);
             }
read_entries() [3/5]
void HF::Core::GroupTable::Client::read_entries (const uint16_t device, const ReadEntries & params) inline
Send a HAN-FUN message containing a GroupTable::REMOVE_ALL_CMD, to the device with the given address.
Parameters
[in] device the device's network address to send the message to.
[in] params parameters to the GroupTable::READ_ENTRIES_CMD.
Definition at line 778 of file group_table.h.
References read_entries().
             {
                Protocol::Address addr(device, 0);
                read_entries(addr, params);
             }
read_entries() [4/5]
void HF::Core::GroupTable::Client::read_entries (const uint16_t device, const uint8_t offset, const uint8_t count) inline
Send a HAN-FUN message containing a GroupTable::REMOVE_ALL_CMD, to the device with the given address.
Parameters
[in] device the device's network address to send the message to.
[in] offset offset to start reading the entries from.
[in] count number of entries to read.
Definition at line 792 of file group_table.h.
References read_entries().
             {
                Protocol::Address addr(device, 0);
                ReadEntries params(offset, count);
                read_entries(addr, params);
             }
read_entries() [5/5]
virtual void HF::Core::GroupTable::Client::read_entries (const Protocol::Address & addr, const ReadEntriesResponse & response) virtual
Callback for processing the response of a GroupTable::READ_ENTRIES_CMD.
Parameters
[in] addr address for device that sent the response.
[in] response the response received.
remove() [1/4]
void HF::Core::GroupTable::Client::remove (const Protocol::Address & addr, const Entry & entry)
Send a HAN-FUN message containing a GroupTable::REMOVE_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
[in] entry the group table entry to remove.
remove() [2/4]
void HF::Core::GroupTable::Client::remove (const uint16_t device, const Entry & entry) inline
Send a HAN-FUN message containing a GroupTable::REMOVE_CMD, to the given device and the given entry.
Parameters
[in] device the device address to remove the entry from.
[in] entry the group table entry to remove.
Definition at line 690 of file group_table.h.
             {
                Protocol::Address addr(device, 0);
                remove(addr, entry);
             }
remove() [3/4]
void HF::Core::GroupTable::Client::remove (const Protocol::Address & addr, uint16_t group, uint8_t unit) inline
Send a HAN-FUN message containing a GroupTable::REMOVE_CMD, to the given network address, for the given group and unit.
Parameters
[in] addr the network address to send the message to.
[in] group the group address for the entry to remove.
[in] unit the unit ID for the entry to remove.
Definition at line 704 of file group_table.h.
References HF::Core::AbstractService::unit().
             {
                Entry entry(group, unit);
                remove(addr, entry);
             }
remove() [4/4]
void HF::Core::GroupTable::Client::remove (const uint16_t device, uint16_t group, uint8_t unit) inline
Send a HAN-FUN message containing a GroupTable::REMOVE_CMD, to the given device, for the given group and unit.
Parameters
[in] device the device address to send the entry to.
[in] group the group address for the entry to remove.
[in] unit the unit ID for the entry to remove.
Definition at line 719 of file group_table.h.
References HF::Core::AbstractService::unit().
             {
                Protocol::Address addr(device, 0);
                Entry entry(group, unit);
                remove(addr, entry);
             }
remove_all() [1/2]
void HF::Core::GroupTable::Client::remove_all (const Protocol::Address & addr)
Send a HAN-FUN message containing a GroupTable::REMOVE_ALL_CMD, to the given network address.
Parameters
[in] addr the network address to send the message to.
Referenced by remove_all().
remove_all() [2/2]
void HF::Core::GroupTable::Client::remove_all (uint16_t device) inline
Send a HAN-FUN message containing a GroupTable::REMOVE_ALL_CMD, to the device with the given address.
Parameters
[in] device the device's network address to send the message to.
Definition at line 740 of file group_table.h.
References remove_all().
             {
                Protocol::Address addr(device, 0);
                remove_all(addr);
             }
removed()
virtual void HF::Core::GroupTable::Client::removed (const Protocol::Address & addr, const GroupTable::Response & response) virtual
Callback for processing the response of a GroupTable::REMOVE_CMD.
Parameters
[in] addr address for device that sent the response.
[in] response the response received.
removed_all()
virtual void HF::Core::GroupTable::Client::removed_all (const Protocol::Address & addr, const Protocol::Response & response) virtual
Callback for processing the response of a GroupTable::REMOVE_ALL_CMD.
Parameters
[in] addr address for device that sent the response.
[in] response the response received.
The documentation for this struct was generated from the following file:
group_table.h