HAN-FUN API: HF::Attributes::Attribute< T, _Owner, typename > Struct Template Reference
HF::Attributes::Attribute< T, _Owner, typename > Struct Template Reference
Protocol » Attributes
Helper template class to declare an attribute with the given T type.
#include <attributes.h>
Public Member Functions
Attribute (const uint16_t interface, const uint8_t uid, const HF::Interface *__owner, T data, bool writable=false)
Attribute template constructor.
Attribute (const uint16_t interface, const uint8_t uid, bool writable=false)
Attribute template constructor.
Attribute (const uint16_t interface, const uint8_t uid, T data, bool writable=false)
Attribute template constructor.
HF::Interface const * owner () const
Pointer to the interface that owns this attribute.
uint16_t size (bool with_uid) const
Number bytes needed to serialize the message.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset, bool with_uid) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset, bool with_uid)
Read a message from a ByteArray.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
IAttribute * clone () const
Create a clone object of the object where this method is being called.
int compare (const IAttribute &other) const
Compare this attribute with the given attribute in other.
float changed (const IAttribute &other) const
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Public Member Functions inherited from HF::Attributes::AbstractAttribute
uint8_t uid () const
Attribute's UID.
bool isWritable () const
Indicate if the attribute is writable.
uint16_t interface () const
Return the UID of the interface the attribute belongs to.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from HF::Attributes::AbstractAttribute
const uint16_t _itf_uid
Interface this attribute belongs to.
const uint8_t _uid
Attribute unique identifier.
const bool _writable
Attribute access mode.
Detailed Description
template<typename T, typename _Owner = void, typename = void>
struct HF::Attributes::Attribute< T, _Owner, typename >
Helper template class to declare an attribute with the given T type.
Template Parameters
T underling data type for the attribute.
Definition at line 347 of file attributes.h.
Constructor & Destructor Documentation
template<typename T, typename _Owner = void, typename = void> HF::Attributes::Attribute< T, _Owner, typename >::Attribute (const uint16_t interface, const uint8_t uid, const HF::Interface * __owner, T data, bool writable = false) inline
Attribute template constructor.
Parameters
[in] interface attribute's interface UID.
[in] uid attribute's UID.
[in] data attribute's value.
[in] __owner pointer to attribute's interface owner object.
[in] writable attribute's writable information.
Definition at line 358 of file attributes.h.
                                          :
             AbstractAttribute (interface, uid, writable), helper (data), _owner (__owner)
          {}
template<typename T, typename _Owner = void, typename = void> HF::Attributes::Attribute< T, _Owner, typename >::Attribute (const uint16_t interface, const uint8_t uid, bool writable = false) inline
Attribute template constructor.
Parameters
[in] interface attribute's interface UID.
[in] uid attribute's UID.
[in] writable attribute's writable information.
Definition at line 370 of file attributes.h.
                                                                                       :
             AbstractAttribute (interface, uid, writable), _owner (nullptr)
          {}
template<typename T, typename _Owner = void, typename = void> HF::Attributes::Attribute< T, _Owner, typename >::Attribute (const uint16_t interface, const uint8_t uid, T data, bool writable = false) inline
Attribute template constructor.
Parameters
[in] interface attribute's interface UID.
[in] uid attribute's UID.
[in] data attribute's value.
[in] writable attribute's writable information.
Definition at line 382 of file attributes.h.
                                                                                               :
             AbstractAttribute (interface, uid, writable), helper (data), _owner (nullptr)
          {}
Member Function Documentation
template<typename T, typename _Owner = void, typename = void> float HF::Attributes::Attribute< T, _Owner, typename >::changed (const IAttribute< T, _Owner, typename > & other) const inline virtual
This method is used to get the percentage of change that the attribute has in relation to the value present in other.
Parameters
[in] other attribute holding a previous value.
Returns
float indicating the percentage of change.
Implements HF::Attributes::IAttribute.
Definition at line 489 of file attributes.h.
          {
             int res = AbstractAttribute::compare (other);
             if (res == 0)
             {
                Attribute <T> *temp = (Attribute <T> *) & other;
                return helper.changed (temp->helper);
             }
             return 0.0;
          }
template<typename T, typename _Owner = void, typename = void> IAttribute* HF::Attributes::Attribute< T, _Owner, typename >::clone () const inline virtual
Create a clone object of the object where this method is being called.
Returns
a new object that is a clone of this object.
Implements HF::Common::Cloneable< IAttribute >.
Definition at line 470 of file attributes.h.
          {
             return new HF::Attributes::Attribute <T>(this->_itf_uid, this->_uid, this->_owner,
                                                      this->helper.data, this->_writable);
          }
template<typename T, typename _Owner = void, typename = void> int HF::Attributes::Attribute< T, _Owner, typename >::compare (const IAttribute< T, _Owner, typename > & other) const inline virtual
Compare this attribute with the given attribute in other.
This method should return < 0 if this attribute is less that, 0 if it is equal and > 0 if greater that the other attribute.
Parameters
[in] other attribute to compare to.
Return values
<0 if attribute less than other;
0 if attribute equal to other;
>0 if attribute greater than other.
Reimplemented from HF::Attributes::AbstractAttribute.
Definition at line 476 of file attributes.h.
          {
             int res = AbstractAttribute::compare (other);
             if (res == 0)
             {
                Attribute <T> *temp = (Attribute <T> *) & other;
                res = helper.compare (temp->helper);
             }
             return res;
          }
template<typename T, typename _Owner = void, typename = void> HF::Interface const* HF::Attributes::Attribute< T, _Owner, typename >::owner () const inline virtual
Pointer to the interface that owns this attribute.
This can return nullptr if the attribute was created for a remote interface.
Returns
pointer to the interface that owns this attribute, or nullptr if owner is a remote object.
Implements HF::Attributes::IAttribute.
Definition at line 407 of file attributes.h.
          {
             return _owner;
          }
template<typename T, typename _Owner = void, typename = void> uint16_t HF::Attributes::Attribute< T, _Owner, typename >::pack (Common::ByteArray & array, uint16_t offset, bool with_uid) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Parameters
[in] with_uid include uid() in the serialization.
Implements HF::Attributes::IAttribute.
Definition at line 422 of file attributes.h.
          {
             SERIALIZABLE_CHECK (array, offset, size (with_uid));
             uint16_t start = offset;
             if (with_uid)
             {
                offset += array.write (offset, uid ());
             }
             offset += helper.pack (array, offset);
             return offset - start;
          }
template<typename T, typename _Owner = void, typename = void> uint16_t HF::Attributes::Attribute< T, _Owner, typename >::pack (Common::ByteArray & array, uint16_t offset = 0) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Implements HF::Attributes::IAttribute.
Definition at line 438 of file attributes.h.
          {
             return helper.pack (array, offset);
          }
template<typename T, typename _Owner = void, typename = void> uint16_t HF::Attributes::Attribute< T, _Owner, typename >::size (bool with_uid) const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Parameters
[in] with_uid include uid() size in the calculation.
Implements HF::Attributes::IAttribute.
Definition at line 412 of file attributes.h.
          {
             return size () + (with_uid ? sizeof(uint8_t) : 0);
          }
template<typename T, typename _Owner = void, typename = void> uint16_t HF::Attributes::Attribute< T, _Owner, typename >::size () const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Implements HF::Attributes::IAttribute.
Definition at line 417 of file attributes.h.
Referenced by HF::Attributes::Attribute< bool >::pack(), HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::pack(), HF::Attributes::Attribute< bool >::size(), HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::size(), HF::Attributes::Attribute< bool >::unpack(), and HF::Attributes::Attribute< T, _Owner, typename std::enable_if< std::is_base_of< HF::Interface, _Owner >::value >::type >::unpack().
          {
             return helper.size ();
          }
template<typename T, typename _Owner = void, typename = void> uint16_t HF::Attributes::Attribute< T, _Owner, typename >::unpack (const Common::ByteArray & array, uint16_t offset, bool with_uid) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Warning
If with_uid == true, then if the value read from the array does not match the attribute's UID, no more data will be read.
Parameters
[in] with_uid attribute UID is included in the serialization.
Implements HF::Attributes::IAttribute.
Definition at line 443 of file attributes.h.
          {
             SERIALIZABLE_CHECK (array, offset, size (with_uid));
             uint16_t start = offset;
             if (with_uid)
             {
                uint8_t temp;
                offset += array.read (offset, temp);
                if (temp != uid ())
                {
                   return 0;
                }
             }
             offset += helper.unpack (array, offset);
             return offset - start;
          }
template<typename T, typename _Owner = void, typename = void> uint16_t HF::Attributes::Attribute< T, _Owner, typename >::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Implements HF::Attributes::IAttribute.
Definition at line 465 of file attributes.h.
          {
             return helper.unpack (array, offset);
          }
The documentation for this struct was generated from the following file:
attributes.h