HAN-FUN API: HF::UID::URI Struct Reference
HF::UID::URI Struct Reference
Devices » UIDs
URI UID class.
#include <uids.h>
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
URI * clone () const
Create a clone object of the object where this method is being called.
int compare (const UID_T &other) const
Compare the current UID with the given UID.
std::string str () const
Return the string value associated with this URI.
Public Member Functions inherited from HF::Common::Serializable
virtual ~Serializable ()
Destructor.
Additional Inherited Members
Static Public Attributes inherited from HF::UID::UID_T
static constexpr uint16_t min_size
Minimum pack/unpack required data size.
Detailed Description
URI UID class.
Definition at line 431 of file uids.h.
Member Function Documentation
clone()
URI* HF::UID::URI::clone () const inline virtual
Create a clone object of the object where this method is being called.
Returns
a new object that is a clone of this object.
Implements HF::Common::Cloneable< UID_T >.
Definition at line 495 of file uids.h.
          {
             return new URI(*this);
          }
compare()
int HF::UID::URI::compare (const UID_T & other) const inline virtual
Compare the current UID with the given UID.
This function returns a value less that 0 if the current UID object order is lower that the given UID, 0 if the UIDs represent the same entity and a value greater that 0 if current UID object is above the given UID.
Parameters
[in] other a pointer to a UID object to compare to.
Return values
<0 the current UID is lower that the given UID.
0 the current UID is the same as given UID.
>0 the current UID is greater that the given UID.
Reimplemented from HF::UID::UID_T.
Definition at line 504 of file uids.h.
References HF::UID::UID_T::compare().
          {
             int res = Abstract<URI_UID>::compare(other);
             return (res == 0 ? value.compare(((URI *) &other)->value) : res);
          }
pack()
uint16_t HF::UID::URI::pack (Common::ByteArray & array, uint16_t offset = 0) const inline virtual
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Reimplemented from HF::UID::UID_T.
Definition at line 447 of file uids.h.
References HF_SERIALIZABLE_CHECK, HF::UID::UID_T::pack(), size(), and HF::Common::ByteArray::write().
          {
             HF_SERIALIZABLE_CHECK(array, offset, size());
             uint16_t start = offset;
             offset += Abstract<URI_UID>::pack(array, offset);
             assert(value.size() <= 0xFF);
             offset += array.write(offset, (uint8_t) value.size());
             for (uint8_t i = 0; i < value.size(); i++)
             {
                offset += array.write(offset, (uint8_t) value[i]);
             }
             return offset - start;
          }
size()
uint16_t HF::UID::URI::size () const inline virtual
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Reimplemented from HF::UID::UID_T.
Definition at line 442 of file uids.h.
References HF::UID::UID_T::size().
Referenced by pack(), and unpack().
          {
             return Abstract<URI_UID>::size() + value.size();
          }
str()
std::string HF::UID::URI::str () const inline
Return the string value associated with this URI.
Returns
the string associated with this URI.
Definition at line 516 of file uids.h.
          {
             return value;
          }
unpack()
uint16_t HF::UID::URI::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline virtual
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Reimplemented from HF::UID::UID_T.
Definition at line 466 of file uids.h.
References HF_SERIALIZABLE_CHECK, HF::UID::UID_T::min_size, HF::Common::ByteArray::read(), size(), and HF::UID::UID_T::unpack().
          {
             HF_SERIALIZABLE_CHECK(array, offset, min_size);
             uint16_t start = offset;
             offset += Abstract<URI_UID>::unpack(array, offset);
             uint8_t size;
             offset += array.read(offset, size);
             HF_SERIALIZABLE_CHECK(array, offset, size);
             value = std::string(size, 0);
             for (uint8_t i = 0; i < size; i++)
             {
                uint8_t c;
                offset  += array.read(offset, c);
                value[i] = c;
             }
             return offset - start;
          }
The documentation for this struct was generated from the following file:
uids.h