HAN-FUN API: HF::Attributes::UIDS Struct Reference
HF::Attributes::UIDS Struct Reference
Protocol » Attributes
List of attributes UIDs.
#include <attributes.h>
Inherits std::vector< T >.
Public Member Functions
UIDS (std::initializer_list< uint8_t > uids)
Constructor.
vector< uint8_t >::size_type length () const
Number of elements in the list.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset, uint8_t &count)
Read a message from a ByteArray.
Static Public Attributes
static constexpr uint8_t min_size = sizeof(uint8_t)
Minimum pack/unpack required data size.
Detailed Description
List of attributes UIDs.
Definition at line 173 of file attributes.h.
Constructor & Destructor Documentation
HF::Attributes::UIDS::UIDS (std::initializer_list< uint8_t > uids) inline
Constructor.
Parameters
[in] uids attributes UIDs list.
Definition at line 183 of file attributes.h.
                                                  :vector <uint8_t>(uids)
          {}
Member Function Documentation
vector<uint8_t>::size_type HF::Attributes::UIDS::length () const inline
Number of elements in the list.
Note
this is used as an alias to the underling method, std::vector<uint8_t>::size, as the size method signature is used to provide a Serializable type interface.
Returns
number of elements.
Definition at line 195 of file attributes.h.
Referenced by pack().
          {
             return vector <uint8_t>::size ();
          }
uint16_t HF::Attributes::UIDS::pack (Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 210 of file attributes.h.
References length(), SERIALIZABLE_CHECK, size(), and HF::Common::ByteArray::write().
Referenced by HF::Protocol::GetAttributePack::Request::pack().
          {
             SERIALIZABLE_CHECK (array, offset, size ());
             uint16_t start = offset;
             uint8_t  count = length ();
             offset += array.write (offset, count);
             /* *INDENT-OFF* */
             std::for_each (vector<uint8_t>::begin(), vector<uint8_t>::end(),
                            [&offset,&array](uint8_t uid)
             {
                offset += array.write (offset, uid);
             });
             /* *INDENT-ON* */
             return offset - start;
          }
uint16_t HF::Attributes::UIDS::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 204 of file attributes.h.
Referenced by pack(), and HF::Protocol::GetAttributePack::Request::size().
          {
             return min_size + sizeof(uint8_t) * vector <uint8_t>::size ();
          }
uint16_t HF::Attributes::UIDS::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 231 of file attributes.h.
Referenced by HF::Protocol::GetAttributePack::Request::unpack().
          {
             uint8_t count = 0;
             return unpack (array, offset, count);
          }
uint16_t HF::Attributes::UIDS::unpack (const Common::ByteArray & array, uint16_t offset, uint8_t & count) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Parameters
[out] count reference to a variable that will hold the count value read from the array.
Definition at line 243 of file attributes.h.
References HF::Common::ByteArray::read(), and SERIALIZABLE_CHECK.
          {
             SERIALIZABLE_CHECK (array, offset, min_size);
             uint16_t start = offset;
             offset += array.read (offset, count);
             SERIALIZABLE_CHECK (array, offset, count);
             vector <uint8_t>::reserve (count);
             for (uint8_t i = 0; i < count; i++)
             {
                uint8_t uid;
                offset += array.read (offset, uid);
                vector <uint8_t>::push_back (uid);
             }
             return offset - start;
          }
The documentation for this struct was generated from the following file:
attributes.h