HAN-FUN API: HF::Common::ByteArray Struct Reference
HF::Common::ByteArray Struct Reference
Common
This class represents a byte array.
#include <common.h>
Inherits std::vector< T >.
Public Member Functions
ByteArray (uint16_t size=0)
Create a byte array with the given initial size.
ByteArray (const uint8_t data[], const uint16_t size)
Create a byte array with the given initial data.
ByteArray (std::initializer_list< uint8_t > raw)
Create byte array from the values in the given list.
virtual ~ByteArray ()
Destructor.
uint16_t write (uint16_t offset, uint8_t data)
Write a byte into the array at the given offset.
uint16_t write (uint16_t offset, uint16_t data)
Write a word in the big endian format into the array at the given offset.
uint16_t write (uint16_t offset, uint32_t data)
Write a double-word in big endian format into the array at the given offset.
uint16_t write (uint16_t offset, bool data)
Write a byte into the array at the given offset. (uint16_t, uint8_t)
template<typename T >
uint16_t write (uint16_t offset, T data)
Write a byte into the array at the given offset. (uint16_t, uint8_t)
uint16_t read (uint16_t offset, uint8_t &data) const
Read the byte at offset into data.
uint16_t read (uint16_t offset, uint16_t &data) const
Read the word in big-endian format at offset into data.
uint16_t read (uint16_t offset, uint32_t &data) const
Read the double-word in big-endian format at offset into data.
uint16_t read (uint16_t offset, bool &data) const
Read the byte at offset into data. (uint16_t, uint8_t)
template<typename T >
uint16_t read (uint16_t offset, T &data) const
Read the byte at offset into data. (uint16_t, uint8_t)
bool available (uint16_t offset, uint16_t expected) const
Check if the array as at least expected bytes available from the given offset.
uint16_t available (uint16_t offset) const
Return the number of data bytes available from the given offset.
void extend (uint16_t _size)
Extend the byte array by the given size.
void ensure (uint16_t _offset, uint16_t _size)
Ensure that the byte array can hold the number of bytes given in _size, from the given offset.
Detailed Description
This class represents a byte array.
The method in this class are used to serialize the messages to be sent over the network, converting between the host's endianness and the big-endian network format.
Definition at line 239 of file inc/hanfun/common.h.
Constructor & Destructor Documentation
ByteArray() [1/3]
HF::Common::ByteArray::ByteArray (uint16_t size = 0)
Create a byte array with the given initial size.
Parameters
[in] size the initial size of the byte array.
ByteArray() [2/3]
HF::Common::ByteArray::ByteArray (const uint8_t data[], const uint16_t size)
Create a byte array with the given initial data.
Parameters
[in] data data to initialize the byte array with.
[in] size size in bytes of the data.
ByteArray() [3/3]
HF::Common::ByteArray::ByteArray (std::initializer_list< uint8_t > raw) inline
Create byte array from the values in the given list.
Parameters
[in] raw values to add to the byte array.
Definition at line 261 of file inc/hanfun/common.h.
                                                     : vector(raw)
          {}
Member Function Documentation
available() [1/2]
bool HF::Common::ByteArray::available (uint16_t offset, uint16_t expected) const inline
Check if the array as at least expected bytes available from the given offset.
Parameters
[in] offset the offset from where to start counting.
[in] expected the number of byte required.
Return values
true if enough data is available,
false otherwise.
Definition at line 377 of file inc/hanfun/common.h.
Referenced by ensure().
          {
             return expected <= available(offset);
          }
available() [2/2]
uint16_t HF::Common::ByteArray::available (uint16_t offset) const inline
Return the number of data bytes available from the given offset.
Parameters
[in] offset the offset from where to start counting.
Returns
number of data bytes available from the given offset.
Definition at line 389 of file inc/hanfun/common.h.
          {
             return (size() >= offset ? size() - offset : 0);
          }
ensure()
void HF::Common::ByteArray::ensure (uint16_t _offset, uint16_t _size) inline
Ensure that the byte array can hold the number of bytes given in _size, from the given offset.
Parameters
[in] _offset offset index to check from.
[in] _size number of bytes to ensure that exist.
Definition at line 424 of file inc/hanfun/common.h.
References available().
          {
             if (!available(_offset, _size))
             {
                _size = _size - available(_offset) + std::max<int16_t>(
                   (int16_t) (_offset - size()), 0);
                vector<uint8_t>::reserve(size() + _size);
                std::fill_n(back_inserter(*this), _size, 0);
             }
          }
extend()
void HF::Common::ByteArray::extend (uint16_t _size) inline
Extend the byte array by the given size.
This is the same as calling : array.reserve(array.size() + _size)
Parameters
[in] _size number of bytes to extent the array by.
Definition at line 412 of file inc/hanfun/common.h.
          {
             vector<uint8_t>::reserve(size() + _size);
          }
read() [1/5]
uint16_t HF::Common::ByteArray::read (uint16_t offset, uint8_t & data) const
Read the byte at offset into data.
Parameters
[in] offset offset to read the byte from.
[out] data reference to save the read value to.
Returns
number of bytes read (1).
Referenced by read(), HF::Interfaces::SimpleVisualEffects::OnEffect::unpack(), msg_t::unpack(), HF::UID::UID_T::unpack(), HF::Core::SessionManagement::GetEntriesMessage::unpack(), HF::UID::NONE::unpack(), HF::Interfaces::SimpleVisualEffects::BlinkEffect::unpack(), HF::Interfaces::SimplePowerMeter::Measurement::unpack(), hello_msg_t::unpack(), HF::Interfaces::SimpleVisualEffects::FadeEffect::unpack(), HF::Attributes::UIDS::unpack(), HF::UID::ByteArray< MAC, 6, MAC_UID >::unpack(), HF::Core::Scheduling::Entry< _Type >::unpack(), HF::Core::GroupTable::ReadEntries::unpack(), HF::Core::SUOTA::UpgradeStatus::unpack(), HF::Interfaces::SimpleVisualEffects::BreatheEffect::unpack(), HF::Core::GroupTable::ReadEntriesResponse::unpack(), HF::Attributes::Attribute< bool >::unpack(), HF::UID::URI::unpack(), HF::Common::SerializableHelper< T, EnableIf(IsIntegral(T))>::unpack(), HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::unpack(), HF::Common::SerializableHelper< Common::ByteArray >::unpack(), and HF::Protocol::SetAttributePack::Response::Result::unpack().
read() [2/5]
uint16_t HF::Common::ByteArray::read (uint16_t offset, uint16_t & data) const
Read the word in big-endian format at offset into data.
Parameters
[in] offset offset to read the word from.
[out] data reference to save the read value to.
Returns
number of bytes read (2).
read() [3/5]
uint16_t HF::Common::ByteArray::read (uint16_t offset, uint32_t & data) const
Read the double-word in big-endian format at offset into data.
Parameters
[in] offset offset to read the double-word from.
[out] data reference to save the read value to.
Returns
number of bytes read (4).
read() [4/5]
uint16_t HF::Common::ByteArray::read (uint16_t offset, bool & data) const inline
Read the byte at offset into data. (uint16_t, uint8_t)
Parameters
[in] offset offset to read the byte from.
[out] data reference to save the read value to.
Returns
number of bytes read (1). (uint16_t, uint8_t)
Definition at line 344 of file inc/hanfun/common.h.
References read().
          {
             uint8_t temp;
             uint16_t result = read(offset, temp);
             data = (temp & 0x01) != 0;
             return result;
          }
read() [5/5]
template<typename T > uint16_t HF::Common::ByteArray::read (uint16_t offset, T & data) const inline
Read the byte at offset into data. (uint16_t, uint8_t)
Parameters
[in] offset offset to read the byte from.
[out] data reference to save the read value to.
Returns
number of bytes read (1). (uint16_t, uint8_t)
Definition at line 356 of file inc/hanfun/common.h.
References read().
          {
             typedef typename std::make_unsigned<T>::type Type;
             Type temp;
             uint16_t result = read(offset, temp);
             data = static_cast<T>(temp);
             return result;
          }
write() [1/5]
uint16_t HF::Common::ByteArray::write (uint16_t offset, uint8_t data)
Write a byte into the array at the given offset.
Parameters
[in] offset offset to write the byte to.
[in] data byte value to write to the array.
Returns
number of bytes written (1).
Referenced by msg_t::pack(), HF::Interfaces::SimpleVisualEffects::OnEffect::pack(), HF::UID::UID_T::pack(), HF::Core::SessionManagement::GetEntriesMessage::pack(), HF::UID::NONE::pack(), HF::Interfaces::SimpleVisualEffects::BlinkEffect::pack(), hello_msg_t::pack(), HF::Interfaces::SimplePowerMeter::Measurement::pack(), HF::Interfaces::SimpleVisualEffects::FadeEffect::pack(), HF::UID::ByteArray< MAC, 6, MAC_UID >::pack(), HF::Core::Scheduling::Entry< _Type >::pack(), HF::Core::SUOTA::UpgradeStatus::pack(), HF::Core::GroupTable::ReadEntries::pack(), HF::Interfaces::SimpleVisualEffects::BreatheEffect::pack(), HF::Core::GroupTable::ReadEntriesResponse::pack(), HF::Attributes::Attribute< bool >::pack(), HF::UID::URI::pack(), HF::Common::SerializableHelper< T, EnableIf(IsIntegral(T))>::pack(), HF::Attributes::Attribute< T, _Owner, EnableIf(IsParent(HF::Interface, _Owner))>::pack(), HF::Common::SerializableHelper< Common::ByteArray >::pack(), HF::Protocol::SetAttributePack::Response::Result::pack(), and write().
write() [2/5]
uint16_t HF::Common::ByteArray::write (uint16_t offset, uint16_t data)
Write a word in the big endian format into the array at the given offset.
Parameters
[in] offset offset to write the word to.
[in] data word value to write to the array.
Returns
number of bytes written (2).
write() [3/5]
uint16_t HF::Common::ByteArray::write (uint16_t offset, uint32_t data)
Write a double-word in big endian format into the array at the given offset.
Parameters
[in] offset offset to write the double-word to.
[in] data double-word value to write to the array.
Returns
number of bytes written (4).
write() [4/5]
uint16_t HF::Common::ByteArray::write (uint16_t offset, bool data) inline
Write a byte into the array at the given offset. (uint16_t, uint8_t)
Parameters
[in] offset offset to write the byte to.
[in] data byte value to write to the array.
Returns
number of bytes written (1). (uint16_t, uint8_t)
Definition at line 300 of file inc/hanfun/common.h.
References write().
          {
             return write(offset, static_cast<uint8_t>(data ? 0x01 : 0x00));
          }
write() [5/5]
template<typename T > uint16_t HF::Common::ByteArray::write (uint16_t offset, T data) inline
Write a byte into the array at the given offset. (uint16_t, uint8_t)
Parameters
[in] offset offset to write the byte to.
[in] data byte value to write to the array.
Returns
number of bytes written (1). (uint16_t, uint8_t)
Definition at line 307 of file inc/hanfun/common.h.
References write().
          {
             typedef typename std::make_unsigned<T>::type Type;
             return write(offset, static_cast<Type>(data));
          }
The documentation for this struct was generated from the following file:
inc/hanfun/common.h