HAN-FUN API: HF::Protocol::Response Struct Reference
HF::Protocol::Response Struct Reference
Protocol
Parent class for the response messages.
#include <protocol.h>
Public Member Functions
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Static Public Attributes
static constexpr uint16_t min_size = sizeof(uint8_t)
Minimum number of bytes required by this message.
Detailed Description
Parent class for the response messages.
Definition at line 368 of file protocol.h.
Member Function Documentation
uint16_t HF::Protocol::Response::pack (Common::ByteArray & array, uint16_t offset = 0) const
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Referenced by HF::Core::SUOTA::CheckVersionResponse::pack(), HF::Core::GroupTable::Response::pack(), HF::Core::GroupTable::ReadEntriesResponse::pack(), HF::Core::Scheduling::GetEntryResponse< _Type >::pack(), and HF::Attributes::Response::Response().
uint16_t HF::Protocol::Response::size () const
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Referenced by HF::Attributes::Response::Response(), HF::Core::SUOTA::CheckVersionResponse::size(), HF::Core::GroupTable::Response::size(), and HF::Core::GroupTable::ReadEntriesResponse::size().
uint16_t HF::Protocol::Response::unpack (const Common::ByteArray & array, uint16_t offset = 0)
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Referenced by HF::Attributes::Response::Response(), HF::Core::SUOTA::CheckVersionResponse::unpack(), HF::Core::GroupTable::Response::unpack(), HF::Core::GroupTable::ReadEntriesResponse::unpack(), and HF::Core::Scheduling::GetEntryResponse< _Type >::unpack().
The documentation for this struct was generated from the following file:
protocol.h