HAN-FUN API: HF::Transport::Endpoint Struct Reference
HF::Transport::Endpoint Struct Reference abstract
Devices » Transport Layer API
This is the interface used by the transport layer to signal events comming in from the network.
#include <transport.h>
Public Member Functions
Events
virtual void connected (Link *link)=0
Callback to report that a new transport link was been created to a remote device.
virtual void disconnected (Link *link)=0
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
virtual void receive (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)=0
Callback to deliver a packet received from the transport layer.
Detailed Description
This is the interface used by the transport layer to signal events comming in from the network.
Definition at line 89 of file inc/hanfun/transport.h.
Member Function Documentation
virtual void HF::Transport::Endpoint::connected (Link * link) pure virtual
Callback to report that a new transport link was been created to a remote device.
This link can then be used by the local end-point to send messages to the remote end-point.
Parameters
[in] link pointer to the created link.
Implemented in HF::Devices::Concentrator::AbstractBase, HF::Devices::Node::Abstract< CoreServices >, HF::Devices::Node::Abstract< NodeUnit0 >, and HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >.
Referenced by HF::Devices::Node::Transport::add(), HF::Devices::Concentrator::Transport::add(), and HF::Transport::AbstractLayer::connected().
virtual void HF::Transport::Endpoint::disconnected (Link * link) pure virtual
Callback to the report that the given transport link no longer is valid and MUST not be used to send messages to the corresponding end-point.
At the time of this method call the link MUST not be used to send any further messages to the remote end-point.
Parameters
[in] link pointer to the link disconnected.
Implemented in HF::Devices::Concentrator::AbstractBase, HF::Devices::Node::Abstract< CoreServices >, HF::Devices::Node::Abstract< NodeUnit0 >, and HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >.
Referenced by HF::Transport::AbstractLayer::disconnected().
virtual void HF::Transport::Endpoint::receive (Protocol::Packet & packet, Common::ByteArray & payload, uint16_t offset) pure virtual
Callback to deliver a packet received from the transport layer.
Parameters
[in] packet reference to the received packet.
[in] payload reference a ByteArray containing the received data.
[in] offset offset from where the received data starts on the payload byte array buffer.
Implemented in HF::Devices::Concentrator::AbstractBase, HF::Devices::Node::Abstract< CoreServices >, HF::Devices::Node::Abstract< NodeUnit0 >, HF::Devices::Node::Abstract< HF::Devices::Node::DefaultUnit0 >, Base, HF::Devices::AbstractDevice, and Node.
Referenced by HF::Transport::AbstractLayer::receive().
The documentation for this struct was generated from the following file:
inc/hanfun/transport.h