HAN-FUN API: HF::Core::Scheduling::Entries< _Type > Struct Template Reference
HF::Core::Scheduling::Entries< _Type > Struct Template Reference
Core Services & Interfaces » Scheduling Services (Common)
Default implementation of the persistence API.
#include <scheduling.h>
Public Member Functions
uint16_t size () const
Return the number of entries in the container.
Common::Result save (const EntryType &entry)
Store the given entry to persistent storage.
Common::Result save (uint8_t id, uint8_t status, _Type &time, uint8_t pid)
Store the given entry to persistent storage.
void clear (void)
Erase all the DB entries.
Common::Result destroy (const uint8_t id)
Destroy the given entry in the persistent storage.
Common::Result destroy (const EntryType &entry)
Destroy the given entry in the persistent storage.
EntryPointer find (uint8_t id) const
Find the Event with the given id.
void for_each (std::function< void(Entry< _Type > &)> func)
Call the given function with each entry in the DB as argument.
uint8_t next_id () const
Return next available id for event.
iterator begin ()
Get an iterator to the start of the entries in this container.
iterator end ()
Get an iterator to the end of the entries in this container.
const_iterator begin () const
Get a constant iterator to the start of the entries in this container.
const_iterator end () const
Get a constant iterator to the start of the entries in this container.
Public Member Functions inherited from HF::Core::Scheduling::IEntries< _Type >
virtual void for_each (std::function< void(EntryType &e)> func)=0
Call the given function with each entry in the DB as argument.
Public Member Functions inherited from HF::Common::IEntries< Entry< _Type > >
virtual Result save (const Entry< _Type > &entry)=0
Store the given entry to persistent storage.
virtual Result destroy (const Entry< _Type > &entry)=0
Destroy the given entry in the persistent storage.
Protected Member Functions
bool exists (const uint8_t id) const
Check if entry with given id exists.
Protected Attributes
Container db
Actual container for the entries.
Additional Inherited Members
Public Types inherited from HF::Core::Scheduling::IEntries< _Type >
typedef Entry< _Type > EntryType
Entry helper type.
typedef Common::Pointer< EntryType > EntryPointer
Entry pointer helper.
Detailed Description
template<typename _Type>
struct HF::Core::Scheduling::Entries< _Type >
Default implementation of the persistence API.
Template Parameters
_Type the specific type of the scheduling entry.
Definition at line 536 of file scheduling.h.
Member Function Documentation
begin() [1/2]
template<typename _Type > iterator HF::Core::Scheduling::Entries< _Type >::begin () inline
Get an iterator to the start of the entries in this container.
Returns
iterator to the start of the entries present in this container.
Definition at line 672 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db.
             {
                return db.begin();
             }
begin() [2/2]
template<typename _Type > const_iterator HF::Core::Scheduling::Entries< _Type >::begin () const inline
Get a constant iterator to the start of the entries in this container.
Returns
constant iterator to the start of the entries present in this container.
Definition at line 692 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db.
             {
                return db.cbegin();
             }
destroy() [1/2]
template<typename _Type > Common::Result HF::Core::Scheduling::Entries< _Type >::destroy (const uint8_t id) inline
Destroy the given entry in the persistent storage.
Parameters
[in] id the Event ID to destroy
Return values
Common::Result::OK,if the entry was destroyed.
Common::Result::FAIL_ARG otherwise.
Definition at line 601 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db, HF::Core::Scheduling::Entries< _Type >::exists(), HF::Common::FAIL_ARG, HF::Core::Scheduling::Entry< _Type >::id, and HF::Common::OK.
Referenced by HF::Core::Scheduling::Entries< _Type >::destroy().
             {
                if (exists(id))
                {
                   db.remove_if([id](const EntryType &e) {return e.id == id;});
                   return Common::Result::OK;
                }
                else
                {
                   return Common::Result::FAIL_ARG;
                }
             }
destroy() [2/2]
template<typename _Type > Common::Result HF::Core::Scheduling::Entries< _Type >::destroy (const EntryType & entry) inline
Destroy the given entry in the persistent storage.
Parameters
[in] entry reference to the entry to erase.
Return values
Common::Result::OK,if the entry was destroyed.
Common::Result::FAIL_ARG otherwise.
Warning
the reference passed into this method SHOULD NOT be considered valid if it was obtained by calling the find method.
Definition at line 620 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::destroy(), and HF::Core::Scheduling::Entry< _Type >::id.
             {
                return destroy(entry.id);
             }
end() [1/2]
template<typename _Type > iterator HF::Core::Scheduling::Entries< _Type >::end () inline
Get an iterator to the end of the entries in this container.
Returns
iterator to the end of the entries present in this container.
Definition at line 682 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db.
             {
                return db.end();
             }
end() [2/2]
template<typename _Type > const_iterator HF::Core::Scheduling::Entries< _Type >::end () const inline
Get a constant iterator to the start of the entries in this container.
Returns
constant iterator to the start of the entries present in this container.
Definition at line 702 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db.
             {
                return db.cend();
             }
exists()
template<typename _Type > bool HF::Core::Scheduling::Entries< _Type >::exists (const uint8_t id) const inline protected
Check if entry with given id exists.
Parameters
[in] id the entry ID to search for.
Return values
true if the entry already exists,
false otherwise.
Definition at line 717 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db.
Referenced by HF::Core::Scheduling::Entries< _Type >::destroy(), HF::Core::Scheduling::Entries< _Type >::next_id(), and HF::Core::Scheduling::Entries< _Type >::save().
             {
                return std::any_of(db.begin(), db.end(), [id](const EntryType &e) {
                   return e.id == id;
                });
             }
find()
template<typename _Type > EntryPointer HF::Core::Scheduling::Entries< _Type >::find (uint8_t id) const inline virtual
Find the Event with the given id.
Parameters
[in] id Event ID to search for.
Returns
pointer to the entry with the given id, nullptr otherwise.
Implements HF::Core::Scheduling::IEntries< _Type >.
Definition at line 626 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db.
             {
                auto it = std::find_if(db.begin(), db.end(),
                                       [id](const EntryType &e)
                                       {return e.id == id;});
                if (it == db.end())
                {
                   return EntryPointer();
                }
                else
                {
                   return EntryPointer(const_cast<EntryType *>(&(*it)));
                }
             }
for_each()
template<typename _Type > void HF::Core::Scheduling::Entries< _Type >::for_each (std::function< void(Entry< _Type > &)> func) inline
Call the given function with each entry in the DB as argument.
Parameters
[in] func function to apply to all entries in the store.
Definition at line 643 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db.
             {
                std::for_each(db.begin(), db.end(), func);
             }
next_id()
template<typename _Type > uint8_t HF::Core::Scheduling::Entries< _Type >::next_id () const inline virtual
Return next available id for event.
Returns
the id to use in the next event, or Scheduler::Entry::AVAILABLE_ID if no id is available.
Implements HF::Core::Scheduling::IEntries< _Type >.
Definition at line 649 of file scheduling.h.
References HF::Core::Scheduling::Entry< _Type >::AVAILABLE_ID, HF::Core::Scheduling::Entries< _Type >::db, HF::Core::Scheduling::Entries< _Type >::exists(), HF::Core::Scheduling::Entry< _Type >::MAX_ID, and HF::Core::Scheduling::Entry< _Type >::START_ID.
             {
                if (std::distance(db.begin(), db.end()) > EntryType::MAX_ID)
                {
                   return EntryType::AVAILABLE_ID;
                }
                for (uint8_t id = EntryType::START_ID; id <= EntryType::MAX_ID; ++id)
                {
                   if (!exists(id))
                   {
                      return id;
                   }
                }
                return EntryType::AVAILABLE_ID;
             }
save() [1/2]
template<typename _Type > Common::Result HF::Core::Scheduling::Entries< _Type >::save (const EntryType & entry) inline virtual
Store the given entry to persistent storage.
Parameters
[in] entry the entry to save to storage.
Return values
Common::Result::OK if the entry was saved,
Common::Result::FAIL_UNKNOWN otherwise.
Implements HF::Core::Scheduling::IEntries< _Type >.
Definition at line 555 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db, HF::Core::Scheduling::Entries< _Type >::exists(), HF::Common::FAIL_ARG, HF::Core::Scheduling::Entry< _Type >::id, and HF::Common::OK.
Referenced by HF::Core::Scheduling::Entries< _Type >::save().
             {
                if (exists(entry.id))
                {
                   return Common::Result::FAIL_ARG;
                }
                else
                {
                   db.push_front(entry);
                   return Common::Result::OK;
                }
             }
save() [2/2]
template<typename _Type > Common::Result HF::Core::Scheduling::Entries< _Type >::save (uint8_t id, uint8_t status, _Type & time, uint8_t pid) inline
Store the given entry to persistent storage.
Parameters
[in] id entry's ID.
[in] status entry's status.
[in] time entry's time.
[in] pid entry's PID.
Return values
Common::Result::OK if the entry was saved,
Common::Result::FAIL_UNKNOWN otherwise.
Definition at line 579 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::save().
             {
                EntryType entry(id, status, time, pid);
                return save(entry);
             }
size()
template<typename _Type > uint16_t HF::Core::Scheduling::Entries< _Type >::size () const inline virtual
Return the number of entries in the container.
Returns
the number of entries in the container.
Implements HF::Common::IEntries< Entry< _Type > >.
Definition at line 549 of file scheduling.h.
References HF::Core::Scheduling::Entries< _Type >::db.
             {
                return std::distance(db.begin(), db.end());
             }
The documentation for this struct was generated from the following file:
scheduling.h