HAN-FUN API: HF::Core::Scheduling::Entry< _Type > Struct Template Reference
HF::Core::Scheduling::Entry< _Type > Struct Template Reference
Core Services & Interfaces » Scheduling Services (Common)
Base class for scheduling services entries.
#include <scheduling.h>
Public Member Functions
Entry (uint8_t _id, uint8_t _status, _Type _t, uint8_t _pid)
Constructor.
bool active (uint32_t _time) const
Check if the current entry is runnable at _time.
void step (void)
Increment the next_run attribute.
uint16_t size () const
Number bytes needed to serialize the message.
uint16_t pack (Common::ByteArray &array, uint16_t offset=0) const
Write the object on to a ByteArray so it can be sent over the network.
uint16_t unpack (const Common::ByteArray &array, uint16_t offset=0)
Read a message from a ByteArray.
Data Fields
uint8_t id
Event ID.
bool status
Event Status.
_Type time
Scheduler configuration.
uint8_t pid
Program ID to be invoked.
uint32_t next_run
Next run timestamp.
Static Public Attributes
static constexpr uint16_t START_ID = 0x00
Lower bound for the entries ID.
static constexpr uint16_t MAX_ID = 0xFE
Upper bound for the entries ID.
static constexpr uint16_t AVAILABLE_ID = 0xFF
Special ID for system allocated ID.
static constexpr uint16_t min_size
Minimum pack/unpack required data size.
Detailed Description
template<typename _Type>
struct HF::Core::Scheduling::Entry< _Type >
Base class for scheduling services entries.
Template Parameters
_Type the specific data for scheduling service entry.
Definition at line 175 of file scheduling.h.
Constructor & Destructor Documentation
template<typename _Type> HF::Core::Scheduling::Entry< _Type >::Entry (uint8_t _id, uint8_t _status, _Type _t, uint8_t _pid) inline
Constructor.
Parameters
[in] _id the entry ID.
[in] _status the entry status.
[in] _t the specific data for the scheduling service.
[in] _pid the batch program ID to be run.
Definition at line 193 of file scheduling.h.
                                                                        :
                id(_id), status(_status), time(_t), pid(_pid), next_run(time.first())
             {}
Member Function Documentation
template<typename _Type> bool HF::Core::Scheduling::Entry< _Type >::active (uint32_t _time) const inline
Check if the current entry is runnable at _time.
Parameters
[in] _time the system time.
Return values
false if the entry can't run.
true if the entry can run.
Definition at line 211 of file scheduling.h.
             {
                return (status == 0x01 &&
                        time.active(_time) &&
                        _time >= next_run);
             }
template<typename _Type> uint16_t HF::Core::Scheduling::Entry< _Type >::pack (Common::ByteArray & array, uint16_t offset = 0) const inline
Write the object on to a ByteArray so it can be sent over the network.
The buffer passed in MUST have enough size to hold the serialized object, e.g.,
Serializable obj;
ByteArray payload(obj.size());
obj.pack(payload);
Parameters
[in,out] array ByteArray reference to write the object to.
[in] offset offset to start writing to.
Returns
the number of bytes written.
Definition at line 239 of file scheduling.h.
References HF_SERIALIZABLE_CHECK, and HF::Common::ByteArray::write().
Referenced by HF::Core::Scheduling::GetEntryResponse< _Type >::pack().
             {
                HF_SERIALIZABLE_CHECK(array, offset, size());
                uint16_t start = offset;
                offset += array.write(offset, id);
                offset += array.write(offset, static_cast<uint8_t>((status << 7) & 0x80));
                offset += time.pack(array, offset);
                offset += array.write(offset, pid);
                return (offset - start);
             }
template<typename _Type> uint16_t HF::Core::Scheduling::Entry< _Type >::size () const inline
Number bytes needed to serialize the message.
Returns
number of bytes the message requires to be serialized.
Definition at line 233 of file scheduling.h.
Referenced by HF::Core::Scheduling::GetEntryResponse< _Type >::unpack().
             {
                return min_size;
             }
template<typename _Type> uint16_t HF::Core::Scheduling::Entry< _Type >::unpack (const Common::ByteArray & array, uint16_t offset = 0) inline
Read a message from a ByteArray.
Parameters
[in] array ByteArray reference to read the message from.
[in] offset offset to start reading from.
Returns
the number of bytes read.
Definition at line 254 of file scheduling.h.
References HF_ASSERT, HF_SERIALIZABLE_CHECK, and HF::Common::ByteArray::read().
Referenced by HF::Core::Scheduling::GetEntryResponse< _Type >::unpack().
             {
                HF_SERIALIZABLE_CHECK(array, offset, min_size);
                uint16_t start = offset;
                offset += array.read(offset, id);
                uint8_t flags = 0;
                offset += array.read(offset, flags);
                status  = (flags >> 7) & 0x01;
                uint16_t size = time.unpack(array, offset);
                HF_ASSERT(size != 0, {return 0;});
                offset += size;
                offset += array.read(offset, pid);
                return (offset - start);
             }
Field Documentation
template<typename _Type> constexpr uint16_t HF::Core::Scheduling::Entry< _Type >::AVAILABLE_ID = 0xFF static
Special ID for system allocated ID.
Definition at line 201 of file scheduling.h.
template<typename _Type> uint8_t HF::Core::Scheduling::Entry< _Type >::id
Event ID.
(Unique per device)
Definition at line 177 of file scheduling.h.
Referenced by HF::Core::Scheduling::Entries< _Type >::destroy(), and HF::Core::Scheduling::Entries< _Type >::save().
template<typename _Type> constexpr uint16_t HF::Core::Scheduling::Entry< _Type >::MAX_ID = 0xFE static
Upper bound for the entries ID.
Definition at line 200 of file scheduling.h.
template<typename _Type> uint32_t HF::Core::Scheduling::Entry< _Type >::next_run
Next run timestamp.
Definition at line 183 of file scheduling.h.
template<typename _Type> uint8_t HF::Core::Scheduling::Entry< _Type >::pid
Program ID to be invoked.
Definition at line 180 of file scheduling.h.
template<typename _Type> constexpr uint16_t HF::Core::Scheduling::Entry< _Type >::START_ID = 0x00 static
Lower bound for the entries ID.
Definition at line 199 of file scheduling.h.
template<typename _Type> bool HF::Core::Scheduling::Entry< _Type >::status
Event Status.
Definition at line 178 of file scheduling.h.
template<typename _Type> _Type HF::Core::Scheduling::Entry< _Type >::time
Scheduler configuration.
Definition at line 179 of file scheduling.h.
The documentation for this struct was generated from the following file:
scheduling.h