HAN-FUN API: HF::Core::AbstractService Struct Reference
HF::Core::AbstractService Struct Reference
Core Services & Interfaces » Common
This is the parent class for all services implementations.
#include <core.h>
Public Member Functions
Unit0 & unit () const
The device this unit is associated with.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
HF::Attributes::UIDS attributes (uint8_t pack_id=HF::Attributes::Pack::MANDATORY) const
Return a vector containing the attribute UIDs, for the given pack ID.
Public Member Functions inherited from HF::Interface
virtual uint16_t uid () const =0
This method returns the interface UID.
virtual Interface::Role role () const =0
Return the Interface::Role this interface implements.
Public Member Functions inherited from HF::Interfaces::AbstractInterface
Common::Result handle (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
void periodic (uint32_t time)
Handle periodic processing.
HF::Attributes::IAttribute * attribute (uint8_t uid)
Return a pointer to the interface attribute with the given uid.
Protected Member Functions
AbstractService (Unit0 &unit)
Constructor.
void send (const Protocol::Address &addr, Protocol::Message &message)
Send message msg to the network address given by addr.
void send (const Protocol::Address &addr, Protocol::Message &message, Transport::Link *link)
Create and send a new packet with the given message to the given address.
Protected Member Functions inherited from HF::Interfaces::AbstractInterface
virtual void notify (const HF::Attributes::IAttribute &old_value, const HF::Attributes::IAttribute &new_value) const
Notify that an attribute value as changed.
Common::Result check (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if message has correct attributes to be processed by the interface.
Common::Result check_payload_size (Protocol::Message &message, Common::ByteArray &payload, uint16_t offset)
Check if payload data size if sufficient for processing the message.
virtual uint16_t payload_size (Protocol::Message &message) const
Return the minimal payload size that should be present for the given message.
virtual uint16_t payload_size (Protocol::Message::Interface &itf) const
Return the minimal payload size that a message should hold when addressed at the given interface.
template<typename _Message >
uint16_t payload_size_helper () const
Helper function template to retrieve minimum size required for serializing/deserializing the class given.
virtual Common::Result handle_command (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
virtual Common::Result handle_attribute (Protocol::Packet &packet, Common::ByteArray &payload, uint16_t offset)
Handle incoming messages from the network.
virtual bool check_uid (uint16_t uid) const =0
Check if the given UID matches the interface UID.
Protected Attributes
Unit0 & _unit
Reference to the unit the service belongs to.
Additional Inherited Members
Public Types inherited from HF::Interface
enum Role { CLIENT_ROLE = 0, SERVER_ROLE = 1 }
Interface roles.
enum UID {
DEVICE_MANAGEMENT = 0x0001, BIND_MANAGEMENT = 0x0002, GROUP_MANAGEMENT = 0x0003, IDENTIFY = 0x0004,
DEVICE_INFORMATION = 0x0005, ATTRIBUTE_REPORTING = 0x0006, BATCH_PROGRAM_MANAGEMENT = 0x0007, EVENT_SCHEDULING = 0x0008,
WEEKLY_SCHEDULING = 0x0009, GROUP_TABLE = 0x000A, TAMPER_ALERT = 0x0101, TIME = 0x0102,
POWER = 0x0110, KEEP_ALIVE = 0x0115, RSSI = 0x0111, SUOTA = 0x0400,
ALERT = 0x0100, ON_OFF = 0x0200, LEVEL_CONTROL = 0x0201, COLOUR_CONTROL = 0x0202,
SIMPLE_KEYPAD = 0x0203, SIMPLE_POWER_METER = 0x0300, SIMPLE_TEMPERATURE = 0x0301, SIMPLE_HUMIDITY = 0x0302,
SIMPLE_THERMOSTAT = 0x0303, SIMPLE_BUTTON = 0x0304, SIMPLE_VISUAL_EFFECTS = 0x0305, SIMPLE_AIR_PRESSURE = 0x0306,
SIMPLE_LIGHT_SENSOR = 0x0307, RESERVED = 0x7F00, MAX_UID = 0x7FFE, ANY_UID = 0x7FFF
}
Interfaces Unique Identifiers (UID).
Static Public Attributes inherited from HF::Interface
static constexpr uint8_t MAX_CMD_ID = 0xFF
Maximum value for command IDs in interfaces.
Detailed Description
This is the parent class for all services implementations.
Definition at line 134 of file core.h.
Constructor & Destructor Documentation
AbstractService()
HF::Core::AbstractService::AbstractService (Unit0 & unit) inline protected
Constructor.
Parameters
[in] unit reference to the unit that holds this service.
Definition at line 164 of file core.h.
                                      : _unit(unit)
          {}
Member Function Documentation
attribute()
HF::Attributes::IAttribute* HF::Core::AbstractService::attribute (uint8_t uid) inline virtual
Return a pointer to the interface attribute with the given uid.
Parameters
[in] uid identifier of the attribute in the interface.
Returns
a pointer to the attribute if it exists, nullptr otherwise.
Implements HF::Interface.
Definition at line 144 of file core.h.
References HF::Interface::uid().
          {
             return AbstractInterface::attribute(uid);
          }
attributes()
HF::Attributes::UIDS HF::Core::AbstractService::attributes (uint8_t pack_id = HF::Attributes::Pack::MANDATORY) const inline virtual
Return a vector containing the attribute UIDs, for the given pack ID.
Parameters
[in] pack_id the Attribute pack ID to get the attributes UIDs for.
Returns
vector containing the attributes UIDs.
Reimplemented from HF::Interfaces::AbstractInterface.
Definition at line 149 of file core.h.
          {
             return AbstractInterface::attributes(pack_id);
          }
send() [1/2]
void HF::Core::AbstractService::send (const Protocol::Address & addr, Protocol::Message & message) inline protected virtual
Send message msg to the network address given by addr.
Parameters
[in] addr HF network address.
[in] message pointer to the message to be sent to the network.
Implements HF::Interfaces::AbstractInterface.
Definition at line 168 of file core.h.
References HF::Units::AbstractUnit::send(), and unit().
          {
             unit().send(addr, message, nullptr);
          }
send() [2/2]
void HF::Core::AbstractService::send (const Protocol::Address & addr, Protocol::Message & message, Transport::Link * link) inline protected
Create and send a new packet with the given message to the given address.
Parameters
[in] addr address to send the message to.
[in] message message to send.
[in] link preferred link to send the message on.
Definition at line 174 of file core.h.
References HF::Units::AbstractUnit::send(), and unit().
          {
             unit().send(addr, message, link);
          }
The documentation for this struct was generated from the following file:
core.h